// Code generated - DO NOT EDIT.
// +build gtk_3.10

package gtk

import c "github.com/pekim/gobbi/lib/internal/c"

// #include <gtk/gtk-a11y.h>
// #include <gtk/gtk.h>
// #include <gtk/gtkx.h>
import "C"

// bitfields
type AccelFlags C.GtkAccelFlags
type ApplicationInhibitFlags C.GtkApplicationInhibitFlags
type AttachOptions C.GtkAttachOptions
type CalendarDisplayOptions C.GtkCalendarDisplayOptions
type CellRendererState C.GtkCellRendererState
type DebugFlag C.GtkDebugFlag
type DestDefaults C.GtkDestDefaults
type DialogFlags C.GtkDialogFlags
type EventControllerScrollFlags c.UnusupportedByVersion
type FileFilterFlags C.GtkFileFilterFlags
type FontChooserLevel c.UnusupportedByVersion
type IconLookupFlags C.GtkIconLookupFlags
type InputHints C.GtkInputHints
type JunctionSides C.GtkJunctionSides
type PlacesOpenFlags C.GtkPlacesOpenFlags
type RcFlags C.GtkRcFlags
type RecentFilterFlags C.GtkRecentFilterFlags
type RegionFlags C.GtkRegionFlags
type StateFlags C.GtkStateFlags
type StyleContextPrintFlags C.GtkStyleContextPrintFlags
type TargetFlags C.GtkTargetFlags
type TextSearchFlags C.GtkTextSearchFlags
type ToolPaletteDragTargets C.GtkToolPaletteDragTargets
type TreeModelFlags C.GtkTreeModelFlags
type UIManagerItemType C.GtkUIManagerItemType

// enumerations
type Align C.GtkAlign
type ArrowPlacement C.GtkArrowPlacement
type ArrowType C.GtkArrowType
type AssistantPageType C.GtkAssistantPageType
type BaselinePosition C.GtkBaselinePosition
type BorderStyle C.GtkBorderStyle
type BuilderError C.GtkBuilderError
type ButtonBoxStyle C.GtkButtonBoxStyle
type ButtonRole C.GtkButtonRole
type ButtonsType C.GtkButtonsType
type CellRendererAccelMode C.GtkCellRendererAccelMode
type CellRendererMode C.GtkCellRendererMode
type CornerType C.GtkCornerType
type CssProviderError C.GtkCssProviderError
type CssSectionType C.GtkCssSectionType
type DeleteType C.GtkDeleteType
type DirectionType C.GtkDirectionType
type DragResult C.GtkDragResult
type EntryIconPosition C.GtkEntryIconPosition
type EventSequenceState c.UnusupportedByVersion
type ExpanderStyle C.GtkExpanderStyle
type FileChooserAction C.GtkFileChooserAction
type FileChooserConfirmation C.GtkFileChooserConfirmation
type FileChooserError C.GtkFileChooserError
type IMPreeditStyle C.GtkIMPreeditStyle
type IMStatusStyle C.GtkIMStatusStyle
type IconSize C.GtkIconSize
type IconThemeError C.GtkIconThemeError
type IconViewDropPosition C.GtkIconViewDropPosition
type ImageType C.GtkImageType
type InputPurpose C.GtkInputPurpose
type Justification C.GtkJustification
type LevelBarMode C.GtkLevelBarMode
type License C.GtkLicense
type MenuDirectionType C.GtkMenuDirectionType
type MessageType C.GtkMessageType
type MovementStep C.GtkMovementStep
type NotebookTab C.GtkNotebookTab
type NumberUpLayout C.GtkNumberUpLayout
type Orientation C.GtkOrientation
type PackDirection C.GtkPackDirection
type PackType C.GtkPackType
type PadActionType C.GtkPadActionType
type PageOrientation C.GtkPageOrientation
type PageSet C.GtkPageSet
type PanDirection c.UnusupportedByVersion
type PathPriorityType C.GtkPathPriorityType
type PathType C.GtkPathType
type PolicyType C.GtkPolicyType
type PopoverConstraint c.UnusupportedByVersion
type PositionType C.GtkPositionType
type PrintDuplex C.GtkPrintDuplex
type PrintError C.GtkPrintError
type PrintOperationAction C.GtkPrintOperationAction
type PrintOperationResult C.GtkPrintOperationResult
type PrintPages C.GtkPrintPages
type PrintQuality C.GtkPrintQuality
type PrintStatus C.GtkPrintStatus
type PropagationPhase c.UnusupportedByVersion
type RcTokenType C.GtkRcTokenType
type RecentChooserError C.GtkRecentChooserError
type RecentManagerError C.GtkRecentManagerError
type RecentSortType C.GtkRecentSortType
type ReliefStyle C.GtkReliefStyle
type ResizeMode C.GtkResizeMode
type ResponseType C.GtkResponseType
type RevealerTransitionType C.GtkRevealerTransitionType
type ScrollStep C.GtkScrollStep
type ScrollType C.GtkScrollType
type ScrollablePolicy C.GtkScrollablePolicy
type SelectionMode C.GtkSelectionMode
type SensitivityType C.GtkSensitivityType
type ShadowType C.GtkShadowType
type ShortcutType c.UnusupportedByVersion
type SizeGroupMode C.GtkSizeGroupMode
type SizeRequestMode C.GtkSizeRequestMode
type SortType C.GtkSortType
type SpinButtonUpdatePolicy C.GtkSpinButtonUpdatePolicy
type SpinType C.GtkSpinType
type StackTransitionType C.GtkStackTransitionType
type StateType C.GtkStateType
type TextBufferTargetInfo C.GtkTextBufferTargetInfo
type TextDirection C.GtkTextDirection
type TextExtendSelection c.UnusupportedByVersion
type TextViewLayer C.GtkTextViewLayer
type TextWindowType C.GtkTextWindowType
type ToolbarSpaceStyle C.GtkToolbarSpaceStyle
type ToolbarStyle C.GtkToolbarStyle
type TreeViewColumnSizing C.GtkTreeViewColumnSizing
type TreeViewDropPosition C.GtkTreeViewDropPosition
type TreeViewGridLines C.GtkTreeViewGridLines
type Unit C.GtkUnit
type WidgetHelpType C.GtkWidgetHelpType
type WindowPosition C.GtkWindowPosition
type WindowType C.GtkWindowType
type WrapMode C.GtkWrapMode
