// Code generated - DO NOT EDIT.

package gdk

// AddOptionEntriesLibgtkOnly is a representation of the C type gdk_add_option_entries_libgtk_only.
// AtomIntern is a representation of the C type gdk_atom_intern.
// AtomInternStaticString is a representation of the C type gdk_atom_intern_static_string.
// Beep is a representation of the C type gdk_beep.
// CairoCreate is a representation of the C type gdk_cairo_create.
// CairoDrawFromGl is a representation of the C type gdk_cairo_draw_from_gl.
// CairoGetClipRectangle is a representation of the C type gdk_cairo_get_clip_rectangle.
// CairoGetDrawingContext is a representation of the C type gdk_cairo_get_drawing_context.
// CairoRectangle is a representation of the C type gdk_cairo_rectangle.
// CairoRegion is a representation of the C type gdk_cairo_region.
// CairoRegionCreateFromSurface is a representation of the C type gdk_cairo_region_create_from_surface.
// CairoSetSourceColor is a representation of the C type gdk_cairo_set_source_color.
// CairoSetSourcePixbuf is a representation of the C type gdk_cairo_set_source_pixbuf.
// CairoSetSourceRgba is a representation of the C type gdk_cairo_set_source_rgba.
// CairoSetSourceWindow is a representation of the C type gdk_cairo_set_source_window.
// CairoSurfaceCreateFromPixbuf is a representation of the C type gdk_cairo_surface_create_from_pixbuf.
// ColorParse is a representation of the C type gdk_color_parse.
// DisableMultidevice is a representation of the C type gdk_disable_multidevice.
// DragAbort is a representation of the C type gdk_drag_abort.
// DragBegin is a representation of the C type gdk_drag_begin.
// DragBeginForDevice is a representation of the C type gdk_drag_begin_for_device.
// DragBeginFromPoint is a representation of the C type gdk_drag_begin_from_point.
// DragDrop is a representation of the C type gdk_drag_drop.
// DragDropDone is a representation of the C type gdk_drag_drop_done.
// DragDropSucceeded is a representation of the C type gdk_drag_drop_succeeded.
// DragFindWindowForScreen is a representation of the C type gdk_drag_find_window_for_screen.
// DragGetSelection is a representation of the C type gdk_drag_get_selection.
// DragMotion is a representation of the C type gdk_drag_motion.
// DragStatus is a representation of the C type gdk_drag_status.
// DropFinish is a representation of the C type gdk_drop_finish.
// DropReply is a representation of the C type gdk_drop_reply.
// ErrorTrapPop is a representation of the C type gdk_error_trap_pop.
// ErrorTrapPopIgnored is a representation of the C type gdk_error_trap_pop_ignored.
// ErrorTrapPush is a representation of the C type gdk_error_trap_push.
// EventGet is a representation of the C type gdk_event_get.
// EventHandlerSet is a representation of the C type gdk_event_handler_set.
// EventPeek is a representation of the C type gdk_event_peek.
// EventRequestMotions is a representation of the C type gdk_event_request_motions.
// EventsGetAngle is a representation of the C type gdk_events_get_angle.
// EventsGetCenter is a representation of the C type gdk_events_get_center.
// EventsGetDistance is a representation of the C type gdk_events_get_distance.
// EventsPending is a representation of the C type gdk_events_pending.
// Flush is a representation of the C type gdk_flush.
// GetDefaultRootWindow is a representation of the C type gdk_get_default_root_window.
// GetDisplay is a representation of the C type gdk_get_display.
// GetDisplayArgName is a representation of the C type gdk_get_display_arg_name.
// GetProgramClass is a representation of the C type gdk_get_program_class.
// GetShowEvents is a representation of the C type gdk_get_show_events.
// GlErrorQuark is a representation of the C type gdk_gl_error_quark.
// Init is a representation of the C type gdk_init.
// InitCheck is a representation of the C type gdk_init_check.
// KeyboardGrab is a representation of the C type gdk_keyboard_grab.
// KeyboardUngrab is a representation of the C type gdk_keyboard_ungrab.
// KeyvalConvertCase is a representation of the C type gdk_keyval_convert_case.
// KeyvalFromName is a representation of the C type gdk_keyval_from_name.
// KeyvalIsLower is a representation of the C type gdk_keyval_is_lower.
// KeyvalIsUpper is a representation of the C type gdk_keyval_is_upper.
// KeyvalName is a representation of the C type gdk_keyval_name.
// KeyvalToLower is a representation of the C type gdk_keyval_to_lower.
// KeyvalToUnicode is a representation of the C type gdk_keyval_to_unicode.
// KeyvalToUpper is a representation of the C type gdk_keyval_to_upper.
// ListVisuals is a representation of the C type gdk_list_visuals.
// NotifyStartupComplete is a representation of the C type gdk_notify_startup_complete.
// NotifyStartupCompleteWithId is a representation of the C type gdk_notify_startup_complete_with_id.
// OffscreenWindowGetEmbedder is a representation of the C type gdk_offscreen_window_get_embedder.
// OffscreenWindowGetSurface is a representation of the C type gdk_offscreen_window_get_surface.
// OffscreenWindowSetEmbedder is a representation of the C type gdk_offscreen_window_set_embedder.
// PangoContextGet is a representation of the C type gdk_pango_context_get.
// PangoContextGetForDisplay is a representation of the C type gdk_pango_context_get_for_display.
// PangoContextGetForScreen is a representation of the C type gdk_pango_context_get_for_screen.
// PangoLayoutGetClipRegion is a representation of the C type gdk_pango_layout_get_clip_region.
// PangoLayoutLineGetClipRegion is a representation of the C type gdk_pango_layout_line_get_clip_region.
// ParseArgs is a representation of the C type gdk_parse_args.
// PixbufGetFromSurface is a representation of the C type gdk_pixbuf_get_from_surface.
// PixbufGetFromWindow is a representation of the C type gdk_pixbuf_get_from_window.
// PointerGrab is a representation of the C type gdk_pointer_grab.
// PointerIsGrabbed is a representation of the C type gdk_pointer_is_grabbed.
// PointerUngrab is a representation of the C type gdk_pointer_ungrab.
// PreParseLibgtkOnly is a representation of the C type gdk_pre_parse_libgtk_only.
// PropertyChange is a representation of the C type gdk_property_change.
// PropertyDelete is a representation of the C type gdk_property_delete.
// PropertyGet is a representation of the C type gdk_property_get.
// QueryDepths is a representation of the C type gdk_query_depths.
// QueryVisualTypes is a representation of the C type gdk_query_visual_types.
// SelectionConvert is a representation of the C type gdk_selection_convert.
// SelectionOwnerGet is a representation of the C type gdk_selection_owner_get.
// SelectionOwnerGetForDisplay is a representation of the C type gdk_selection_owner_get_for_display.
// SelectionOwnerSet is a representation of the C type gdk_selection_owner_set.
// SelectionOwnerSetForDisplay is a representation of the C type gdk_selection_owner_set_for_display.
// SelectionPropertyGet is a representation of the C type gdk_selection_property_get.
// SelectionSendNotify is a representation of the C type gdk_selection_send_notify.
// SelectionSendNotifyForDisplay is a representation of the C type gdk_selection_send_notify_for_display.
// SetAllowedBackends is a representation of the C type gdk_set_allowed_backends.
// SetDoubleClickTime is a representation of the C type gdk_set_double_click_time.
// SetProgramClass is a representation of the C type gdk_set_program_class.
// SetShowEvents is a representation of the C type gdk_set_show_events.
// SettingGet is a representation of the C type gdk_setting_get.
// SynthesizeWindowState is a representation of the C type gdk_synthesize_window_state.
// TestRenderSync is a representation of the C type gdk_test_render_sync.
// TestSimulateButton is a representation of the C type gdk_test_simulate_button.
// TestSimulateKey is a representation of the C type gdk_test_simulate_key.
// TextPropertyToUtf8ListForDisplay is a representation of the C type gdk_text_property_to_utf8_list_for_display.
// ThreadsAddIdle is a representation of the C type gdk_threads_add_idle.
// ThreadsAddIdleFull is a representation of the C type gdk_threads_add_idle_full.
// ThreadsAddTimeout is a representation of the C type gdk_threads_add_timeout.
// ThreadsAddTimeoutFull is a representation of the C type gdk_threads_add_timeout_full.
// ThreadsAddTimeoutSeconds is a representation of the C type gdk_threads_add_timeout_seconds.
// ThreadsAddTimeoutSecondsFull is a representation of the C type gdk_threads_add_timeout_seconds_full.
// ThreadsEnter is a representation of the C type gdk_threads_enter.
// ThreadsInit is a representation of the C type gdk_threads_init.
// ThreadsLeave is a representation of the C type gdk_threads_leave.
// ThreadsSetLockFunctions is a representation of the C type gdk_threads_set_lock_functions.
// UnicodeToKeyval is a representation of the C type gdk_unicode_to_keyval.
// Utf8ToStringTarget is a representation of the C type gdk_utf8_to_string_target.
