// Code generated - DO NOT EDIT.

package atk

type CoordType uint32

const (
	CoordType_Screen CoordType = int64(0)
	CoordType_Window CoordType = int64(1)
	CoordType_Parent CoordType = int64(2)
)

type KeyEventType uint32

const (
	KeyEventType_Press       KeyEventType = int64(0)
	KeyEventType_Release     KeyEventType = int64(1)
	KeyEventType_LastDefined KeyEventType = int64(2)
)

type Layer uint32

const (
	Layer_Invalid    Layer = int64(0)
	Layer_Background Layer = int64(1)
	Layer_Canvas     Layer = int64(2)
	Layer_Widget     Layer = int64(3)
	Layer_Mdi        Layer = int64(4)
	Layer_Popup      Layer = int64(5)
	Layer_Overlay    Layer = int64(6)
	Layer_Window     Layer = int64(7)
)

type RelationType uint32

const (
	RelationType_Null           RelationType = int64(0)
	RelationType_ControlledBy   RelationType = int64(1)
	RelationType_ControllerFor  RelationType = int64(2)
	RelationType_LabelFor       RelationType = int64(3)
	RelationType_LabelledBy     RelationType = int64(4)
	RelationType_MemberOf       RelationType = int64(5)
	RelationType_NodeChildOf    RelationType = int64(6)
	RelationType_FlowsTo        RelationType = int64(7)
	RelationType_FlowsFrom      RelationType = int64(8)
	RelationType_SubwindowOf    RelationType = int64(9)
	RelationType_Embeds         RelationType = int64(10)
	RelationType_EmbeddedBy     RelationType = int64(11)
	RelationType_PopupFor       RelationType = int64(12)
	RelationType_ParentWindowOf RelationType = int64(13)
	RelationType_DescribedBy    RelationType = int64(14)
	RelationType_DescriptionFor RelationType = int64(15)
	RelationType_NodeParentOf   RelationType = int64(16)
	RelationType_Details        RelationType = int64(17)
	RelationType_DetailsFor     RelationType = int64(18)
	RelationType_ErrorMessage   RelationType = int64(19)
	RelationType_ErrorFor       RelationType = int64(20)
	RelationType_LastDefined    RelationType = int64(21)
)

type Role uint32

const (
	Role_Invalid              Role = int64(0)
	Role_AcceleratorLabel     Role = int64(1)
	Role_Alert                Role = int64(2)
	Role_Animation            Role = int64(3)
	Role_Arrow                Role = int64(4)
	Role_Calendar             Role = int64(5)
	Role_Canvas               Role = int64(6)
	Role_CheckBox             Role = int64(7)
	Role_CheckMenuItem        Role = int64(8)
	Role_ColorChooser         Role = int64(9)
	Role_ColumnHeader         Role = int64(10)
	Role_ComboBox             Role = int64(11)
	Role_DateEditor           Role = int64(12)
	Role_DesktopIcon          Role = int64(13)
	Role_DesktopFrame         Role = int64(14)
	Role_Dial                 Role = int64(15)
	Role_Dialog               Role = int64(16)
	Role_DirectoryPane        Role = int64(17)
	Role_DrawingArea          Role = int64(18)
	Role_FileChooser          Role = int64(19)
	Role_Filler               Role = int64(20)
	Role_FontChooser          Role = int64(21)
	Role_Frame                Role = int64(22)
	Role_GlassPane            Role = int64(23)
	Role_HtmlContainer        Role = int64(24)
	Role_Icon                 Role = int64(25)
	Role_Image                Role = int64(26)
	Role_InternalFrame        Role = int64(27)
	Role_Label                Role = int64(28)
	Role_LayeredPane          Role = int64(29)
	Role_List                 Role = int64(30)
	Role_ListItem             Role = int64(31)
	Role_Menu                 Role = int64(32)
	Role_MenuBar              Role = int64(33)
	Role_MenuItem             Role = int64(34)
	Role_OptionPane           Role = int64(35)
	Role_PageTab              Role = int64(36)
	Role_PageTabList          Role = int64(37)
	Role_Panel                Role = int64(38)
	Role_PasswordText         Role = int64(39)
	Role_PopupMenu            Role = int64(40)
	Role_ProgressBar          Role = int64(41)
	Role_PushButton           Role = int64(42)
	Role_RadioButton          Role = int64(43)
	Role_RadioMenuItem        Role = int64(44)
	Role_RootPane             Role = int64(45)
	Role_RowHeader            Role = int64(46)
	Role_ScrollBar            Role = int64(47)
	Role_ScrollPane           Role = int64(48)
	Role_Separator            Role = int64(49)
	Role_Slider               Role = int64(50)
	Role_SplitPane            Role = int64(51)
	Role_SpinButton           Role = int64(52)
	Role_Statusbar            Role = int64(53)
	Role_Table                Role = int64(54)
	Role_TableCell            Role = int64(55)
	Role_TableColumnHeader    Role = int64(56)
	Role_TableRowHeader       Role = int64(57)
	Role_TearOffMenuItem      Role = int64(58)
	Role_Terminal             Role = int64(59)
	Role_Text                 Role = int64(60)
	Role_ToggleButton         Role = int64(61)
	Role_ToolBar              Role = int64(62)
	Role_ToolTip              Role = int64(63)
	Role_Tree                 Role = int64(64)
	Role_TreeTable            Role = int64(65)
	Role_Unknown              Role = int64(66)
	Role_Viewport             Role = int64(67)
	Role_Window               Role = int64(68)
	Role_Header               Role = int64(69)
	Role_Footer               Role = int64(70)
	Role_Paragraph            Role = int64(71)
	Role_Ruler                Role = int64(72)
	Role_Application          Role = int64(73)
	Role_Autocomplete         Role = int64(74)
	Role_EditBar              Role = int64(75)
	Role_Embedded             Role = int64(76)
	Role_Entry                Role = int64(77)
	Role_Chart                Role = int64(78)
	Role_Caption              Role = int64(79)
	Role_DocumentFrame        Role = int64(80)
	Role_Heading              Role = int64(81)
	Role_Page                 Role = int64(82)
	Role_Section              Role = int64(83)
	Role_RedundantObject      Role = int64(84)
	Role_Form                 Role = int64(85)
	Role_Link                 Role = int64(86)
	Role_InputMethodWindow    Role = int64(87)
	Role_TableRow             Role = int64(88)
	Role_TreeItem             Role = int64(89)
	Role_DocumentSpreadsheet  Role = int64(90)
	Role_DocumentPresentation Role = int64(91)
	Role_DocumentText         Role = int64(92)
	Role_DocumentWeb          Role = int64(93)
	Role_DocumentEmail        Role = int64(94)
	Role_Comment              Role = int64(95)
	Role_ListBox              Role = int64(96)
	Role_Grouping             Role = int64(97)
	Role_ImageMap             Role = int64(98)
	Role_Notification         Role = int64(99)
	Role_InfoBar              Role = int64(100)
	Role_LevelBar             Role = int64(101)
	Role_TitleBar             Role = int64(102)
	Role_BlockQuote           Role = int64(103)
	Role_Audio                Role = int64(104)
	Role_Video                Role = int64(105)
	Role_Definition           Role = int64(106)
	Role_Article              Role = int64(107)
	Role_Landmark             Role = int64(108)
	Role_Log                  Role = int64(109)
	Role_Marquee              Role = int64(110)
	Role_Math                 Role = int64(111)
	Role_Rating               Role = int64(112)
	Role_Timer                Role = int64(113)
	Role_DescriptionList      Role = int64(114)
	Role_DescriptionTerm      Role = int64(115)
	Role_DescriptionValue     Role = int64(116)
	Role_Static               Role = int64(117)
	Role_MathFraction         Role = int64(118)
	Role_MathRoot             Role = int64(119)
	Role_Subscript            Role = int64(120)
	Role_Superscript          Role = int64(121)
	Role_Footnote             Role = int64(122)
	Role_LastDefined          Role = int64(123)
)

type ScrollType uint32

const (
	ScrollType_TopLeft     ScrollType = int64(0)
	ScrollType_BottomRight ScrollType = int64(1)
	ScrollType_TopEdge     ScrollType = int64(2)
	ScrollType_BottomEdge  ScrollType = int64(3)
	ScrollType_LeftEdge    ScrollType = int64(4)
	ScrollType_RightEdge   ScrollType = int64(5)
	ScrollType_Anywhere    ScrollType = int64(6)
)

type StateType uint32

const (
	StateType_Invalid                StateType = int64(0)
	StateType_Active                 StateType = int64(1)
	StateType_Armed                  StateType = int64(2)
	StateType_Busy                   StateType = int64(3)
	StateType_Checked                StateType = int64(4)
	StateType_Defunct                StateType = int64(5)
	StateType_Editable               StateType = int64(6)
	StateType_Enabled                StateType = int64(7)
	StateType_Expandable             StateType = int64(8)
	StateType_Expanded               StateType = int64(9)
	StateType_Focusable              StateType = int64(10)
	StateType_Focused                StateType = int64(11)
	StateType_Horizontal             StateType = int64(12)
	StateType_Iconified              StateType = int64(13)
	StateType_Modal                  StateType = int64(14)
	StateType_MultiLine              StateType = int64(15)
	StateType_Multiselectable        StateType = int64(16)
	StateType_Opaque                 StateType = int64(17)
	StateType_Pressed                StateType = int64(18)
	StateType_Resizable              StateType = int64(19)
	StateType_Selectable             StateType = int64(20)
	StateType_Selected               StateType = int64(21)
	StateType_Sensitive              StateType = int64(22)
	StateType_Showing                StateType = int64(23)
	StateType_SingleLine             StateType = int64(24)
	StateType_Stale                  StateType = int64(25)
	StateType_Transient              StateType = int64(26)
	StateType_Vertical               StateType = int64(27)
	StateType_Visible                StateType = int64(28)
	StateType_ManagesDescendants     StateType = int64(29)
	StateType_Indeterminate          StateType = int64(30)
	StateType_Truncated              StateType = int64(31)
	StateType_Required               StateType = int64(32)
	StateType_InvalidEntry           StateType = int64(33)
	StateType_SupportsAutocompletion StateType = int64(34)
	StateType_SelectableText         StateType = int64(35)
	StateType_Default                StateType = int64(36)
	StateType_Animated               StateType = int64(37)
	StateType_Visited                StateType = int64(38)
	StateType_Checkable              StateType = int64(39)
	StateType_HasPopup               StateType = int64(40)
	StateType_HasTooltip             StateType = int64(41)
	StateType_ReadOnly               StateType = int64(42)
	StateType_LastDefined            StateType = int64(43)
)

type TextAttribute uint32

const (
	TextAttribute_Invalid          TextAttribute = int64(0)
	TextAttribute_LeftMargin       TextAttribute = int64(1)
	TextAttribute_RightMargin      TextAttribute = int64(2)
	TextAttribute_Indent           TextAttribute = int64(3)
	TextAttribute_Invisible        TextAttribute = int64(4)
	TextAttribute_Editable         TextAttribute = int64(5)
	TextAttribute_PixelsAboveLines TextAttribute = int64(6)
	TextAttribute_PixelsBelowLines TextAttribute = int64(7)
	TextAttribute_PixelsInsideWrap TextAttribute = int64(8)
	TextAttribute_BgFullHeight     TextAttribute = int64(9)
	TextAttribute_Rise             TextAttribute = int64(10)
	TextAttribute_Underline        TextAttribute = int64(11)
	TextAttribute_Strikethrough    TextAttribute = int64(12)
	TextAttribute_Size             TextAttribute = int64(13)
	TextAttribute_Scale            TextAttribute = int64(14)
	TextAttribute_Weight           TextAttribute = int64(15)
	TextAttribute_Language         TextAttribute = int64(16)
	TextAttribute_FamilyName       TextAttribute = int64(17)
	TextAttribute_BgColor          TextAttribute = int64(18)
	TextAttribute_FgColor          TextAttribute = int64(19)
	TextAttribute_BgStipple        TextAttribute = int64(20)
	TextAttribute_FgStipple        TextAttribute = int64(21)
	TextAttribute_WrapMode         TextAttribute = int64(22)
	TextAttribute_Direction        TextAttribute = int64(23)
	TextAttribute_Justification    TextAttribute = int64(24)
	TextAttribute_Stretch          TextAttribute = int64(25)
	TextAttribute_Variant          TextAttribute = int64(26)
	TextAttribute_Style            TextAttribute = int64(27)
	TextAttribute_LastDefined      TextAttribute = int64(28)
)

type TextBoundary uint32

const (
	TextBoundary_Char          TextBoundary = int64(0)
	TextBoundary_WordStart     TextBoundary = int64(1)
	TextBoundary_WordEnd       TextBoundary = int64(2)
	TextBoundary_SentenceStart TextBoundary = int64(3)
	TextBoundary_SentenceEnd   TextBoundary = int64(4)
	TextBoundary_LineStart     TextBoundary = int64(5)
	TextBoundary_LineEnd       TextBoundary = int64(6)
)

type TextClipType uint32

const (
	TextClipType_None TextClipType = int64(0)
	TextClipType_Min  TextClipType = int64(1)
	TextClipType_Max  TextClipType = int64(2)
	TextClipType_Both TextClipType = int64(3)
)

type TextGranularity uint32

const (
	TextGranularity_Char      TextGranularity = int64(0)
	TextGranularity_Word      TextGranularity = int64(1)
	TextGranularity_Sentence  TextGranularity = int64(2)
	TextGranularity_Line      TextGranularity = int64(3)
	TextGranularity_Paragraph TextGranularity = int64(4)
)

type ValueType uint32

const (
	ValueType_VeryWeak    ValueType = int64(0)
	ValueType_Weak        ValueType = int64(1)
	ValueType_Acceptable  ValueType = int64(2)
	ValueType_Strong      ValueType = int64(3)
	ValueType_VeryStrong  ValueType = int64(4)
	ValueType_VeryLow     ValueType = int64(5)
	ValueType_Low         ValueType = int64(6)
	ValueType_Medium      ValueType = int64(7)
	ValueType_High        ValueType = int64(8)
	ValueType_VeryHigh    ValueType = int64(9)
	ValueType_VeryBad     ValueType = int64(10)
	ValueType_Bad         ValueType = int64(11)
	ValueType_Good        ValueType = int64(12)
	ValueType_VeryGood    ValueType = int64(13)
	ValueType_Best        ValueType = int64(14)
	ValueType_LastDefined ValueType = int64(15)
)
