image: ubuntu/lts
packages:
  - build-essential
  - libatk1.0-dev
  - libcairo2-dev
  - libglib2.0-dev
  - libgtk-3-dev
  - libgtksourceview-3.0-dev
  - libpango1.0-dev
  - xvfb
sources:
  - https://github.com/pekim/gobbi/
tasks:
  - install-go: |
      wget -nv https://dl.google.com/go/go1.12.4.linux-amd64.tar.gz
      sudo tar -C /usr/local -xzf go1.12.4.linux-amd64.tar.gz
      sudo ln -s /usr/local/go/bin/go /usr/bin/go
  - generate: |
      cd gobbi/internal
      ./gobbi generate
  - test: |
      cd gobbi/internal
      xvfb-run ./gobbi test
triggers:
  - action: email
    condition: always
    to: Mike D Pilsbury <mike.pilsbury@gmail.com>
