pool:
  vmImage: 'ubuntu-latest'

variables:
#  GOBIN:  '$(GOPATH)/bin' # Go binaries path
#  GOROOT: '/usr/local/go1.12.1' # Go installation path
#  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  GO111MODULE: 'on'
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
  - script: |
      sudo apt install -y \
        libatk1.0-dev \
        libcairo2-dev \
        libglib2.0-dev \
        libgtk-3-dev \
        libgtksourceview-3.0-dev \
        libpango1.0-dev \
        xvfb
    displayName: 'install dependencies'

  # Go Tool Installer
  # Finds or downloads a specific version of Go in the tools cache and adds it to the PATH. Use this to set the version of Go used in subsequent tasks.
  - task: GoTool@0
    inputs:
      version: '1.12.5'
      #goPath: # Optional
      #goBin: # Optional
    displayName: 'install Go'

  - script: |
      mkdir -p '$(GOBIN)'
      mkdir -p '$(GOPATH)/pkg'
      mkdir -p '$(modulePath)'
      shopt -s extglob
      shopt -s dotglob
      mv !(gopath) '$(modulePath)'
      echo '##vso[task.prependpath]$(GOBIN)'
      echo '##vso[task.prependpath]$(GOROOT)/bin'
    displayName: 'set up Go workspace'

  - script: |
      ./gobbi generate
    workingDirectory: '$(modulePath)'
    displayName: 'generate'

  - script: |
      xvfb-run ./gobbi test
    workingDirectory: '$(modulePath)'
    displayName: 'test'
