// Code generated - DO NOT EDIT.

package javascriptcore

const MAJOR_VERSION int32 = "2"
const MICRO_VERSION int32 = "1"
const MINOR_VERSION int32 = "26"

// UNSUPPORTED : OPTIONS_USE_DFG
// UNSUPPORTED : OPTIONS_USE_FTL
// UNSUPPORTED : OPTIONS_USE_JIT
// UNSUPPORTED : OPTIONS_USE_LLINT
