// Code generated - DO NOT EDIT.

package gdk

// constant : BUTTON_MIDDLE
// constant : BUTTON_PRIMARY
// constant : BUTTON_SECONDARY
// constant : CURRENT_TIME
// constant : EVENT_PROPAGATE
// constant : EVENT_STOP
// constant : KEY_0
// constant : KEY_1
// constant : KEY_2
// constant : KEY_3
// constant : KEY_3270_AltCursor
// constant : KEY_3270_Attn
// constant : KEY_3270_BackTab
// constant : KEY_3270_ChangeScreen
// constant : KEY_3270_Copy
// constant : KEY_3270_CursorBlink
// constant : KEY_3270_CursorSelect
// constant : KEY_3270_DeleteWord
// constant : KEY_3270_Duplicate
// constant : KEY_3270_Enter
// constant : KEY_3270_EraseEOF
// constant : KEY_3270_EraseInput
// constant : KEY_3270_ExSelect
// constant : KEY_3270_FieldMark
// constant : KEY_3270_Ident
// constant : KEY_3270_Jump
// constant : KEY_3270_KeyClick
// constant : KEY_3270_Left2
// constant : KEY_3270_PA1
// constant : KEY_3270_PA2
// constant : KEY_3270_PA3
// constant : KEY_3270_Play
// constant : KEY_3270_PrintScreen
// constant : KEY_3270_Quit
// constant : KEY_3270_Record
// constant : KEY_3270_Reset
// constant : KEY_3270_Right2
// constant : KEY_3270_Rule
// constant : KEY_3270_Setup
// constant : KEY_3270_Test
// constant : KEY_4
// constant : KEY_5
// constant : KEY_6
// constant : KEY_7
// constant : KEY_8
// constant : KEY_9
// constant : KEY_A
// constant : KEY_AE
// constant : KEY_Aacute
// constant : KEY_Abelowdot
// constant : KEY_Abreve
// constant : KEY_Abreveacute
// constant : KEY_Abrevebelowdot
// constant : KEY_Abrevegrave
// constant : KEY_Abrevehook
// constant : KEY_Abrevetilde
// constant : KEY_AccessX_Enable
// constant : KEY_AccessX_Feedback_Enable
// constant : KEY_Acircumflex
// constant : KEY_Acircumflexacute
// constant : KEY_Acircumflexbelowdot
// constant : KEY_Acircumflexgrave
// constant : KEY_Acircumflexhook
// constant : KEY_Acircumflextilde
// constant : KEY_AddFavorite
// constant : KEY_Adiaeresis
// constant : KEY_Agrave
// constant : KEY_Ahook
// constant : KEY_Alt_L
// constant : KEY_Alt_R
// constant : KEY_Amacron
// constant : KEY_Aogonek
// constant : KEY_ApplicationLeft
// constant : KEY_ApplicationRight
// constant : KEY_Arabic_0
// constant : KEY_Arabic_1
// constant : KEY_Arabic_2
// constant : KEY_Arabic_3
// constant : KEY_Arabic_4
// constant : KEY_Arabic_5
// constant : KEY_Arabic_6
// constant : KEY_Arabic_7
// constant : KEY_Arabic_8
// constant : KEY_Arabic_9
// constant : KEY_Arabic_ain
// constant : KEY_Arabic_alef
// constant : KEY_Arabic_alefmaksura
// constant : KEY_Arabic_beh
// constant : KEY_Arabic_comma
// constant : KEY_Arabic_dad
// constant : KEY_Arabic_dal
// constant : KEY_Arabic_damma
// constant : KEY_Arabic_dammatan
// constant : KEY_Arabic_ddal
// constant : KEY_Arabic_farsi_yeh
// constant : KEY_Arabic_fatha
// constant : KEY_Arabic_fathatan
// constant : KEY_Arabic_feh
// constant : KEY_Arabic_fullstop
// constant : KEY_Arabic_gaf
// constant : KEY_Arabic_ghain
// constant : KEY_Arabic_ha
// constant : KEY_Arabic_hah
// constant : KEY_Arabic_hamza
// constant : KEY_Arabic_hamza_above
// constant : KEY_Arabic_hamza_below
// constant : KEY_Arabic_hamzaonalef
// constant : KEY_Arabic_hamzaonwaw
// constant : KEY_Arabic_hamzaonyeh
// constant : KEY_Arabic_hamzaunderalef
// constant : KEY_Arabic_heh
// constant : KEY_Arabic_heh_doachashmee
// constant : KEY_Arabic_heh_goal
// constant : KEY_Arabic_jeem
// constant : KEY_Arabic_jeh
// constant : KEY_Arabic_kaf
// constant : KEY_Arabic_kasra
// constant : KEY_Arabic_kasratan
// constant : KEY_Arabic_keheh
// constant : KEY_Arabic_khah
// constant : KEY_Arabic_lam
// constant : KEY_Arabic_madda_above
// constant : KEY_Arabic_maddaonalef
// constant : KEY_Arabic_meem
// constant : KEY_Arabic_noon
// constant : KEY_Arabic_noon_ghunna
// constant : KEY_Arabic_peh
// constant : KEY_Arabic_percent
// constant : KEY_Arabic_qaf
// constant : KEY_Arabic_question_mark
// constant : KEY_Arabic_ra
// constant : KEY_Arabic_rreh
// constant : KEY_Arabic_sad
// constant : KEY_Arabic_seen
// constant : KEY_Arabic_semicolon
// constant : KEY_Arabic_shadda
// constant : KEY_Arabic_sheen
// constant : KEY_Arabic_sukun
// constant : KEY_Arabic_superscript_alef
// constant : KEY_Arabic_switch
// constant : KEY_Arabic_tah
// constant : KEY_Arabic_tatweel
// constant : KEY_Arabic_tcheh
// constant : KEY_Arabic_teh
// constant : KEY_Arabic_tehmarbuta
// constant : KEY_Arabic_thal
// constant : KEY_Arabic_theh
// constant : KEY_Arabic_tteh
// constant : KEY_Arabic_veh
// constant : KEY_Arabic_waw
// constant : KEY_Arabic_yeh
// constant : KEY_Arabic_yeh_baree
// constant : KEY_Arabic_zah
// constant : KEY_Arabic_zain
// constant : KEY_Aring
// constant : KEY_Armenian_AT
// constant : KEY_Armenian_AYB
// constant : KEY_Armenian_BEN
// constant : KEY_Armenian_CHA
// constant : KEY_Armenian_DA
// constant : KEY_Armenian_DZA
// constant : KEY_Armenian_E
// constant : KEY_Armenian_FE
// constant : KEY_Armenian_GHAT
// constant : KEY_Armenian_GIM
// constant : KEY_Armenian_HI
// constant : KEY_Armenian_HO
// constant : KEY_Armenian_INI
// constant : KEY_Armenian_JE
// constant : KEY_Armenian_KE
// constant : KEY_Armenian_KEN
// constant : KEY_Armenian_KHE
// constant : KEY_Armenian_LYUN
// constant : KEY_Armenian_MEN
// constant : KEY_Armenian_NU
// constant : KEY_Armenian_O
// constant : KEY_Armenian_PE
// constant : KEY_Armenian_PYUR
// constant : KEY_Armenian_RA
// constant : KEY_Armenian_RE
// constant : KEY_Armenian_SE
// constant : KEY_Armenian_SHA
// constant : KEY_Armenian_TCHE
// constant : KEY_Armenian_TO
// constant : KEY_Armenian_TSA
// constant : KEY_Armenian_TSO
// constant : KEY_Armenian_TYUN
// constant : KEY_Armenian_VEV
// constant : KEY_Armenian_VO
// constant : KEY_Armenian_VYUN
// constant : KEY_Armenian_YECH
// constant : KEY_Armenian_ZA
// constant : KEY_Armenian_ZHE
// constant : KEY_Armenian_accent
// constant : KEY_Armenian_amanak
// constant : KEY_Armenian_apostrophe
// constant : KEY_Armenian_at
// constant : KEY_Armenian_ayb
// constant : KEY_Armenian_ben
// constant : KEY_Armenian_but
// constant : KEY_Armenian_cha
// constant : KEY_Armenian_da
// constant : KEY_Armenian_dza
// constant : KEY_Armenian_e
// constant : KEY_Armenian_exclam
// constant : KEY_Armenian_fe
// constant : KEY_Armenian_full_stop
// constant : KEY_Armenian_ghat
// constant : KEY_Armenian_gim
// constant : KEY_Armenian_hi
// constant : KEY_Armenian_ho
// constant : KEY_Armenian_hyphen
// constant : KEY_Armenian_ini
// constant : KEY_Armenian_je
// constant : KEY_Armenian_ke
// constant : KEY_Armenian_ken
// constant : KEY_Armenian_khe
// constant : KEY_Armenian_ligature_ew
// constant : KEY_Armenian_lyun
// constant : KEY_Armenian_men
// constant : KEY_Armenian_nu
// constant : KEY_Armenian_o
// constant : KEY_Armenian_paruyk
// constant : KEY_Armenian_pe
// constant : KEY_Armenian_pyur
// constant : KEY_Armenian_question
// constant : KEY_Armenian_ra
// constant : KEY_Armenian_re
// constant : KEY_Armenian_se
// constant : KEY_Armenian_separation_mark
// constant : KEY_Armenian_sha
// constant : KEY_Armenian_shesht
// constant : KEY_Armenian_tche
// constant : KEY_Armenian_to
// constant : KEY_Armenian_tsa
// constant : KEY_Armenian_tso
// constant : KEY_Armenian_tyun
// constant : KEY_Armenian_verjaket
// constant : KEY_Armenian_vev
// constant : KEY_Armenian_vo
// constant : KEY_Armenian_vyun
// constant : KEY_Armenian_yech
// constant : KEY_Armenian_yentamna
// constant : KEY_Armenian_za
// constant : KEY_Armenian_zhe
// constant : KEY_Atilde
// constant : KEY_AudibleBell_Enable
// constant : KEY_AudioCycleTrack
// constant : KEY_AudioForward
// constant : KEY_AudioLowerVolume
// constant : KEY_AudioMedia
// constant : KEY_AudioMicMute
// constant : KEY_AudioMute
// constant : KEY_AudioNext
// constant : KEY_AudioPause
// constant : KEY_AudioPlay
// constant : KEY_AudioPrev
// constant : KEY_AudioRaiseVolume
// constant : KEY_AudioRandomPlay
// constant : KEY_AudioRecord
// constant : KEY_AudioRepeat
// constant : KEY_AudioRewind
// constant : KEY_AudioStop
// constant : KEY_Away
// constant : KEY_B
// constant : KEY_Babovedot
// constant : KEY_Back
// constant : KEY_BackForward
// constant : KEY_BackSpace
// constant : KEY_Battery
// constant : KEY_Begin
// constant : KEY_Blue
// constant : KEY_Bluetooth
// constant : KEY_Book
// constant : KEY_BounceKeys_Enable
// constant : KEY_Break
// constant : KEY_BrightnessAdjust
// constant : KEY_Byelorussian_SHORTU
// constant : KEY_Byelorussian_shortu
// constant : KEY_C
// constant : KEY_CD
// constant : KEY_CH
// constant : KEY_C_H
// constant : KEY_C_h
// constant : KEY_Cabovedot
// constant : KEY_Cacute
// constant : KEY_Calculator
// constant : KEY_Calendar
// constant : KEY_Cancel
// constant : KEY_Caps_Lock
// constant : KEY_Ccaron
// constant : KEY_Ccedilla
// constant : KEY_Ccircumflex
// constant : KEY_Ch
// constant : KEY_Clear
// constant : KEY_ClearGrab
// constant : KEY_Close
// constant : KEY_Codeinput
// constant : KEY_ColonSign
// constant : KEY_Community
// constant : KEY_ContrastAdjust
// constant : KEY_Control_L
// constant : KEY_Control_R
// constant : KEY_Copy
// constant : KEY_CruzeiroSign
// constant : KEY_Cut
// constant : KEY_CycleAngle
// constant : KEY_Cyrillic_A
// constant : KEY_Cyrillic_BE
// constant : KEY_Cyrillic_CHE
// constant : KEY_Cyrillic_CHE_descender
// constant : KEY_Cyrillic_CHE_vertstroke
// constant : KEY_Cyrillic_DE
// constant : KEY_Cyrillic_DZHE
// constant : KEY_Cyrillic_E
// constant : KEY_Cyrillic_EF
// constant : KEY_Cyrillic_EL
// constant : KEY_Cyrillic_EM
// constant : KEY_Cyrillic_EN
// constant : KEY_Cyrillic_EN_descender
// constant : KEY_Cyrillic_ER
// constant : KEY_Cyrillic_ES
// constant : KEY_Cyrillic_GHE
// constant : KEY_Cyrillic_GHE_bar
// constant : KEY_Cyrillic_HA
// constant : KEY_Cyrillic_HARDSIGN
// constant : KEY_Cyrillic_HA_descender
// constant : KEY_Cyrillic_I
// constant : KEY_Cyrillic_IE
// constant : KEY_Cyrillic_IO
// constant : KEY_Cyrillic_I_macron
// constant : KEY_Cyrillic_JE
// constant : KEY_Cyrillic_KA
// constant : KEY_Cyrillic_KA_descender
// constant : KEY_Cyrillic_KA_vertstroke
// constant : KEY_Cyrillic_LJE
// constant : KEY_Cyrillic_NJE
// constant : KEY_Cyrillic_O
// constant : KEY_Cyrillic_O_bar
// constant : KEY_Cyrillic_PE
// constant : KEY_Cyrillic_SCHWA
// constant : KEY_Cyrillic_SHA
// constant : KEY_Cyrillic_SHCHA
// constant : KEY_Cyrillic_SHHA
// constant : KEY_Cyrillic_SHORTI
// constant : KEY_Cyrillic_SOFTSIGN
// constant : KEY_Cyrillic_TE
// constant : KEY_Cyrillic_TSE
// constant : KEY_Cyrillic_U
// constant : KEY_Cyrillic_U_macron
// constant : KEY_Cyrillic_U_straight
// constant : KEY_Cyrillic_U_straight_bar
// constant : KEY_Cyrillic_VE
// constant : KEY_Cyrillic_YA
// constant : KEY_Cyrillic_YERU
// constant : KEY_Cyrillic_YU
// constant : KEY_Cyrillic_ZE
// constant : KEY_Cyrillic_ZHE
// constant : KEY_Cyrillic_ZHE_descender
// constant : KEY_Cyrillic_a
// constant : KEY_Cyrillic_be
// constant : KEY_Cyrillic_che
// constant : KEY_Cyrillic_che_descender
// constant : KEY_Cyrillic_che_vertstroke
// constant : KEY_Cyrillic_de
// constant : KEY_Cyrillic_dzhe
// constant : KEY_Cyrillic_e
// constant : KEY_Cyrillic_ef
// constant : KEY_Cyrillic_el
// constant : KEY_Cyrillic_em
// constant : KEY_Cyrillic_en
// constant : KEY_Cyrillic_en_descender
// constant : KEY_Cyrillic_er
// constant : KEY_Cyrillic_es
// constant : KEY_Cyrillic_ghe
// constant : KEY_Cyrillic_ghe_bar
// constant : KEY_Cyrillic_ha
// constant : KEY_Cyrillic_ha_descender
// constant : KEY_Cyrillic_hardsign
// constant : KEY_Cyrillic_i
// constant : KEY_Cyrillic_i_macron
// constant : KEY_Cyrillic_ie
// constant : KEY_Cyrillic_io
// constant : KEY_Cyrillic_je
// constant : KEY_Cyrillic_ka
// constant : KEY_Cyrillic_ka_descender
// constant : KEY_Cyrillic_ka_vertstroke
// constant : KEY_Cyrillic_lje
// constant : KEY_Cyrillic_nje
// constant : KEY_Cyrillic_o
// constant : KEY_Cyrillic_o_bar
// constant : KEY_Cyrillic_pe
// constant : KEY_Cyrillic_schwa
// constant : KEY_Cyrillic_sha
// constant : KEY_Cyrillic_shcha
// constant : KEY_Cyrillic_shha
// constant : KEY_Cyrillic_shorti
// constant : KEY_Cyrillic_softsign
// constant : KEY_Cyrillic_te
// constant : KEY_Cyrillic_tse
// constant : KEY_Cyrillic_u
// constant : KEY_Cyrillic_u_macron
// constant : KEY_Cyrillic_u_straight
// constant : KEY_Cyrillic_u_straight_bar
// constant : KEY_Cyrillic_ve
// constant : KEY_Cyrillic_ya
// constant : KEY_Cyrillic_yeru
// constant : KEY_Cyrillic_yu
// constant : KEY_Cyrillic_ze
// constant : KEY_Cyrillic_zhe
// constant : KEY_Cyrillic_zhe_descender
// constant : KEY_D
// constant : KEY_DOS
// constant : KEY_Dabovedot
// constant : KEY_Dcaron
// constant : KEY_Delete
// constant : KEY_Display
// constant : KEY_Documents
// constant : KEY_DongSign
// constant : KEY_Down
// constant : KEY_Dstroke
// constant : KEY_E
// constant : KEY_ENG
// constant : KEY_ETH
// constant : KEY_EZH
// constant : KEY_Eabovedot
// constant : KEY_Eacute
// constant : KEY_Ebelowdot
// constant : KEY_Ecaron
// constant : KEY_Ecircumflex
// constant : KEY_Ecircumflexacute
// constant : KEY_Ecircumflexbelowdot
// constant : KEY_Ecircumflexgrave
// constant : KEY_Ecircumflexhook
// constant : KEY_Ecircumflextilde
// constant : KEY_EcuSign
// constant : KEY_Ediaeresis
// constant : KEY_Egrave
// constant : KEY_Ehook
// constant : KEY_Eisu_Shift
// constant : KEY_Eisu_toggle
// constant : KEY_Eject
// constant : KEY_Emacron
// constant : KEY_End
// constant : KEY_Eogonek
// constant : KEY_Escape
// constant : KEY_Eth
// constant : KEY_Etilde
// constant : KEY_EuroSign
// constant : KEY_Excel
// constant : KEY_Execute
// constant : KEY_Explorer
// constant : KEY_F
// constant : KEY_F1
// constant : KEY_F10
// constant : KEY_F11
// constant : KEY_F12
// constant : KEY_F13
// constant : KEY_F14
// constant : KEY_F15
// constant : KEY_F16
// constant : KEY_F17
// constant : KEY_F18
// constant : KEY_F19
// constant : KEY_F2
// constant : KEY_F20
// constant : KEY_F21
// constant : KEY_F22
// constant : KEY_F23
// constant : KEY_F24
// constant : KEY_F25
// constant : KEY_F26
// constant : KEY_F27
// constant : KEY_F28
// constant : KEY_F29
// constant : KEY_F3
// constant : KEY_F30
// constant : KEY_F31
// constant : KEY_F32
// constant : KEY_F33
// constant : KEY_F34
// constant : KEY_F35
// constant : KEY_F4
// constant : KEY_F5
// constant : KEY_F6
// constant : KEY_F7
// constant : KEY_F8
// constant : KEY_F9
// constant : KEY_FFrancSign
// constant : KEY_Fabovedot
// constant : KEY_Farsi_0
// constant : KEY_Farsi_1
// constant : KEY_Farsi_2
// constant : KEY_Farsi_3
// constant : KEY_Farsi_4
// constant : KEY_Farsi_5
// constant : KEY_Farsi_6
// constant : KEY_Farsi_7
// constant : KEY_Farsi_8
// constant : KEY_Farsi_9
// constant : KEY_Farsi_yeh
// constant : KEY_Favorites
// constant : KEY_Finance
// constant : KEY_Find
// constant : KEY_First_Virtual_Screen
// constant : KEY_Forward
// constant : KEY_FrameBack
// constant : KEY_FrameForward
// constant : KEY_G
// constant : KEY_Gabovedot
// constant : KEY_Game
// constant : KEY_Gbreve
// constant : KEY_Gcaron
// constant : KEY_Gcedilla
// constant : KEY_Gcircumflex
// constant : KEY_Georgian_an
// constant : KEY_Georgian_ban
// constant : KEY_Georgian_can
// constant : KEY_Georgian_char
// constant : KEY_Georgian_chin
// constant : KEY_Georgian_cil
// constant : KEY_Georgian_don
// constant : KEY_Georgian_en
// constant : KEY_Georgian_fi
// constant : KEY_Georgian_gan
// constant : KEY_Georgian_ghan
// constant : KEY_Georgian_hae
// constant : KEY_Georgian_har
// constant : KEY_Georgian_he
// constant : KEY_Georgian_hie
// constant : KEY_Georgian_hoe
// constant : KEY_Georgian_in
// constant : KEY_Georgian_jhan
// constant : KEY_Georgian_jil
// constant : KEY_Georgian_kan
// constant : KEY_Georgian_khar
// constant : KEY_Georgian_las
// constant : KEY_Georgian_man
// constant : KEY_Georgian_nar
// constant : KEY_Georgian_on
// constant : KEY_Georgian_par
// constant : KEY_Georgian_phar
// constant : KEY_Georgian_qar
// constant : KEY_Georgian_rae
// constant : KEY_Georgian_san
// constant : KEY_Georgian_shin
// constant : KEY_Georgian_tan
// constant : KEY_Georgian_tar
// constant : KEY_Georgian_un
// constant : KEY_Georgian_vin
// constant : KEY_Georgian_we
// constant : KEY_Georgian_xan
// constant : KEY_Georgian_zen
// constant : KEY_Georgian_zhar
// constant : KEY_Go
// constant : KEY_Greek_ALPHA
// constant : KEY_Greek_ALPHAaccent
// constant : KEY_Greek_BETA
// constant : KEY_Greek_CHI
// constant : KEY_Greek_DELTA
// constant : KEY_Greek_EPSILON
// constant : KEY_Greek_EPSILONaccent
// constant : KEY_Greek_ETA
// constant : KEY_Greek_ETAaccent
// constant : KEY_Greek_GAMMA
// constant : KEY_Greek_IOTA
// constant : KEY_Greek_IOTAaccent
// constant : KEY_Greek_IOTAdiaeresis
// constant : KEY_Greek_IOTAdieresis
// constant : KEY_Greek_KAPPA
// constant : KEY_Greek_LAMBDA
// constant : KEY_Greek_LAMDA
// constant : KEY_Greek_MU
// constant : KEY_Greek_NU
// constant : KEY_Greek_OMEGA
// constant : KEY_Greek_OMEGAaccent
// constant : KEY_Greek_OMICRON
// constant : KEY_Greek_OMICRONaccent
// constant : KEY_Greek_PHI
// constant : KEY_Greek_PI
// constant : KEY_Greek_PSI
// constant : KEY_Greek_RHO
// constant : KEY_Greek_SIGMA
// constant : KEY_Greek_TAU
// constant : KEY_Greek_THETA
// constant : KEY_Greek_UPSILON
// constant : KEY_Greek_UPSILONaccent
// constant : KEY_Greek_UPSILONdieresis
// constant : KEY_Greek_XI
// constant : KEY_Greek_ZETA
// constant : KEY_Greek_accentdieresis
// constant : KEY_Greek_alpha
// constant : KEY_Greek_alphaaccent
// constant : KEY_Greek_beta
// constant : KEY_Greek_chi
// constant : KEY_Greek_delta
// constant : KEY_Greek_epsilon
// constant : KEY_Greek_epsilonaccent
// constant : KEY_Greek_eta
// constant : KEY_Greek_etaaccent
// constant : KEY_Greek_finalsmallsigma
// constant : KEY_Greek_gamma
// constant : KEY_Greek_horizbar
// constant : KEY_Greek_iota
// constant : KEY_Greek_iotaaccent
// constant : KEY_Greek_iotaaccentdieresis
// constant : KEY_Greek_iotadieresis
// constant : KEY_Greek_kappa
// constant : KEY_Greek_lambda
// constant : KEY_Greek_lamda
// constant : KEY_Greek_mu
// constant : KEY_Greek_nu
// constant : KEY_Greek_omega
// constant : KEY_Greek_omegaaccent
// constant : KEY_Greek_omicron
// constant : KEY_Greek_omicronaccent
// constant : KEY_Greek_phi
// constant : KEY_Greek_pi
// constant : KEY_Greek_psi
// constant : KEY_Greek_rho
// constant : KEY_Greek_sigma
// constant : KEY_Greek_switch
// constant : KEY_Greek_tau
// constant : KEY_Greek_theta
// constant : KEY_Greek_upsilon
// constant : KEY_Greek_upsilonaccent
// constant : KEY_Greek_upsilonaccentdieresis
// constant : KEY_Greek_upsilondieresis
// constant : KEY_Greek_xi
// constant : KEY_Greek_zeta
// constant : KEY_Green
// constant : KEY_H
// constant : KEY_Hangul
// constant : KEY_Hangul_A
// constant : KEY_Hangul_AE
// constant : KEY_Hangul_AraeA
// constant : KEY_Hangul_AraeAE
// constant : KEY_Hangul_Banja
// constant : KEY_Hangul_Cieuc
// constant : KEY_Hangul_Codeinput
// constant : KEY_Hangul_Dikeud
// constant : KEY_Hangul_E
// constant : KEY_Hangul_EO
// constant : KEY_Hangul_EU
// constant : KEY_Hangul_End
// constant : KEY_Hangul_Hanja
// constant : KEY_Hangul_Hieuh
// constant : KEY_Hangul_I
// constant : KEY_Hangul_Ieung
// constant : KEY_Hangul_J_Cieuc
// constant : KEY_Hangul_J_Dikeud
// constant : KEY_Hangul_J_Hieuh
// constant : KEY_Hangul_J_Ieung
// constant : KEY_Hangul_J_Jieuj
// constant : KEY_Hangul_J_Khieuq
// constant : KEY_Hangul_J_Kiyeog
// constant : KEY_Hangul_J_KiyeogSios
// constant : KEY_Hangul_J_KkogjiDalrinIeung
// constant : KEY_Hangul_J_Mieum
// constant : KEY_Hangul_J_Nieun
// constant : KEY_Hangul_J_NieunHieuh
// constant : KEY_Hangul_J_NieunJieuj
// constant : KEY_Hangul_J_PanSios
// constant : KEY_Hangul_J_Phieuf
// constant : KEY_Hangul_J_Pieub
// constant : KEY_Hangul_J_PieubSios
// constant : KEY_Hangul_J_Rieul
// constant : KEY_Hangul_J_RieulHieuh
// constant : KEY_Hangul_J_RieulKiyeog
// constant : KEY_Hangul_J_RieulMieum
// constant : KEY_Hangul_J_RieulPhieuf
// constant : KEY_Hangul_J_RieulPieub
// constant : KEY_Hangul_J_RieulSios
// constant : KEY_Hangul_J_RieulTieut
// constant : KEY_Hangul_J_Sios
// constant : KEY_Hangul_J_SsangKiyeog
// constant : KEY_Hangul_J_SsangSios
// constant : KEY_Hangul_J_Tieut
// constant : KEY_Hangul_J_YeorinHieuh
// constant : KEY_Hangul_Jamo
// constant : KEY_Hangul_Jeonja
// constant : KEY_Hangul_Jieuj
// constant : KEY_Hangul_Khieuq
// constant : KEY_Hangul_Kiyeog
// constant : KEY_Hangul_KiyeogSios
// constant : KEY_Hangul_KkogjiDalrinIeung
// constant : KEY_Hangul_Mieum
// constant : KEY_Hangul_MultipleCandidate
// constant : KEY_Hangul_Nieun
// constant : KEY_Hangul_NieunHieuh
// constant : KEY_Hangul_NieunJieuj
// constant : KEY_Hangul_O
// constant : KEY_Hangul_OE
// constant : KEY_Hangul_PanSios
// constant : KEY_Hangul_Phieuf
// constant : KEY_Hangul_Pieub
// constant : KEY_Hangul_PieubSios
// constant : KEY_Hangul_PostHanja
// constant : KEY_Hangul_PreHanja
// constant : KEY_Hangul_PreviousCandidate
// constant : KEY_Hangul_Rieul
// constant : KEY_Hangul_RieulHieuh
// constant : KEY_Hangul_RieulKiyeog
// constant : KEY_Hangul_RieulMieum
// constant : KEY_Hangul_RieulPhieuf
// constant : KEY_Hangul_RieulPieub
// constant : KEY_Hangul_RieulSios
// constant : KEY_Hangul_RieulTieut
// constant : KEY_Hangul_RieulYeorinHieuh
// constant : KEY_Hangul_Romaja
// constant : KEY_Hangul_SingleCandidate
// constant : KEY_Hangul_Sios
// constant : KEY_Hangul_Special
// constant : KEY_Hangul_SsangDikeud
// constant : KEY_Hangul_SsangJieuj
// constant : KEY_Hangul_SsangKiyeog
// constant : KEY_Hangul_SsangPieub
// constant : KEY_Hangul_SsangSios
// constant : KEY_Hangul_Start
// constant : KEY_Hangul_SunkyeongeumMieum
// constant : KEY_Hangul_SunkyeongeumPhieuf
// constant : KEY_Hangul_SunkyeongeumPieub
// constant : KEY_Hangul_Tieut
// constant : KEY_Hangul_U
// constant : KEY_Hangul_WA
// constant : KEY_Hangul_WAE
// constant : KEY_Hangul_WE
// constant : KEY_Hangul_WEO
// constant : KEY_Hangul_WI
// constant : KEY_Hangul_YA
// constant : KEY_Hangul_YAE
// constant : KEY_Hangul_YE
// constant : KEY_Hangul_YEO
// constant : KEY_Hangul_YI
// constant : KEY_Hangul_YO
// constant : KEY_Hangul_YU
// constant : KEY_Hangul_YeorinHieuh
// constant : KEY_Hangul_switch
// constant : KEY_Hankaku
// constant : KEY_Hcircumflex
// constant : KEY_Hebrew_switch
// constant : KEY_Help
// constant : KEY_Henkan
// constant : KEY_Henkan_Mode
// constant : KEY_Hibernate
// constant : KEY_Hiragana
// constant : KEY_Hiragana_Katakana
// constant : KEY_History
// constant : KEY_Home
// constant : KEY_HomePage
// constant : KEY_HotLinks
// constant : KEY_Hstroke
// constant : KEY_Hyper_L
// constant : KEY_Hyper_R
// constant : KEY_I
// constant : KEY_ISO_Center_Object
// constant : KEY_ISO_Continuous_Underline
// constant : KEY_ISO_Discontinuous_Underline
// constant : KEY_ISO_Emphasize
// constant : KEY_ISO_Enter
// constant : KEY_ISO_Fast_Cursor_Down
// constant : KEY_ISO_Fast_Cursor_Left
// constant : KEY_ISO_Fast_Cursor_Right
// constant : KEY_ISO_Fast_Cursor_Up
// constant : KEY_ISO_First_Group
// constant : KEY_ISO_First_Group_Lock
// constant : KEY_ISO_Group_Latch
// constant : KEY_ISO_Group_Lock
// constant : KEY_ISO_Group_Shift
// constant : KEY_ISO_Last_Group
// constant : KEY_ISO_Last_Group_Lock
// constant : KEY_ISO_Left_Tab
// constant : KEY_ISO_Level2_Latch
// constant : KEY_ISO_Level3_Latch
// constant : KEY_ISO_Level3_Lock
// constant : KEY_ISO_Level3_Shift
// constant : KEY_ISO_Level5_Latch
// constant : KEY_ISO_Level5_Lock
// constant : KEY_ISO_Level5_Shift
// constant : KEY_ISO_Lock
// constant : KEY_ISO_Move_Line_Down
// constant : KEY_ISO_Move_Line_Up
// constant : KEY_ISO_Next_Group
// constant : KEY_ISO_Next_Group_Lock
// constant : KEY_ISO_Partial_Line_Down
// constant : KEY_ISO_Partial_Line_Up
// constant : KEY_ISO_Partial_Space_Left
// constant : KEY_ISO_Partial_Space_Right
// constant : KEY_ISO_Prev_Group
// constant : KEY_ISO_Prev_Group_Lock
// constant : KEY_ISO_Release_Both_Margins
// constant : KEY_ISO_Release_Margin_Left
// constant : KEY_ISO_Release_Margin_Right
// constant : KEY_ISO_Set_Margin_Left
// constant : KEY_ISO_Set_Margin_Right
// constant : KEY_Iabovedot
// constant : KEY_Iacute
// constant : KEY_Ibelowdot
// constant : KEY_Ibreve
// constant : KEY_Icircumflex
// constant : KEY_Idiaeresis
// constant : KEY_Igrave
// constant : KEY_Ihook
// constant : KEY_Imacron
// constant : KEY_Insert
// constant : KEY_Iogonek
// constant : KEY_Itilde
// constant : KEY_J
// constant : KEY_Jcircumflex
// constant : KEY_K
// constant : KEY_KP_0
// constant : KEY_KP_1
// constant : KEY_KP_2
// constant : KEY_KP_3
// constant : KEY_KP_4
// constant : KEY_KP_5
// constant : KEY_KP_6
// constant : KEY_KP_7
// constant : KEY_KP_8
// constant : KEY_KP_9
// constant : KEY_KP_Add
// constant : KEY_KP_Begin
// constant : KEY_KP_Decimal
// constant : KEY_KP_Delete
// constant : KEY_KP_Divide
// constant : KEY_KP_Down
// constant : KEY_KP_End
// constant : KEY_KP_Enter
// constant : KEY_KP_Equal
// constant : KEY_KP_F1
// constant : KEY_KP_F2
// constant : KEY_KP_F3
// constant : KEY_KP_F4
// constant : KEY_KP_Home
// constant : KEY_KP_Insert
// constant : KEY_KP_Left
// constant : KEY_KP_Multiply
// constant : KEY_KP_Next
// constant : KEY_KP_Page_Down
// constant : KEY_KP_Page_Up
// constant : KEY_KP_Prior
// constant : KEY_KP_Right
// constant : KEY_KP_Separator
// constant : KEY_KP_Space
// constant : KEY_KP_Subtract
// constant : KEY_KP_Tab
// constant : KEY_KP_Up
// constant : KEY_Kana_Lock
// constant : KEY_Kana_Shift
// constant : KEY_Kanji
// constant : KEY_Kanji_Bangou
// constant : KEY_Katakana
// constant : KEY_KbdBrightnessDown
// constant : KEY_KbdBrightnessUp
// constant : KEY_KbdLightOnOff
// constant : KEY_Kcedilla
// constant : KEY_Korean_Won
// constant : KEY_L
// constant : KEY_L1
// constant : KEY_L10
// constant : KEY_L2
// constant : KEY_L3
// constant : KEY_L4
// constant : KEY_L5
// constant : KEY_L6
// constant : KEY_L7
// constant : KEY_L8
// constant : KEY_L9
// constant : KEY_Lacute
// constant : KEY_Last_Virtual_Screen
// constant : KEY_Launch0
// constant : KEY_Launch1
// constant : KEY_Launch2
// constant : KEY_Launch3
// constant : KEY_Launch4
// constant : KEY_Launch5
// constant : KEY_Launch6
// constant : KEY_Launch7
// constant : KEY_Launch8
// constant : KEY_Launch9
// constant : KEY_LaunchA
// constant : KEY_LaunchB
// constant : KEY_LaunchC
// constant : KEY_LaunchD
// constant : KEY_LaunchE
// constant : KEY_LaunchF
// constant : KEY_Lbelowdot
// constant : KEY_Lcaron
// constant : KEY_Lcedilla
// constant : KEY_Left
// constant : KEY_LightBulb
// constant : KEY_Linefeed
// constant : KEY_LiraSign
// constant : KEY_LogGrabInfo
// constant : KEY_LogOff
// constant : KEY_LogWindowTree
// constant : KEY_Lstroke
// constant : KEY_M
// constant : KEY_Mabovedot
// constant : KEY_Macedonia_DSE
// constant : KEY_Macedonia_GJE
// constant : KEY_Macedonia_KJE
// constant : KEY_Macedonia_dse
// constant : KEY_Macedonia_gje
// constant : KEY_Macedonia_kje
// constant : KEY_Mae_Koho
// constant : KEY_Mail
// constant : KEY_MailForward
// constant : KEY_Market
// constant : KEY_Massyo
// constant : KEY_Meeting
// constant : KEY_Memo
// constant : KEY_Menu
// constant : KEY_MenuKB
// constant : KEY_MenuPB
// constant : KEY_Messenger
// constant : KEY_Meta_L
// constant : KEY_Meta_R
// constant : KEY_MillSign
// constant : KEY_ModeLock
// constant : KEY_Mode_switch
// constant : KEY_MonBrightnessDown
// constant : KEY_MonBrightnessUp
// constant : KEY_MouseKeys_Accel_Enable
// constant : KEY_MouseKeys_Enable
// constant : KEY_Muhenkan
// constant : KEY_Multi_key
// constant : KEY_MultipleCandidate
// constant : KEY_Music
// constant : KEY_MyComputer
// constant : KEY_MySites
// constant : KEY_N
// constant : KEY_Nacute
// constant : KEY_NairaSign
// constant : KEY_Ncaron
// constant : KEY_Ncedilla
// constant : KEY_New
// constant : KEY_NewSheqelSign
// constant : KEY_News
// constant : KEY_Next
// constant : KEY_Next_VMode
// constant : KEY_Next_Virtual_Screen
// constant : KEY_Ntilde
// constant : KEY_Num_Lock
// constant : KEY_O
// constant : KEY_OE
// constant : KEY_Oacute
// constant : KEY_Obarred
// constant : KEY_Obelowdot
// constant : KEY_Ocaron
// constant : KEY_Ocircumflex
// constant : KEY_Ocircumflexacute
// constant : KEY_Ocircumflexbelowdot
// constant : KEY_Ocircumflexgrave
// constant : KEY_Ocircumflexhook
// constant : KEY_Ocircumflextilde
// constant : KEY_Odiaeresis
// constant : KEY_Odoubleacute
// constant : KEY_OfficeHome
// constant : KEY_Ograve
// constant : KEY_Ohook
// constant : KEY_Ohorn
// constant : KEY_Ohornacute
// constant : KEY_Ohornbelowdot
// constant : KEY_Ohorngrave
// constant : KEY_Ohornhook
// constant : KEY_Ohorntilde
// constant : KEY_Omacron
// constant : KEY_Ooblique
// constant : KEY_Open
// constant : KEY_OpenURL
// constant : KEY_Option
// constant : KEY_Oslash
// constant : KEY_Otilde
// constant : KEY_Overlay1_Enable
// constant : KEY_Overlay2_Enable
// constant : KEY_P
// constant : KEY_Pabovedot
// constant : KEY_Page_Down
// constant : KEY_Page_Up
// constant : KEY_Paste
// constant : KEY_Pause
// constant : KEY_PesetaSign
// constant : KEY_Phone
// constant : KEY_Pictures
// constant : KEY_Pointer_Accelerate
// constant : KEY_Pointer_Button1
// constant : KEY_Pointer_Button2
// constant : KEY_Pointer_Button3
// constant : KEY_Pointer_Button4
// constant : KEY_Pointer_Button5
// constant : KEY_Pointer_Button_Dflt
// constant : KEY_Pointer_DblClick1
// constant : KEY_Pointer_DblClick2
// constant : KEY_Pointer_DblClick3
// constant : KEY_Pointer_DblClick4
// constant : KEY_Pointer_DblClick5
// constant : KEY_Pointer_DblClick_Dflt
// constant : KEY_Pointer_DfltBtnNext
// constant : KEY_Pointer_DfltBtnPrev
// constant : KEY_Pointer_Down
// constant : KEY_Pointer_DownLeft
// constant : KEY_Pointer_DownRight
// constant : KEY_Pointer_Drag1
// constant : KEY_Pointer_Drag2
// constant : KEY_Pointer_Drag3
// constant : KEY_Pointer_Drag4
// constant : KEY_Pointer_Drag5
// constant : KEY_Pointer_Drag_Dflt
// constant : KEY_Pointer_EnableKeys
// constant : KEY_Pointer_Left
// constant : KEY_Pointer_Right
// constant : KEY_Pointer_Up
// constant : KEY_Pointer_UpLeft
// constant : KEY_Pointer_UpRight
// constant : KEY_PowerDown
// constant : KEY_PowerOff
// constant : KEY_Prev_VMode
// constant : KEY_Prev_Virtual_Screen
// constant : KEY_PreviousCandidate
// constant : KEY_Print
// constant : KEY_Prior
// constant : KEY_Q
// constant : KEY_R
// constant : KEY_R1
// constant : KEY_R10
// constant : KEY_R11
// constant : KEY_R12
// constant : KEY_R13
// constant : KEY_R14
// constant : KEY_R15
// constant : KEY_R2
// constant : KEY_R3
// constant : KEY_R4
// constant : KEY_R5
// constant : KEY_R6
// constant : KEY_R7
// constant : KEY_R8
// constant : KEY_R9
// constant : KEY_Racute
// constant : KEY_Rcaron
// constant : KEY_Rcedilla
// constant : KEY_Red
// constant : KEY_Redo
// constant : KEY_Refresh
// constant : KEY_Reload
// constant : KEY_RepeatKeys_Enable
// constant : KEY_Reply
// constant : KEY_Return
// constant : KEY_Right
// constant : KEY_RockerDown
// constant : KEY_RockerEnter
// constant : KEY_RockerUp
// constant : KEY_Romaji
// constant : KEY_RotateWindows
// constant : KEY_RotationKB
// constant : KEY_RotationPB
// constant : KEY_RupeeSign
// constant : KEY_S
// constant : KEY_SCHWA
// constant : KEY_Sabovedot
// constant : KEY_Sacute
// constant : KEY_Save
// constant : KEY_Scaron
// constant : KEY_Scedilla
// constant : KEY_Scircumflex
// constant : KEY_ScreenSaver
// constant : KEY_ScrollClick
// constant : KEY_ScrollDown
// constant : KEY_ScrollUp
// constant : KEY_Scroll_Lock
// constant : KEY_Search
// constant : KEY_Select
// constant : KEY_SelectButton
// constant : KEY_Send
// constant : KEY_Serbian_DJE
// constant : KEY_Serbian_DZE
// constant : KEY_Serbian_JE
// constant : KEY_Serbian_LJE
// constant : KEY_Serbian_NJE
// constant : KEY_Serbian_TSHE
// constant : KEY_Serbian_dje
// constant : KEY_Serbian_dze
// constant : KEY_Serbian_je
// constant : KEY_Serbian_lje
// constant : KEY_Serbian_nje
// constant : KEY_Serbian_tshe
// constant : KEY_Shift_L
// constant : KEY_Shift_Lock
// constant : KEY_Shift_R
// constant : KEY_Shop
// constant : KEY_SingleCandidate
// constant : KEY_Sinh_a
// constant : KEY_Sinh_aa
// constant : KEY_Sinh_aa2
// constant : KEY_Sinh_ae
// constant : KEY_Sinh_ae2
// constant : KEY_Sinh_aee
// constant : KEY_Sinh_aee2
// constant : KEY_Sinh_ai
// constant : KEY_Sinh_ai2
// constant : KEY_Sinh_al
// constant : KEY_Sinh_au
// constant : KEY_Sinh_au2
// constant : KEY_Sinh_ba
// constant : KEY_Sinh_bha
// constant : KEY_Sinh_ca
// constant : KEY_Sinh_cha
// constant : KEY_Sinh_dda
// constant : KEY_Sinh_ddha
// constant : KEY_Sinh_dha
// constant : KEY_Sinh_dhha
// constant : KEY_Sinh_e
// constant : KEY_Sinh_e2
// constant : KEY_Sinh_ee
// constant : KEY_Sinh_ee2
// constant : KEY_Sinh_fa
// constant : KEY_Sinh_ga
// constant : KEY_Sinh_gha
// constant : KEY_Sinh_h2
// constant : KEY_Sinh_ha
// constant : KEY_Sinh_i
// constant : KEY_Sinh_i2
// constant : KEY_Sinh_ii
// constant : KEY_Sinh_ii2
// constant : KEY_Sinh_ja
// constant : KEY_Sinh_jha
// constant : KEY_Sinh_jnya
// constant : KEY_Sinh_ka
// constant : KEY_Sinh_kha
// constant : KEY_Sinh_kunddaliya
// constant : KEY_Sinh_la
// constant : KEY_Sinh_lla
// constant : KEY_Sinh_lu
// constant : KEY_Sinh_lu2
// constant : KEY_Sinh_luu
// constant : KEY_Sinh_luu2
// constant : KEY_Sinh_ma
// constant : KEY_Sinh_mba
// constant : KEY_Sinh_na
// constant : KEY_Sinh_ndda
// constant : KEY_Sinh_ndha
// constant : KEY_Sinh_ng
// constant : KEY_Sinh_ng2
// constant : KEY_Sinh_nga
// constant : KEY_Sinh_nja
// constant : KEY_Sinh_nna
// constant : KEY_Sinh_nya
// constant : KEY_Sinh_o
// constant : KEY_Sinh_o2
// constant : KEY_Sinh_oo
// constant : KEY_Sinh_oo2
// constant : KEY_Sinh_pa
// constant : KEY_Sinh_pha
// constant : KEY_Sinh_ra
// constant : KEY_Sinh_ri
// constant : KEY_Sinh_rii
// constant : KEY_Sinh_ru2
// constant : KEY_Sinh_ruu2
// constant : KEY_Sinh_sa
// constant : KEY_Sinh_sha
// constant : KEY_Sinh_ssha
// constant : KEY_Sinh_tha
// constant : KEY_Sinh_thha
// constant : KEY_Sinh_tta
// constant : KEY_Sinh_ttha
// constant : KEY_Sinh_u
// constant : KEY_Sinh_u2
// constant : KEY_Sinh_uu
// constant : KEY_Sinh_uu2
// constant : KEY_Sinh_va
// constant : KEY_Sinh_ya
// constant : KEY_Sleep
// constant : KEY_SlowKeys_Enable
// constant : KEY_Spell
// constant : KEY_SplitScreen
// constant : KEY_Standby
// constant : KEY_Start
// constant : KEY_StickyKeys_Enable
// constant : KEY_Stop
// constant : KEY_Subtitle
// constant : KEY_Super_L
// constant : KEY_Super_R
// constant : KEY_Support
// constant : KEY_Suspend
// constant : KEY_Switch_VT_1
// constant : KEY_Switch_VT_10
// constant : KEY_Switch_VT_11
// constant : KEY_Switch_VT_12
// constant : KEY_Switch_VT_2
// constant : KEY_Switch_VT_3
// constant : KEY_Switch_VT_4
// constant : KEY_Switch_VT_5
// constant : KEY_Switch_VT_6
// constant : KEY_Switch_VT_7
// constant : KEY_Switch_VT_8
// constant : KEY_Switch_VT_9
// constant : KEY_Sys_Req
// constant : KEY_T
// constant : KEY_THORN
// constant : KEY_Tab
// constant : KEY_Tabovedot
// constant : KEY_TaskPane
// constant : KEY_Tcaron
// constant : KEY_Tcedilla
// constant : KEY_Terminal
// constant : KEY_Terminate_Server
// constant : KEY_Thai_baht
// constant : KEY_Thai_bobaimai
// constant : KEY_Thai_chochan
// constant : KEY_Thai_chochang
// constant : KEY_Thai_choching
// constant : KEY_Thai_chochoe
// constant : KEY_Thai_dochada
// constant : KEY_Thai_dodek
// constant : KEY_Thai_fofa
// constant : KEY_Thai_fofan
// constant : KEY_Thai_hohip
// constant : KEY_Thai_honokhuk
// constant : KEY_Thai_khokhai
// constant : KEY_Thai_khokhon
// constant : KEY_Thai_khokhuat
// constant : KEY_Thai_khokhwai
// constant : KEY_Thai_khorakhang
// constant : KEY_Thai_kokai
// constant : KEY_Thai_lakkhangyao
// constant : KEY_Thai_lekchet
// constant : KEY_Thai_lekha
// constant : KEY_Thai_lekhok
// constant : KEY_Thai_lekkao
// constant : KEY_Thai_leknung
// constant : KEY_Thai_lekpaet
// constant : KEY_Thai_leksam
// constant : KEY_Thai_leksi
// constant : KEY_Thai_leksong
// constant : KEY_Thai_leksun
// constant : KEY_Thai_lochula
// constant : KEY_Thai_loling
// constant : KEY_Thai_lu
// constant : KEY_Thai_maichattawa
// constant : KEY_Thai_maiek
// constant : KEY_Thai_maihanakat
// constant : KEY_Thai_maihanakat_maitho
// constant : KEY_Thai_maitaikhu
// constant : KEY_Thai_maitho
// constant : KEY_Thai_maitri
// constant : KEY_Thai_maiyamok
// constant : KEY_Thai_moma
// constant : KEY_Thai_ngongu
// constant : KEY_Thai_nikhahit
// constant : KEY_Thai_nonen
// constant : KEY_Thai_nonu
// constant : KEY_Thai_oang
// constant : KEY_Thai_paiyannoi
// constant : KEY_Thai_phinthu
// constant : KEY_Thai_phophan
// constant : KEY_Thai_phophung
// constant : KEY_Thai_phosamphao
// constant : KEY_Thai_popla
// constant : KEY_Thai_rorua
// constant : KEY_Thai_ru
// constant : KEY_Thai_saraa
// constant : KEY_Thai_saraaa
// constant : KEY_Thai_saraae
// constant : KEY_Thai_saraaimaimalai
// constant : KEY_Thai_saraaimaimuan
// constant : KEY_Thai_saraam
// constant : KEY_Thai_sarae
// constant : KEY_Thai_sarai
// constant : KEY_Thai_saraii
// constant : KEY_Thai_sarao
// constant : KEY_Thai_sarau
// constant : KEY_Thai_saraue
// constant : KEY_Thai_sarauee
// constant : KEY_Thai_sarauu
// constant : KEY_Thai_sorusi
// constant : KEY_Thai_sosala
// constant : KEY_Thai_soso
// constant : KEY_Thai_sosua
// constant : KEY_Thai_thanthakhat
// constant : KEY_Thai_thonangmontho
// constant : KEY_Thai_thophuthao
// constant : KEY_Thai_thothahan
// constant : KEY_Thai_thothan
// constant : KEY_Thai_thothong
// constant : KEY_Thai_thothung
// constant : KEY_Thai_topatak
// constant : KEY_Thai_totao
// constant : KEY_Thai_wowaen
// constant : KEY_Thai_yoyak
// constant : KEY_Thai_yoying
// constant : KEY_Thorn
// constant : KEY_Time
// constant : KEY_ToDoList
// constant : KEY_Tools
// constant : KEY_TopMenu
// constant : KEY_TouchpadOff
// constant : KEY_TouchpadOn
// constant : KEY_TouchpadToggle
// constant : KEY_Touroku
// constant : KEY_Travel
// constant : KEY_Tslash
// constant : KEY_U
// constant : KEY_UWB
// constant : KEY_Uacute
// constant : KEY_Ubelowdot
// constant : KEY_Ubreve
// constant : KEY_Ucircumflex
// constant : KEY_Udiaeresis
// constant : KEY_Udoubleacute
// constant : KEY_Ugrave
// constant : KEY_Uhook
// constant : KEY_Uhorn
// constant : KEY_Uhornacute
// constant : KEY_Uhornbelowdot
// constant : KEY_Uhorngrave
// constant : KEY_Uhornhook
// constant : KEY_Uhorntilde
// constant : KEY_Ukrainian_GHE_WITH_UPTURN
// constant : KEY_Ukrainian_I
// constant : KEY_Ukrainian_IE
// constant : KEY_Ukrainian_YI
// constant : KEY_Ukrainian_ghe_with_upturn
// constant : KEY_Ukrainian_i
// constant : KEY_Ukrainian_ie
// constant : KEY_Ukrainian_yi
// constant : KEY_Ukranian_I
// constant : KEY_Ukranian_JE
// constant : KEY_Ukranian_YI
// constant : KEY_Ukranian_i
// constant : KEY_Ukranian_je
// constant : KEY_Ukranian_yi
// constant : KEY_Umacron
// constant : KEY_Undo
// constant : KEY_Ungrab
// constant : KEY_Uogonek
// constant : KEY_Up
// constant : KEY_Uring
// constant : KEY_User1KB
// constant : KEY_User2KB
// constant : KEY_UserPB
// constant : KEY_Utilde
// constant : KEY_V
// constant : KEY_VendorHome
// constant : KEY_Video
// constant : KEY_View
// constant : KEY_VoidSymbol
// constant : KEY_W
// constant : KEY_WLAN
// constant : KEY_WWW
// constant : KEY_Wacute
// constant : KEY_WakeUp
// constant : KEY_Wcircumflex
// constant : KEY_Wdiaeresis
// constant : KEY_WebCam
// constant : KEY_Wgrave
// constant : KEY_WheelButton
// constant : KEY_WindowClear
// constant : KEY_WonSign
// constant : KEY_Word
// constant : KEY_X
// constant : KEY_Xabovedot
// constant : KEY_Xfer
// constant : KEY_Y
// constant : KEY_Yacute
// constant : KEY_Ybelowdot
// constant : KEY_Ycircumflex
// constant : KEY_Ydiaeresis
// constant : KEY_Yellow
// constant : KEY_Ygrave
// constant : KEY_Yhook
// constant : KEY_Ytilde
// constant : KEY_Z
// constant : KEY_Zabovedot
// constant : KEY_Zacute
// constant : KEY_Zcaron
// constant : KEY_Zen_Koho
// constant : KEY_Zenkaku
// constant : KEY_Zenkaku_Hankaku
// constant : KEY_ZoomIn
// constant : KEY_ZoomOut
// constant : KEY_Zstroke
// constant : KEY_a
// constant : KEY_aacute
// constant : KEY_abelowdot
// constant : KEY_abovedot
// constant : KEY_abreve
// constant : KEY_abreveacute
// constant : KEY_abrevebelowdot
// constant : KEY_abrevegrave
// constant : KEY_abrevehook
// constant : KEY_abrevetilde
// constant : KEY_acircumflex
// constant : KEY_acircumflexacute
// constant : KEY_acircumflexbelowdot
// constant : KEY_acircumflexgrave
// constant : KEY_acircumflexhook
// constant : KEY_acircumflextilde
// constant : KEY_acute
// constant : KEY_adiaeresis
// constant : KEY_ae
// constant : KEY_agrave
// constant : KEY_ahook
// constant : KEY_amacron
// constant : KEY_ampersand
// constant : KEY_aogonek
// constant : KEY_apostrophe
// constant : KEY_approxeq
// constant : KEY_approximate
// constant : KEY_aring
// constant : KEY_asciicircum
// constant : KEY_asciitilde
// constant : KEY_asterisk
// constant : KEY_at
// constant : KEY_atilde
// constant : KEY_b
// constant : KEY_babovedot
// constant : KEY_backslash
// constant : KEY_ballotcross
// constant : KEY_bar
// constant : KEY_because
// constant : KEY_blank
// constant : KEY_botintegral
// constant : KEY_botleftparens
// constant : KEY_botleftsqbracket
// constant : KEY_botleftsummation
// constant : KEY_botrightparens
// constant : KEY_botrightsqbracket
// constant : KEY_botrightsummation
// constant : KEY_bott
// constant : KEY_botvertsummationconnector
// constant : KEY_braceleft
// constant : KEY_braceright
// constant : KEY_bracketleft
// constant : KEY_bracketright
// constant : KEY_braille_blank
// constant : KEY_braille_dot_1
// constant : KEY_braille_dot_10
// constant : KEY_braille_dot_2
// constant : KEY_braille_dot_3
// constant : KEY_braille_dot_4
// constant : KEY_braille_dot_5
// constant : KEY_braille_dot_6
// constant : KEY_braille_dot_7
// constant : KEY_braille_dot_8
// constant : KEY_braille_dot_9
// constant : KEY_braille_dots_1
// constant : KEY_braille_dots_12
// constant : KEY_braille_dots_123
// constant : KEY_braille_dots_1234
// constant : KEY_braille_dots_12345
// constant : KEY_braille_dots_123456
// constant : KEY_braille_dots_1234567
// constant : KEY_braille_dots_12345678
// constant : KEY_braille_dots_1234568
// constant : KEY_braille_dots_123457
// constant : KEY_braille_dots_1234578
// constant : KEY_braille_dots_123458
// constant : KEY_braille_dots_12346
// constant : KEY_braille_dots_123467
// constant : KEY_braille_dots_1234678
// constant : KEY_braille_dots_123468
// constant : KEY_braille_dots_12347
// constant : KEY_braille_dots_123478
// constant : KEY_braille_dots_12348
// constant : KEY_braille_dots_1235
// constant : KEY_braille_dots_12356
// constant : KEY_braille_dots_123567
// constant : KEY_braille_dots_1235678
// constant : KEY_braille_dots_123568
// constant : KEY_braille_dots_12357
// constant : KEY_braille_dots_123578
// constant : KEY_braille_dots_12358
// constant : KEY_braille_dots_1236
// constant : KEY_braille_dots_12367
// constant : KEY_braille_dots_123678
// constant : KEY_braille_dots_12368
// constant : KEY_braille_dots_1237
// constant : KEY_braille_dots_12378
// constant : KEY_braille_dots_1238
// constant : KEY_braille_dots_124
// constant : KEY_braille_dots_1245
// constant : KEY_braille_dots_12456
// constant : KEY_braille_dots_124567
// constant : KEY_braille_dots_1245678
// constant : KEY_braille_dots_124568
// constant : KEY_braille_dots_12457
// constant : KEY_braille_dots_124578
// constant : KEY_braille_dots_12458
// constant : KEY_braille_dots_1246
// constant : KEY_braille_dots_12467
// constant : KEY_braille_dots_124678
// constant : KEY_braille_dots_12468
// constant : KEY_braille_dots_1247
// constant : KEY_braille_dots_12478
// constant : KEY_braille_dots_1248
// constant : KEY_braille_dots_125
// constant : KEY_braille_dots_1256
// constant : KEY_braille_dots_12567
// constant : KEY_braille_dots_125678
// constant : KEY_braille_dots_12568
// constant : KEY_braille_dots_1257
// constant : KEY_braille_dots_12578
// constant : KEY_braille_dots_1258
// constant : KEY_braille_dots_126
// constant : KEY_braille_dots_1267
// constant : KEY_braille_dots_12678
// constant : KEY_braille_dots_1268
// constant : KEY_braille_dots_127
// constant : KEY_braille_dots_1278
// constant : KEY_braille_dots_128
// constant : KEY_braille_dots_13
// constant : KEY_braille_dots_134
// constant : KEY_braille_dots_1345
// constant : KEY_braille_dots_13456
// constant : KEY_braille_dots_134567
// constant : KEY_braille_dots_1345678
// constant : KEY_braille_dots_134568
// constant : KEY_braille_dots_13457
// constant : KEY_braille_dots_134578
// constant : KEY_braille_dots_13458
// constant : KEY_braille_dots_1346
// constant : KEY_braille_dots_13467
// constant : KEY_braille_dots_134678
// constant : KEY_braille_dots_13468
// constant : KEY_braille_dots_1347
// constant : KEY_braille_dots_13478
// constant : KEY_braille_dots_1348
// constant : KEY_braille_dots_135
// constant : KEY_braille_dots_1356
// constant : KEY_braille_dots_13567
// constant : KEY_braille_dots_135678
// constant : KEY_braille_dots_13568
// constant : KEY_braille_dots_1357
// constant : KEY_braille_dots_13578
// constant : KEY_braille_dots_1358
// constant : KEY_braille_dots_136
// constant : KEY_braille_dots_1367
// constant : KEY_braille_dots_13678
// constant : KEY_braille_dots_1368
// constant : KEY_braille_dots_137
// constant : KEY_braille_dots_1378
// constant : KEY_braille_dots_138
// constant : KEY_braille_dots_14
// constant : KEY_braille_dots_145
// constant : KEY_braille_dots_1456
// constant : KEY_braille_dots_14567
// constant : KEY_braille_dots_145678
// constant : KEY_braille_dots_14568
// constant : KEY_braille_dots_1457
// constant : KEY_braille_dots_14578
// constant : KEY_braille_dots_1458
// constant : KEY_braille_dots_146
// constant : KEY_braille_dots_1467
// constant : KEY_braille_dots_14678
// constant : KEY_braille_dots_1468
// constant : KEY_braille_dots_147
// constant : KEY_braille_dots_1478
// constant : KEY_braille_dots_148
// constant : KEY_braille_dots_15
// constant : KEY_braille_dots_156
// constant : KEY_braille_dots_1567
// constant : KEY_braille_dots_15678
// constant : KEY_braille_dots_1568
// constant : KEY_braille_dots_157
// constant : KEY_braille_dots_1578
// constant : KEY_braille_dots_158
// constant : KEY_braille_dots_16
// constant : KEY_braille_dots_167
// constant : KEY_braille_dots_1678
// constant : KEY_braille_dots_168
// constant : KEY_braille_dots_17
// constant : KEY_braille_dots_178
// constant : KEY_braille_dots_18
// constant : KEY_braille_dots_2
// constant : KEY_braille_dots_23
// constant : KEY_braille_dots_234
// constant : KEY_braille_dots_2345
// constant : KEY_braille_dots_23456
// constant : KEY_braille_dots_234567
// constant : KEY_braille_dots_2345678
// constant : KEY_braille_dots_234568
// constant : KEY_braille_dots_23457
// constant : KEY_braille_dots_234578
// constant : KEY_braille_dots_23458
// constant : KEY_braille_dots_2346
// constant : KEY_braille_dots_23467
// constant : KEY_braille_dots_234678
// constant : KEY_braille_dots_23468
// constant : KEY_braille_dots_2347
// constant : KEY_braille_dots_23478
// constant : KEY_braille_dots_2348
// constant : KEY_braille_dots_235
// constant : KEY_braille_dots_2356
// constant : KEY_braille_dots_23567
// constant : KEY_braille_dots_235678
// constant : KEY_braille_dots_23568
// constant : KEY_braille_dots_2357
// constant : KEY_braille_dots_23578
// constant : KEY_braille_dots_2358
// constant : KEY_braille_dots_236
// constant : KEY_braille_dots_2367
// constant : KEY_braille_dots_23678
// constant : KEY_braille_dots_2368
// constant : KEY_braille_dots_237
// constant : KEY_braille_dots_2378
// constant : KEY_braille_dots_238
// constant : KEY_braille_dots_24
// constant : KEY_braille_dots_245
// constant : KEY_braille_dots_2456
// constant : KEY_braille_dots_24567
// constant : KEY_braille_dots_245678
// constant : KEY_braille_dots_24568
// constant : KEY_braille_dots_2457
// constant : KEY_braille_dots_24578
// constant : KEY_braille_dots_2458
// constant : KEY_braille_dots_246
// constant : KEY_braille_dots_2467
// constant : KEY_braille_dots_24678
// constant : KEY_braille_dots_2468
// constant : KEY_braille_dots_247
// constant : KEY_braille_dots_2478
// constant : KEY_braille_dots_248
// constant : KEY_braille_dots_25
// constant : KEY_braille_dots_256
// constant : KEY_braille_dots_2567
// constant : KEY_braille_dots_25678
// constant : KEY_braille_dots_2568
// constant : KEY_braille_dots_257
// constant : KEY_braille_dots_2578
// constant : KEY_braille_dots_258
// constant : KEY_braille_dots_26
// constant : KEY_braille_dots_267
// constant : KEY_braille_dots_2678
// constant : KEY_braille_dots_268
// constant : KEY_braille_dots_27
// constant : KEY_braille_dots_278
// constant : KEY_braille_dots_28
// constant : KEY_braille_dots_3
// constant : KEY_braille_dots_34
// constant : KEY_braille_dots_345
// constant : KEY_braille_dots_3456
// constant : KEY_braille_dots_34567
// constant : KEY_braille_dots_345678
// constant : KEY_braille_dots_34568
// constant : KEY_braille_dots_3457
// constant : KEY_braille_dots_34578
// constant : KEY_braille_dots_3458
// constant : KEY_braille_dots_346
// constant : KEY_braille_dots_3467
// constant : KEY_braille_dots_34678
// constant : KEY_braille_dots_3468
// constant : KEY_braille_dots_347
// constant : KEY_braille_dots_3478
// constant : KEY_braille_dots_348
// constant : KEY_braille_dots_35
// constant : KEY_braille_dots_356
// constant : KEY_braille_dots_3567
// constant : KEY_braille_dots_35678
// constant : KEY_braille_dots_3568
// constant : KEY_braille_dots_357
// constant : KEY_braille_dots_3578
// constant : KEY_braille_dots_358
// constant : KEY_braille_dots_36
// constant : KEY_braille_dots_367
// constant : KEY_braille_dots_3678
// constant : KEY_braille_dots_368
// constant : KEY_braille_dots_37
// constant : KEY_braille_dots_378
// constant : KEY_braille_dots_38
// constant : KEY_braille_dots_4
// constant : KEY_braille_dots_45
// constant : KEY_braille_dots_456
// constant : KEY_braille_dots_4567
// constant : KEY_braille_dots_45678
// constant : KEY_braille_dots_4568
// constant : KEY_braille_dots_457
// constant : KEY_braille_dots_4578
// constant : KEY_braille_dots_458
// constant : KEY_braille_dots_46
// constant : KEY_braille_dots_467
// constant : KEY_braille_dots_4678
// constant : KEY_braille_dots_468
// constant : KEY_braille_dots_47
// constant : KEY_braille_dots_478
// constant : KEY_braille_dots_48
// constant : KEY_braille_dots_5
// constant : KEY_braille_dots_56
// constant : KEY_braille_dots_567
// constant : KEY_braille_dots_5678
// constant : KEY_braille_dots_568
// constant : KEY_braille_dots_57
// constant : KEY_braille_dots_578
// constant : KEY_braille_dots_58
// constant : KEY_braille_dots_6
// constant : KEY_braille_dots_67
// constant : KEY_braille_dots_678
// constant : KEY_braille_dots_68
// constant : KEY_braille_dots_7
// constant : KEY_braille_dots_78
// constant : KEY_braille_dots_8
// constant : KEY_breve
// constant : KEY_brokenbar
// constant : KEY_c
// constant : KEY_c_h
// constant : KEY_cabovedot
// constant : KEY_cacute
// constant : KEY_careof
// constant : KEY_caret
// constant : KEY_caron
// constant : KEY_ccaron
// constant : KEY_ccedilla
// constant : KEY_ccircumflex
// constant : KEY_cedilla
// constant : KEY_cent
// constant : KEY_ch
// constant : KEY_checkerboard
// constant : KEY_checkmark
// constant : KEY_circle
// constant : KEY_club
// constant : KEY_colon
// constant : KEY_comma
// constant : KEY_containsas
// constant : KEY_copyright
// constant : KEY_cr
// constant : KEY_crossinglines
// constant : KEY_cuberoot
// constant : KEY_currency
// constant : KEY_cursor
// constant : KEY_d
// constant : KEY_dabovedot
// constant : KEY_dagger
// constant : KEY_dcaron
// constant : KEY_dead_A
// constant : KEY_dead_E
// constant : KEY_dead_I
// constant : KEY_dead_O
// constant : KEY_dead_U
// constant : KEY_dead_a
// constant : KEY_dead_abovecomma
// constant : KEY_dead_abovedot
// constant : KEY_dead_abovereversedcomma
// constant : KEY_dead_abovering
// constant : KEY_dead_acute
// constant : KEY_dead_belowbreve
// constant : KEY_dead_belowcircumflex
// constant : KEY_dead_belowcomma
// constant : KEY_dead_belowdiaeresis
// constant : KEY_dead_belowdot
// constant : KEY_dead_belowmacron
// constant : KEY_dead_belowring
// constant : KEY_dead_belowtilde
// constant : KEY_dead_breve
// constant : KEY_dead_capital_schwa
// constant : KEY_dead_caron
// constant : KEY_dead_cedilla
// constant : KEY_dead_circumflex
// constant : KEY_dead_currency
// constant : KEY_dead_dasia
// constant : KEY_dead_diaeresis
// constant : KEY_dead_doubleacute
// constant : KEY_dead_doublegrave
// constant : KEY_dead_e
// constant : KEY_dead_grave
// constant : KEY_dead_greek
// constant : KEY_dead_hook
// constant : KEY_dead_horn
// constant : KEY_dead_i
// constant : KEY_dead_invertedbreve
// constant : KEY_dead_iota
// constant : KEY_dead_macron
// constant : KEY_dead_o
// constant : KEY_dead_ogonek
// constant : KEY_dead_perispomeni
// constant : KEY_dead_psili
// constant : KEY_dead_semivoiced_sound
// constant : KEY_dead_small_schwa
// constant : KEY_dead_stroke
// constant : KEY_dead_tilde
// constant : KEY_dead_u
// constant : KEY_dead_voiced_sound
// constant : KEY_decimalpoint
// constant : KEY_degree
// constant : KEY_diaeresis
// constant : KEY_diamond
// constant : KEY_digitspace
// constant : KEY_dintegral
// constant : KEY_division
// constant : KEY_dollar
// constant : KEY_doubbaselinedot
// constant : KEY_doubleacute
// constant : KEY_doubledagger
// constant : KEY_doublelowquotemark
// constant : KEY_downarrow
// constant : KEY_downcaret
// constant : KEY_downshoe
// constant : KEY_downstile
// constant : KEY_downtack
// constant : KEY_dstroke
// constant : KEY_e
// constant : KEY_eabovedot
// constant : KEY_eacute
// constant : KEY_ebelowdot
// constant : KEY_ecaron
// constant : KEY_ecircumflex
// constant : KEY_ecircumflexacute
// constant : KEY_ecircumflexbelowdot
// constant : KEY_ecircumflexgrave
// constant : KEY_ecircumflexhook
// constant : KEY_ecircumflextilde
// constant : KEY_ediaeresis
// constant : KEY_egrave
// constant : KEY_ehook
// constant : KEY_eightsubscript
// constant : KEY_eightsuperior
// constant : KEY_elementof
// constant : KEY_ellipsis
// constant : KEY_em3space
// constant : KEY_em4space
// constant : KEY_emacron
// constant : KEY_emdash
// constant : KEY_emfilledcircle
// constant : KEY_emfilledrect
// constant : KEY_emopencircle
// constant : KEY_emopenrectangle
// constant : KEY_emptyset
// constant : KEY_emspace
// constant : KEY_endash
// constant : KEY_enfilledcircbullet
// constant : KEY_enfilledsqbullet
// constant : KEY_eng
// constant : KEY_enopencircbullet
// constant : KEY_enopensquarebullet
// constant : KEY_enspace
// constant : KEY_eogonek
// constant : KEY_equal
// constant : KEY_eth
// constant : KEY_etilde
// constant : KEY_exclam
// constant : KEY_exclamdown
// constant : KEY_ezh
// constant : KEY_f
// constant : KEY_fabovedot
// constant : KEY_femalesymbol
// constant : KEY_ff
// constant : KEY_figdash
// constant : KEY_filledlefttribullet
// constant : KEY_filledrectbullet
// constant : KEY_filledrighttribullet
// constant : KEY_filledtribulletdown
// constant : KEY_filledtribulletup
// constant : KEY_fiveeighths
// constant : KEY_fivesixths
// constant : KEY_fivesubscript
// constant : KEY_fivesuperior
// constant : KEY_fourfifths
// constant : KEY_foursubscript
// constant : KEY_foursuperior
// constant : KEY_fourthroot
// constant : KEY_function
// constant : KEY_g
// constant : KEY_gabovedot
// constant : KEY_gbreve
// constant : KEY_gcaron
// constant : KEY_gcedilla
// constant : KEY_gcircumflex
// constant : KEY_grave
// constant : KEY_greater
// constant : KEY_greaterthanequal
// constant : KEY_guillemotleft
// constant : KEY_guillemotright
// constant : KEY_h
// constant : KEY_hairspace
// constant : KEY_hcircumflex
// constant : KEY_heart
// constant : KEY_hebrew_aleph
// constant : KEY_hebrew_ayin
// constant : KEY_hebrew_bet
// constant : KEY_hebrew_beth
// constant : KEY_hebrew_chet
// constant : KEY_hebrew_dalet
// constant : KEY_hebrew_daleth
// constant : KEY_hebrew_doublelowline
// constant : KEY_hebrew_finalkaph
// constant : KEY_hebrew_finalmem
// constant : KEY_hebrew_finalnun
// constant : KEY_hebrew_finalpe
// constant : KEY_hebrew_finalzade
// constant : KEY_hebrew_finalzadi
// constant : KEY_hebrew_gimel
// constant : KEY_hebrew_gimmel
// constant : KEY_hebrew_he
// constant : KEY_hebrew_het
// constant : KEY_hebrew_kaph
// constant : KEY_hebrew_kuf
// constant : KEY_hebrew_lamed
// constant : KEY_hebrew_mem
// constant : KEY_hebrew_nun
// constant : KEY_hebrew_pe
// constant : KEY_hebrew_qoph
// constant : KEY_hebrew_resh
// constant : KEY_hebrew_samech
// constant : KEY_hebrew_samekh
// constant : KEY_hebrew_shin
// constant : KEY_hebrew_taf
// constant : KEY_hebrew_taw
// constant : KEY_hebrew_tet
// constant : KEY_hebrew_teth
// constant : KEY_hebrew_waw
// constant : KEY_hebrew_yod
// constant : KEY_hebrew_zade
// constant : KEY_hebrew_zadi
// constant : KEY_hebrew_zain
// constant : KEY_hebrew_zayin
// constant : KEY_hexagram
// constant : KEY_horizconnector
// constant : KEY_horizlinescan1
// constant : KEY_horizlinescan3
// constant : KEY_horizlinescan5
// constant : KEY_horizlinescan7
// constant : KEY_horizlinescan9
// constant : KEY_hstroke
// constant : KEY_ht
// constant : KEY_hyphen
// constant : KEY_i
// constant : KEY_iTouch
// constant : KEY_iacute
// constant : KEY_ibelowdot
// constant : KEY_ibreve
// constant : KEY_icircumflex
// constant : KEY_identical
// constant : KEY_idiaeresis
// constant : KEY_idotless
// constant : KEY_ifonlyif
// constant : KEY_igrave
// constant : KEY_ihook
// constant : KEY_imacron
// constant : KEY_implies
// constant : KEY_includedin
// constant : KEY_includes
// constant : KEY_infinity
// constant : KEY_integral
// constant : KEY_intersection
// constant : KEY_iogonek
// constant : KEY_itilde
// constant : KEY_j
// constant : KEY_jcircumflex
// constant : KEY_jot
// constant : KEY_k
// constant : KEY_kana_A
// constant : KEY_kana_CHI
// constant : KEY_kana_E
// constant : KEY_kana_FU
// constant : KEY_kana_HA
// constant : KEY_kana_HE
// constant : KEY_kana_HI
// constant : KEY_kana_HO
// constant : KEY_kana_HU
// constant : KEY_kana_I
// constant : KEY_kana_KA
// constant : KEY_kana_KE
// constant : KEY_kana_KI
// constant : KEY_kana_KO
// constant : KEY_kana_KU
// constant : KEY_kana_MA
// constant : KEY_kana_ME
// constant : KEY_kana_MI
// constant : KEY_kana_MO
// constant : KEY_kana_MU
// constant : KEY_kana_N
// constant : KEY_kana_NA
// constant : KEY_kana_NE
// constant : KEY_kana_NI
// constant : KEY_kana_NO
// constant : KEY_kana_NU
// constant : KEY_kana_O
// constant : KEY_kana_RA
// constant : KEY_kana_RE
// constant : KEY_kana_RI
// constant : KEY_kana_RO
// constant : KEY_kana_RU
// constant : KEY_kana_SA
// constant : KEY_kana_SE
// constant : KEY_kana_SHI
// constant : KEY_kana_SO
// constant : KEY_kana_SU
// constant : KEY_kana_TA
// constant : KEY_kana_TE
// constant : KEY_kana_TI
// constant : KEY_kana_TO
// constant : KEY_kana_TSU
// constant : KEY_kana_TU
// constant : KEY_kana_U
// constant : KEY_kana_WA
// constant : KEY_kana_WO
// constant : KEY_kana_YA
// constant : KEY_kana_YO
// constant : KEY_kana_YU
// constant : KEY_kana_a
// constant : KEY_kana_closingbracket
// constant : KEY_kana_comma
// constant : KEY_kana_conjunctive
// constant : KEY_kana_e
// constant : KEY_kana_fullstop
// constant : KEY_kana_i
// constant : KEY_kana_middledot
// constant : KEY_kana_o
// constant : KEY_kana_openingbracket
// constant : KEY_kana_switch
// constant : KEY_kana_tsu
// constant : KEY_kana_tu
// constant : KEY_kana_u
// constant : KEY_kana_ya
// constant : KEY_kana_yo
// constant : KEY_kana_yu
// constant : KEY_kappa
// constant : KEY_kcedilla
// constant : KEY_kra
// constant : KEY_l
// constant : KEY_lacute
// constant : KEY_latincross
// constant : KEY_lbelowdot
// constant : KEY_lcaron
// constant : KEY_lcedilla
// constant : KEY_leftanglebracket
// constant : KEY_leftarrow
// constant : KEY_leftcaret
// constant : KEY_leftdoublequotemark
// constant : KEY_leftmiddlecurlybrace
// constant : KEY_leftopentriangle
// constant : KEY_leftpointer
// constant : KEY_leftradical
// constant : KEY_leftshoe
// constant : KEY_leftsinglequotemark
// constant : KEY_leftt
// constant : KEY_lefttack
// constant : KEY_less
// constant : KEY_lessthanequal
// constant : KEY_lf
// constant : KEY_logicaland
// constant : KEY_logicalor
// constant : KEY_lowleftcorner
// constant : KEY_lowrightcorner
// constant : KEY_lstroke
// constant : KEY_m
// constant : KEY_mabovedot
// constant : KEY_macron
// constant : KEY_malesymbol
// constant : KEY_maltesecross
// constant : KEY_marker
// constant : KEY_masculine
// constant : KEY_minus
// constant : KEY_minutes
// constant : KEY_mu
// constant : KEY_multiply
// constant : KEY_musicalflat
// constant : KEY_musicalsharp
// constant : KEY_n
// constant : KEY_nabla
// constant : KEY_nacute
// constant : KEY_ncaron
// constant : KEY_ncedilla
// constant : KEY_ninesubscript
// constant : KEY_ninesuperior
// constant : KEY_nl
// constant : KEY_nobreakspace
// constant : KEY_notapproxeq
// constant : KEY_notelementof
// constant : KEY_notequal
// constant : KEY_notidentical
// constant : KEY_notsign
// constant : KEY_ntilde
// constant : KEY_numbersign
// constant : KEY_numerosign
// constant : KEY_o
// constant : KEY_oacute
// constant : KEY_obarred
// constant : KEY_obelowdot
// constant : KEY_ocaron
// constant : KEY_ocircumflex
// constant : KEY_ocircumflexacute
// constant : KEY_ocircumflexbelowdot
// constant : KEY_ocircumflexgrave
// constant : KEY_ocircumflexhook
// constant : KEY_ocircumflextilde
// constant : KEY_odiaeresis
// constant : KEY_odoubleacute
// constant : KEY_oe
// constant : KEY_ogonek
// constant : KEY_ograve
// constant : KEY_ohook
// constant : KEY_ohorn
// constant : KEY_ohornacute
// constant : KEY_ohornbelowdot
// constant : KEY_ohorngrave
// constant : KEY_ohornhook
// constant : KEY_ohorntilde
// constant : KEY_omacron
// constant : KEY_oneeighth
// constant : KEY_onefifth
// constant : KEY_onehalf
// constant : KEY_onequarter
// constant : KEY_onesixth
// constant : KEY_onesubscript
// constant : KEY_onesuperior
// constant : KEY_onethird
// constant : KEY_ooblique
// constant : KEY_openrectbullet
// constant : KEY_openstar
// constant : KEY_opentribulletdown
// constant : KEY_opentribulletup
// constant : KEY_ordfeminine
// constant : KEY_oslash
// constant : KEY_otilde
// constant : KEY_overbar
// constant : KEY_overline
// constant : KEY_p
// constant : KEY_pabovedot
// constant : KEY_paragraph
// constant : KEY_parenleft
// constant : KEY_parenright
// constant : KEY_partdifferential
// constant : KEY_partialderivative
// constant : KEY_percent
// constant : KEY_period
// constant : KEY_periodcentered
// constant : KEY_permille
// constant : KEY_phonographcopyright
// constant : KEY_plus
// constant : KEY_plusminus
// constant : KEY_prescription
// constant : KEY_prolongedsound
// constant : KEY_punctspace
// constant : KEY_q
// constant : KEY_quad
// constant : KEY_question
// constant : KEY_questiondown
// constant : KEY_quotedbl
// constant : KEY_quoteleft
// constant : KEY_quoteright
// constant : KEY_r
// constant : KEY_racute
// constant : KEY_radical
// constant : KEY_rcaron
// constant : KEY_rcedilla
// constant : KEY_registered
// constant : KEY_rightanglebracket
// constant : KEY_rightarrow
// constant : KEY_rightcaret
// constant : KEY_rightdoublequotemark
// constant : KEY_rightmiddlecurlybrace
// constant : KEY_rightmiddlesummation
// constant : KEY_rightopentriangle
// constant : KEY_rightpointer
// constant : KEY_rightshoe
// constant : KEY_rightsinglequotemark
// constant : KEY_rightt
// constant : KEY_righttack
// constant : KEY_s
// constant : KEY_sabovedot
// constant : KEY_sacute
// constant : KEY_scaron
// constant : KEY_scedilla
// constant : KEY_schwa
// constant : KEY_scircumflex
// constant : KEY_script_switch
// constant : KEY_seconds
// constant : KEY_section
// constant : KEY_semicolon
// constant : KEY_semivoicedsound
// constant : KEY_seveneighths
// constant : KEY_sevensubscript
// constant : KEY_sevensuperior
// constant : KEY_signaturemark
// constant : KEY_signifblank
// constant : KEY_similarequal
// constant : KEY_singlelowquotemark
// constant : KEY_sixsubscript
// constant : KEY_sixsuperior
// constant : KEY_slash
// constant : KEY_soliddiamond
// constant : KEY_space
// constant : KEY_squareroot
// constant : KEY_ssharp
// constant : KEY_sterling
// constant : KEY_stricteq
// constant : KEY_t
// constant : KEY_tabovedot
// constant : KEY_tcaron
// constant : KEY_tcedilla
// constant : KEY_telephone
// constant : KEY_telephonerecorder
// constant : KEY_therefore
// constant : KEY_thinspace
// constant : KEY_thorn
// constant : KEY_threeeighths
// constant : KEY_threefifths
// constant : KEY_threequarters
// constant : KEY_threesubscript
// constant : KEY_threesuperior
// constant : KEY_tintegral
// constant : KEY_topintegral
// constant : KEY_topleftparens
// constant : KEY_topleftradical
// constant : KEY_topleftsqbracket
// constant : KEY_topleftsummation
// constant : KEY_toprightparens
// constant : KEY_toprightsqbracket
// constant : KEY_toprightsummation
// constant : KEY_topt
// constant : KEY_topvertsummationconnector
// constant : KEY_trademark
// constant : KEY_trademarkincircle
// constant : KEY_tslash
// constant : KEY_twofifths
// constant : KEY_twosubscript
// constant : KEY_twosuperior
// constant : KEY_twothirds
// constant : KEY_u
// constant : KEY_uacute
// constant : KEY_ubelowdot
// constant : KEY_ubreve
// constant : KEY_ucircumflex
// constant : KEY_udiaeresis
// constant : KEY_udoubleacute
// constant : KEY_ugrave
// constant : KEY_uhook
// constant : KEY_uhorn
// constant : KEY_uhornacute
// constant : KEY_uhornbelowdot
// constant : KEY_uhorngrave
// constant : KEY_uhornhook
// constant : KEY_uhorntilde
// constant : KEY_umacron
// constant : KEY_underbar
// constant : KEY_underscore
// constant : KEY_union
// constant : KEY_uogonek
// constant : KEY_uparrow
// constant : KEY_upcaret
// constant : KEY_upleftcorner
// constant : KEY_uprightcorner
// constant : KEY_upshoe
// constant : KEY_upstile
// constant : KEY_uptack
// constant : KEY_uring
// constant : KEY_utilde
// constant : KEY_v
// constant : KEY_variation
// constant : KEY_vertbar
// constant : KEY_vertconnector
// constant : KEY_voicedsound
// constant : KEY_vt
// constant : KEY_w
// constant : KEY_wacute
// constant : KEY_wcircumflex
// constant : KEY_wdiaeresis
// constant : KEY_wgrave
// constant : KEY_x
// constant : KEY_xabovedot
// constant : KEY_y
// constant : KEY_yacute
// constant : KEY_ybelowdot
// constant : KEY_ycircumflex
// constant : KEY_ydiaeresis
// constant : KEY_yen
// constant : KEY_ygrave
// constant : KEY_yhook
// constant : KEY_ytilde
// constant : KEY_z
// constant : KEY_zabovedot
// constant : KEY_zacute
// constant : KEY_zcaron
// constant : KEY_zerosubscript
// constant : KEY_zerosuperior
// constant : KEY_zstroke
// constant : MAJOR_VERSION
// constant : MAX_TIMECOORD_AXES
// constant : MICRO_VERSION
// constant : MINOR_VERSION
// constant : PARENT_RELATIVE
// constant : PRIORITY_REDRAW
