// Code generated - DO NOT EDIT.
// +build gdk_3.22

package gdk

// #include <gdk/gdk.h>
import "C"

// bitfields
type AnchorHints C.GdkAnchorHints
type AxisFlags C.GdkAxisFlags
type DragAction C.GdkDragAction
type EventMask C.GdkEventMask
type FrameClockPhase C.GdkFrameClockPhase
type ModifierType C.GdkModifierType
type SeatCapabilities C.GdkSeatCapabilities
type WMDecoration C.GdkWMDecoration
type WMFunction C.GdkWMFunction
type WindowAttributesType C.GdkWindowAttributesType
type WindowHints C.GdkWindowHints
type WindowState C.GdkWindowState

// enumerations
type AxisUse C.GdkAxisUse
type ByteOrder C.GdkByteOrder
type CrossingMode C.GdkCrossingMode
type CursorType C.GdkCursorType
type DevicePadFeature C.GdkDevicePadFeature
type DeviceToolType C.GdkDeviceToolType
type DeviceType C.GdkDeviceType
type DragCancelReason C.GdkDragCancelReason
type DragProtocol C.GdkDragProtocol
type EventType C.GdkEventType
type FilterReturn C.GdkFilterReturn
type FullscreenMode C.GdkFullscreenMode
type GLError C.GdkGLError
type GrabOwnership C.GdkGrabOwnership
type GrabStatus C.GdkGrabStatus
type Gravity C.GdkGravity
type InputMode C.GdkInputMode
type InputSource C.GdkInputSource
type ModifierIntent C.GdkModifierIntent
type NotifyType C.GdkNotifyType
type OwnerChange C.GdkOwnerChange
type PropMode C.GdkPropMode
type PropertyState C.GdkPropertyState
type ScrollDirection C.GdkScrollDirection
type SettingAction C.GdkSettingAction
type Status C.GdkStatus
type SubpixelLayout C.GdkSubpixelLayout
type TouchpadGesturePhase C.GdkTouchpadGesturePhase
type VisibilityState C.GdkVisibilityState
type VisualType C.GdkVisualType
type WindowEdge C.GdkWindowEdge
type WindowType C.GdkWindowType
type WindowTypeHint C.GdkWindowTypeHint
type WindowWindowClass C.GdkWindowWindowClass

// records
type Atom C.GdkAtom
type Color C.GdkColor
type DevicePadInterface C.GdkDevicePadInterface
type DrawingContextClass C.GdkDrawingContextClass
type EventAny C.GdkEventAny
type EventButton C.GdkEventButton
type EventConfigure C.GdkEventConfigure
type EventCrossing C.GdkEventCrossing
type EventDND C.GdkEventDND
type EventExpose C.GdkEventExpose
type EventFocus C.GdkEventFocus
type EventGrabBroken C.GdkEventGrabBroken
type EventKey C.GdkEventKey
type EventMotion C.GdkEventMotion
type EventOwnerChange C.GdkEventOwnerChange
type EventPadAxis C.GdkEventPadAxis
type EventPadButton C.GdkEventPadButton
type EventPadGroupMode C.GdkEventPadGroupMode
type EventProperty C.GdkEventProperty
type EventProximity C.GdkEventProximity
type EventScroll C.GdkEventScroll
type EventSelection C.GdkEventSelection
type EventSequence C.GdkEventSequence
type EventSetting C.GdkEventSetting
type EventTouch C.GdkEventTouch
type EventTouchpadPinch C.GdkEventTouchpadPinch
type EventTouchpadSwipe C.GdkEventTouchpadSwipe
type EventVisibility C.GdkEventVisibility
type EventWindowState C.GdkEventWindowState
type FrameClockClass C.GdkFrameClockClass
type FrameClockPrivate C.GdkFrameClockPrivate
type FrameTimings C.GdkFrameTimings
type Geometry C.GdkGeometry
type KeymapKey C.GdkKeymapKey
type MonitorClass C.GdkMonitorClass
type Point C.GdkPoint
type RGBA C.GdkRGBA
type Rectangle C.GdkRectangle
type TimeCoord C.GdkTimeCoord
type WindowAttr C.GdkWindowAttr
type WindowClass C.GdkWindowClass
type WindowRedirect C.GdkWindowRedirect

// classes
type AppLaunchContext C.GdkAppLaunchContext
type Cursor C.GdkCursor
type Device C.GdkDevice
type DeviceManager C.GdkDeviceManager
type DeviceTool C.GdkDeviceTool
type Display C.GdkDisplay
type DisplayManager C.GdkDisplayManager
type DragContext C.GdkDragContext
type DrawingContext C.GdkDrawingContext
type FrameClock C.GdkFrameClock
type GLContext C.GdkGLContext
type Keymap C.GdkKeymap
type Monitor C.GdkMonitor
type Screen C.GdkScreen
type Seat C.GdkSeat
type Visual C.GdkVisual
type Window C.GdkWindow

// interfaces
type DevicePad C.GdkDevicePad

// functions
func Fn_add_option_entries_libgtk_only()         {}
func Fn_atom_intern()                            {}
func Fn_atom_intern_static_string()              {}
func Fn_beep()                                   {}
func Fn_cairo_create()                           {}
func Fn_cairo_draw_from_gl()                     {}
func Fn_cairo_get_clip_rectangle()               {}
func Fn_cairo_get_drawing_context()              {}
func Fn_cairo_rectangle()                        {}
func Fn_cairo_region()                           {}
func Fn_cairo_region_create_from_surface()       {}
func Fn_cairo_set_source_color()                 {}
func Fn_cairo_set_source_pixbuf()                {}
func Fn_cairo_set_source_rgba()                  {}
func Fn_cairo_set_source_window()                {}
func Fn_cairo_surface_create_from_pixbuf()       {}
func Fn_color_parse()                            {}
func Fn_disable_multidevice()                    {}
func Fn_drag_abort()                             {}
func Fn_drag_begin()                             {}
func Fn_drag_begin_for_device()                  {}
func Fn_drag_begin_from_point()                  {}
func Fn_drag_drop()                              {}
func Fn_drag_drop_done()                         {}
func Fn_drag_drop_succeeded()                    {}
func Fn_drag_find_window_for_screen()            {}
func Fn_drag_get_selection()                     {}
func Fn_drag_motion()                            {}
func Fn_drag_status()                            {}
func Fn_drop_finish()                            {}
func Fn_drop_reply()                             {}
func Fn_error_trap_pop()                         {}
func Fn_error_trap_pop_ignored()                 {}
func Fn_error_trap_push()                        {}
func Fn_event_get()                              {}
func Fn_event_handler_set()                      {}
func Fn_event_peek()                             {}
func Fn_event_request_motions()                  {}
func Fn_events_get_angle()                       {}
func Fn_events_get_center()                      {}
func Fn_events_get_distance()                    {}
func Fn_events_pending()                         {}
func Fn_flush()                                  {}
func Fn_get_default_root_window()                {}
func Fn_get_display()                            {}
func Fn_get_display_arg_name()                   {}
func Fn_get_program_class()                      {}
func Fn_get_show_events()                        {}
func Fn_gl_error_quark()                         {}
func Fn_init()                                   {}
func Fn_init_check()                             {}
func Fn_keyboard_grab()                          {}
func Fn_keyboard_ungrab()                        {}
func Fn_keyval_convert_case()                    {}
func Fn_keyval_from_name()                       {}
func Fn_keyval_is_lower()                        {}
func Fn_keyval_is_upper()                        {}
func Fn_keyval_name()                            {}
func Fn_keyval_to_lower()                        {}
func Fn_keyval_to_unicode()                      {}
func Fn_keyval_to_upper()                        {}
func Fn_list_visuals()                           {}
func Fn_notify_startup_complete()                {}
func Fn_notify_startup_complete_with_id()        {}
func Fn_offscreen_window_get_embedder()          {}
func Fn_offscreen_window_get_surface()           {}
func Fn_offscreen_window_set_embedder()          {}
func Fn_pango_context_get()                      {}
func Fn_pango_context_get_for_display()          {}
func Fn_pango_context_get_for_screen()           {}
func Fn_pango_layout_get_clip_region()           {}
func Fn_pango_layout_line_get_clip_region()      {}
func Fn_parse_args()                             {}
func Fn_pixbuf_get_from_surface()                {}
func Fn_pixbuf_get_from_window()                 {}
func Fn_pointer_grab()                           {}
func Fn_pointer_is_grabbed()                     {}
func Fn_pointer_ungrab()                         {}
func Fn_pre_parse_libgtk_only()                  {}
func Fn_property_change()                        {}
func Fn_property_delete()                        {}
func Fn_property_get()                           {}
func Fn_query_depths()                           {}
func Fn_query_visual_types()                     {}
func Fn_selection_convert()                      {}
func Fn_selection_owner_get()                    {}
func Fn_selection_owner_get_for_display()        {}
func Fn_selection_owner_set()                    {}
func Fn_selection_owner_set_for_display()        {}
func Fn_selection_property_get()                 {}
func Fn_selection_send_notify()                  {}
func Fn_selection_send_notify_for_display()      {}
func Fn_set_allowed_backends()                   {}
func Fn_set_double_click_time()                  {}
func Fn_set_program_class()                      {}
func Fn_set_show_events()                        {}
func Fn_setting_get()                            {}
func Fn_synthesize_window_state()                {}
func Fn_test_render_sync()                       {}
func Fn_test_simulate_button()                   {}
func Fn_test_simulate_key()                      {}
func Fn_text_property_to_utf8_list_for_display() {}
func Fn_threads_add_idle()                       {}
func Fn_threads_add_idle_full()                  {}
func Fn_threads_add_timeout()                    {}
func Fn_threads_add_timeout_full()               {}
func Fn_threads_add_timeout_seconds()            {}
func Fn_threads_add_timeout_seconds_full()       {}
func Fn_threads_enter()                          {}
func Fn_threads_init()                           {}
func Fn_threads_leave()                          {}
func Fn_threads_set_lock_functions()             {}
func Fn_unicode_to_keyval()                      {}
func Fn_utf8_to_string_target()                  {}
