// This is a generated file - DO NOT EDIT

package glib

// #cgo CFLAGS: -Wno-deprecated-declarations
// #cgo CFLAGS: -Wno-format-security
// #cgo CFLAGS: -Wno-incompatible-pointer-types
// #include <glib.h>
// #include <glib/gstdio.h>
// #include <glib-unix.h>
// #include <glib-object.h>
// #include <stdlib.h>
import "C"

const ANALYZER_ANALYZING int32 = C.G_ANALYZER_ANALYZING
const ASCII_DTOSTR_BUF_SIZE int32 = C.G_ASCII_DTOSTR_BUF_SIZE
const BIG_ENDIAN int32 = C.G_BIG_ENDIAN
const CSET_A_2_Z string = C.G_CSET_A_2_Z
const CSET_DIGITS string = C.G_CSET_DIGITS
const CSET_a_2_z string = C.G_CSET_a_2_z
const DATALIST_FLAGS_MASK int32 = C.G_DATALIST_FLAGS_MASK
const DATE_BAD_DAY int32 = C.G_DATE_BAD_DAY
const DATE_BAD_JULIAN int32 = C.G_DATE_BAD_JULIAN
const DATE_BAD_YEAR int32 = C.G_DATE_BAD_YEAR
const DIR_SEPARATOR int32 = C.G_DIR_SEPARATOR
const DIR_SEPARATOR_S string = C.G_DIR_SEPARATOR_S
const E float64 = C.G_E
const GINT16_FORMAT string = C.G_GINT16_FORMAT
const GINT32_FORMAT string = C.G_GINT32_FORMAT
const GINT64_FORMAT string = C.G_GINT64_FORMAT
const GNUC_FUNCTION string = C.G_GNUC_FUNCTION
const GNUC_PRETTY_FUNCTION string = C.G_GNUC_PRETTY_FUNCTION
const GUINT16_FORMAT string = C.G_GUINT16_FORMAT
const GUINT32_FORMAT string = C.G_GUINT32_FORMAT
const GUINT64_FORMAT string = C.G_GUINT64_FORMAT
const HAVE_GINT64 int32 = C.G_HAVE_GINT64
const HAVE_GNUC_VARARGS int32 = C.G_HAVE_GNUC_VARARGS
const HAVE_GNUC_VISIBILITY int32 = C.G_HAVE_GNUC_VISIBILITY
const HAVE_GROWING_STACK int32 = C.G_HAVE_GROWING_STACK
const HAVE_ISO_VARARGS int32 = C.G_HAVE_ISO_VARARGS
const HOOK_FLAG_USER_SHIFT int32 = C.G_HOOK_FLAG_USER_SHIFT
const IEEE754_DOUBLE_BIAS int32 = C.G_IEEE754_DOUBLE_BIAS
const IEEE754_FLOAT_BIAS int32 = C.G_IEEE754_FLOAT_BIAS

// Blacklisted : KEY_FILE_DESKTOP_ACTION_GROUP_PREFIX

const KEY_FILE_DESKTOP_KEY_FULLNAME string = C.G_KEY_FILE_DESKTOP_KEY_FULLNAME
const KEY_FILE_DESKTOP_KEY_GETTEXT_DOMAIN string = C.G_KEY_FILE_DESKTOP_KEY_GETTEXT_DOMAIN
const KEY_FILE_DESKTOP_KEY_KEYWORDS string = C.G_KEY_FILE_DESKTOP_KEY_KEYWORDS
const LITTLE_ENDIAN int32 = C.G_LITTLE_ENDIAN
const LN10 float64 = C.G_LN10
const LN2 float64 = C.G_LN2
const LOG_2_BASE_10 float64 = C.G_LOG_2_BASE_10

// Blacklisted : LOG_DOMAIN

const LOG_FATAL_MASK int32 = C.G_LOG_FATAL_MASK
const LOG_LEVEL_USER_SHIFT int32 = C.G_LOG_LEVEL_USER_SHIFT
const MAJOR_VERSION int32 = C.GLIB_MAJOR_VERSION
const MAXINT64 int64 = C.G_MAXINT64
const MAXUINT64 uint64 = C.G_MAXUINT64
const MICRO_VERSION int32 = C.GLIB_MICRO_VERSION
const MININT64 int64 = C.G_MININT64
const MINOR_VERSION int32 = C.GLIB_MINOR_VERSION
const MODULE_SUFFIX string = C.G_MODULE_SUFFIX
const PDP_ENDIAN int32 = C.G_PDP_ENDIAN
const PI float64 = C.G_PI
const PI_2 float64 = C.G_PI_2
const PI_4 float64 = C.G_PI_4
const POLLFD_FORMAT string = C.G_POLLFD_FORMAT
const PRIORITY_DEFAULT int32 = C.G_PRIORITY_DEFAULT
const PRIORITY_DEFAULT_IDLE int32 = C.G_PRIORITY_DEFAULT_IDLE
const PRIORITY_HIGH int32 = C.G_PRIORITY_HIGH
const PRIORITY_HIGH_IDLE int32 = C.G_PRIORITY_HIGH_IDLE
const PRIORITY_LOW int32 = C.G_PRIORITY_LOW
const SEARCHPATH_SEPARATOR int32 = C.G_SEARCHPATH_SEPARATOR
const SEARCHPATH_SEPARATOR_S string = C.G_SEARCHPATH_SEPARATOR_S
const SIZEOF_LONG int32 = C.GLIB_SIZEOF_LONG
const SIZEOF_SIZE_T int32 = C.GLIB_SIZEOF_SIZE_T
const SIZEOF_SSIZE_T int32 = C.GLIB_SIZEOF_SSIZE_T
const SIZEOF_VOID_P int32 = C.GLIB_SIZEOF_VOID_P
const SQRT2 float64 = C.G_SQRT2
const STR_DELIMITERS string = C.G_STR_DELIMITERS
const SYSDEF_AF_INET int32 = C.GLIB_SYSDEF_AF_INET
const SYSDEF_AF_INET6 int32 = C.GLIB_SYSDEF_AF_INET6
const SYSDEF_AF_UNIX int32 = C.GLIB_SYSDEF_AF_UNIX
const SYSDEF_MSG_DONTROUTE int32 = C.GLIB_SYSDEF_MSG_DONTROUTE
const SYSDEF_MSG_OOB int32 = C.GLIB_SYSDEF_MSG_OOB
const SYSDEF_MSG_PEEK int32 = C.GLIB_SYSDEF_MSG_PEEK
const URI_RESERVED_CHARS_GENERIC_DELIMITERS string = C.G_URI_RESERVED_CHARS_GENERIC_DELIMITERS
const URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS string = C.G_URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS
const USEC_PER_SEC int32 = C.G_USEC_PER_SEC
const VA_COPY_AS_ARRAY int32 = C.G_VA_COPY_AS_ARRAY

// Blacklisted : WIN32_MSG_HANDLE
