// Code generated - DO NOT EDIT.

package glib

const ANALYZER_ANALYZING int32 = "1"
const ASCII_DTOSTR_BUF_SIZE int32 = "39"
const BIG_ENDIAN int32 = "4321"

// UNSUPPORTED : CSET_A_2_Z
// UNSUPPORTED : CSET_DIGITS
// UNSUPPORTED : CSET_a_2_z
const DATALIST_FLAGS_MASK int32 = "3"
const DATE_BAD_DAY int32 = "0"
const DATE_BAD_JULIAN int32 = "0"
const DATE_BAD_YEAR int32 = "0"
const DIR_SEPARATOR int32 = "47"

// UNSUPPORTED : DIR_SEPARATOR_S
const E float64 = "2.718282"

// UNSUPPORTED : GINT16_FORMAT
// UNSUPPORTED : GINT16_MODIFIER
// UNSUPPORTED : GINT32_FORMAT
// UNSUPPORTED : GINT32_MODIFIER
// UNSUPPORTED : GINT64_FORMAT
// UNSUPPORTED : GINT64_MODIFIER
// UNSUPPORTED : GINTPTR_FORMAT
// UNSUPPORTED : GINTPTR_MODIFIER
// UNSUPPORTED : GNUC_FUNCTION
// UNSUPPORTED : GNUC_PRETTY_FUNCTION
// UNSUPPORTED : GSIZE_FORMAT
// UNSUPPORTED : GSIZE_MODIFIER
// UNSUPPORTED : GSSIZE_FORMAT
// UNSUPPORTED : GSSIZE_MODIFIER
// UNSUPPORTED : GUINT16_FORMAT
// UNSUPPORTED : GUINT32_FORMAT
// UNSUPPORTED : GUINT64_FORMAT
// UNSUPPORTED : GUINTPTR_FORMAT
const HAVE_GINT64 int32 = "1"
const HAVE_GNUC_VARARGS int32 = "1"
const HAVE_GNUC_VISIBILITY int32 = "1"
const HAVE_GROWING_STACK int32 = "0"
const HAVE_ISO_VARARGS int32 = "1"
const HOOK_FLAG_USER_SHIFT int32 = "4"
const IEEE754_DOUBLE_BIAS int32 = "1023"
const IEEE754_FLOAT_BIAS int32 = "127"

// UNSUPPORTED : KEY_FILE_DESKTOP_ACTION_GROUP_PREFIX
// UNSUPPORTED : KEY_FILE_DESKTOP_GROUP
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_ACTIONS
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_CATEGORIES
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_COMMENT
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_DBUS_ACTIVATABLE
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_EXEC
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_FULLNAME
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_GENERIC_NAME
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_GETTEXT_DOMAIN
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_HIDDEN
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_ICON
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_KEYWORDS
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_MIME_TYPE
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_NAME
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_NOT_SHOW_IN
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_NO_DISPLAY
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_ONLY_SHOW_IN
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_PATH
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_STARTUP_NOTIFY
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_STARTUP_WM_CLASS
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_TERMINAL
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_TRY_EXEC
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_TYPE
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_URL
// UNSUPPORTED : KEY_FILE_DESKTOP_KEY_VERSION
// UNSUPPORTED : KEY_FILE_DESKTOP_TYPE_APPLICATION
// UNSUPPORTED : KEY_FILE_DESKTOP_TYPE_DIRECTORY
// UNSUPPORTED : KEY_FILE_DESKTOP_TYPE_LINK
const LITTLE_ENDIAN int32 = "1234"
const LN10 float64 = "2.302585"
const LN2 float64 = "0.693147"
const LOG_2_BASE_10 float64 = "0.301030"
const LOG_DOMAIN rune = "0"
const LOG_FATAL_MASK int32 = "5"
const LOG_LEVEL_USER_SHIFT int32 = "8"
const MAJOR_VERSION int32 = "2"
const MAXINT16 int16 = "32767"
const MAXINT32 int32 = "2147483647"
const MAXINT64 int64 = "9223372036854775807"
const MAXINT8 int8 = "127"
const MAXUINT16 uint16 = "65535"
const MAXUINT32 uint32 = "4294967295"
const MAXUINT64 uint64 = "18446744073709551615"
const MAXUINT8 uint8 = "255"
const MICRO_VERSION int32 = "1"
const MININT16 int16 = "-32768"
const MININT32 int32 = "-2147483648"
const MININT64 int64 = "-9223372036854775808"
const MININT8 int8 = "-128"
const MINOR_VERSION int32 = "56"

// UNSUPPORTED : MODULE_SUFFIX
// UNSUPPORTED : OPTION_REMAINING
const PDP_ENDIAN int32 = "3412"
const PI float64 = "3.141593"

// UNSUPPORTED : PID_FORMAT
const PI_2 float64 = "1.570796"
const PI_4 float64 = "0.785398"

// UNSUPPORTED : POLLFD_FORMAT
const PRIORITY_DEFAULT int32 = "0"
const PRIORITY_DEFAULT_IDLE int32 = "200"
const PRIORITY_HIGH int32 = "-100"
const PRIORITY_HIGH_IDLE int32 = "100"
const PRIORITY_LOW int32 = "300"
const SEARCHPATH_SEPARATOR int32 = "58"

// UNSUPPORTED : SEARCHPATH_SEPARATOR_S
const SIZEOF_LONG int32 = "8"
const SIZEOF_SIZE_T int32 = "8"
const SIZEOF_SSIZE_T int32 = "8"
const SIZEOF_VOID_P int32 = "8"
const SOURCE_CONTINUE bool = "true"
const SOURCE_REMOVE bool = "false"
const SQRT2 float64 = "1.414214"

// UNSUPPORTED : STR_DELIMITERS
const SYSDEF_AF_INET int32 = "2"
const SYSDEF_AF_INET6 int32 = "10"
const SYSDEF_AF_UNIX int32 = "1"
const SYSDEF_MSG_DONTROUTE int32 = "4"
const SYSDEF_MSG_OOB int32 = "1"
const SYSDEF_MSG_PEEK int32 = "2"
const TIME_SPAN_DAY int64 = "86400000000"
const TIME_SPAN_HOUR int64 = "3600000000"
const TIME_SPAN_MILLISECOND int64 = "1000"
const TIME_SPAN_MINUTE int64 = "60000000"
const TIME_SPAN_SECOND int64 = "1000000"
const UNICHAR_MAX_DECOMPOSITION_LENGTH int32 = "18"

// UNSUPPORTED : URI_RESERVED_CHARS_GENERIC_DELIMITERS
// UNSUPPORTED : URI_RESERVED_CHARS_SUBCOMPONENT_DELIMITERS
const USEC_PER_SEC int32 = "1000000"
const VA_COPY_AS_ARRAY int32 = "1"
const VERSION_MIN_REQUIRED int32 = "2"
const WIN32_MSG_HANDLE int32 = "19981206"
