// Code generated - DO NOT EDIT.

package pango

// AttrBackgroundAlphaNew is a representation of the C type pango_attr_background_alpha_new.
// AttrBackgroundNew is a representation of the C type pango_attr_background_new.
// AttrFallbackNew is a representation of the C type pango_attr_fallback_new.
// AttrFamilyNew is a representation of the C type pango_attr_family_new.
// AttrForegroundAlphaNew is a representation of the C type pango_attr_foreground_alpha_new.
// AttrForegroundNew is a representation of the C type pango_attr_foreground_new.
// AttrGravityHintNew is a representation of the C type pango_attr_gravity_hint_new.
// AttrGravityNew is a representation of the C type pango_attr_gravity_new.
// AttrLetterSpacingNew is a representation of the C type pango_attr_letter_spacing_new.
// AttrRiseNew is a representation of the C type pango_attr_rise_new.
// AttrScaleNew is a representation of the C type pango_attr_scale_new.
// AttrStretchNew is a representation of the C type pango_attr_stretch_new.
// AttrStrikethroughColorNew is a representation of the C type pango_attr_strikethrough_color_new.
// AttrStrikethroughNew is a representation of the C type pango_attr_strikethrough_new.
// AttrStyleNew is a representation of the C type pango_attr_style_new.
// AttrTypeGetName is a representation of the C type pango_attr_type_get_name.
// AttrTypeRegister is a representation of the C type pango_attr_type_register.
// AttrUnderlineColorNew is a representation of the C type pango_attr_underline_color_new.
// AttrUnderlineNew is a representation of the C type pango_attr_underline_new.
// AttrVariantNew is a representation of the C type pango_attr_variant_new.
// AttrWeightNew is a representation of the C type pango_attr_weight_new.
// BidiTypeForUnichar is a representation of the C type pango_bidi_type_for_unichar.
// Break is a representation of the C type pango_break.
// ConfigKeyGet is a representation of the C type pango_config_key_get.
// ConfigKeyGetSystem is a representation of the C type pango_config_key_get_system.
// DefaultBreak is a representation of the C type pango_default_break.
// ExtentsToPixels is a representation of the C type pango_extents_to_pixels.
// FindBaseDir is a representation of the C type pango_find_base_dir.
// FindMap is a representation of the C type pango_find_map.
// FindParagraphBoundary is a representation of the C type pango_find_paragraph_boundary.
// FontDescriptionFromString is a representation of the C type pango_font_description_from_string.
// GetLibSubdirectory is a representation of the C type pango_get_lib_subdirectory.
// GetLogAttrs is a representation of the C type pango_get_log_attrs.
// GetMirrorChar is a representation of the C type pango_get_mirror_char.
// GetSysconfSubdirectory is a representation of the C type pango_get_sysconf_subdirectory.
// GravityGetForMatrix is a representation of the C type pango_gravity_get_for_matrix.
// GravityGetForScript is a representation of the C type pango_gravity_get_for_script.
// GravityGetForScriptAndWidth is a representation of the C type pango_gravity_get_for_script_and_width.
// GravityToRotation is a representation of the C type pango_gravity_to_rotation.
// IsZeroWidth is a representation of the C type pango_is_zero_width.
// Itemize is a representation of the C type pango_itemize.
// ItemizeWithBaseDir is a representation of the C type pango_itemize_with_base_dir.
// LanguageFromString is a representation of the C type pango_language_from_string.
// LanguageGetDefault is a representation of the C type pango_language_get_default.
// Log2visGetEmbeddingLevels is a representation of the C type pango_log2vis_get_embedding_levels.
// LookupAliases is a representation of the C type pango_lookup_aliases.
// MarkupParserFinish is a representation of the C type pango_markup_parser_finish.
// MarkupParserNew is a representation of the C type pango_markup_parser_new.
// ModuleRegister is a representation of the C type pango_module_register.
// ParseEnum is a representation of the C type pango_parse_enum.
// ParseMarkup is a representation of the C type pango_parse_markup.
// ParseStretch is a representation of the C type pango_parse_stretch.
// ParseStyle is a representation of the C type pango_parse_style.
// ParseVariant is a representation of the C type pango_parse_variant.
// ParseWeight is a representation of the C type pango_parse_weight.
// QuantizeLineGeometry is a representation of the C type pango_quantize_line_geometry.
// ReadLine is a representation of the C type pango_read_line.
// ReorderItems is a representation of the C type pango_reorder_items.
// ScanInt is a representation of the C type pango_scan_int.
// ScanString is a representation of the C type pango_scan_string.
// ScanWord is a representation of the C type pango_scan_word.
// ScriptForUnichar is a representation of the C type pango_script_for_unichar.
// ScriptGetSampleLanguage is a representation of the C type pango_script_get_sample_language.
// Shape is a representation of the C type pango_shape.
// ShapeFull is a representation of the C type pango_shape_full.
// SkipSpace is a representation of the C type pango_skip_space.
// SplitFileList is a representation of the C type pango_split_file_list.
// TrimString is a representation of the C type pango_trim_string.
// UnicharDirection is a representation of the C type pango_unichar_direction.
// UnitsFromDouble is a representation of the C type pango_units_from_double.
// UnitsToDouble is a representation of the C type pango_units_to_double.
// Version is a representation of the C type pango_version.
// VersionCheck is a representation of the C type pango_version_check.
// VersionString is a representation of the C type pango_version_string.
