// Code generated - DO NOT EDIT.

package webkit2

// UNSUPPORTED : C value 'EDITING_COMMAND_COPY'
// UNSUPPORTED : C value 'EDITING_COMMAND_CREATE_LINK'
// UNSUPPORTED : C value 'EDITING_COMMAND_CUT'
// UNSUPPORTED : C value 'EDITING_COMMAND_INSERT_IMAGE'
// UNSUPPORTED : C value 'EDITING_COMMAND_PASTE'
// UNSUPPORTED : C value 'EDITING_COMMAND_REDO'
// UNSUPPORTED : C value 'EDITING_COMMAND_SELECT_ALL'
// UNSUPPORTED : C value 'EDITING_COMMAND_UNDO'
const MajorVersion int32 = "2"
const MicroVersion int32 = "1"
const MinorVersion int32 = "26"
