// Code generated - DO NOT EDIT.

package webkit2

// UNSUPPORTED : EDITING_COMMAND_COPY
// UNSUPPORTED : EDITING_COMMAND_CREATE_LINK
// UNSUPPORTED : EDITING_COMMAND_CUT
// UNSUPPORTED : EDITING_COMMAND_INSERT_IMAGE
// UNSUPPORTED : EDITING_COMMAND_PASTE
// UNSUPPORTED : EDITING_COMMAND_REDO
// UNSUPPORTED : EDITING_COMMAND_SELECT_ALL
// UNSUPPORTED : EDITING_COMMAND_UNDO
const MAJOR_VERSION int32 = "2"
const MICRO_VERSION int32 = "1"
const MINOR_VERSION int32 = "26"
