// This is a generated file - DO NOT EDIT

package gtk

// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gtk/gtk-a11y.h>
// #include <gtk/gtk.h>
// #include <gtk/gtkx.h>
// #include <stdlib.h>
import "C"

const BINARY_AGE int = C.GTK_BINARY_AGE
const INPUT_ERROR int = C.GTK_INPUT_ERROR
const INTERFACE_AGE int = C.GTK_INTERFACE_AGE
const MAJOR_VERSION int = C.GTK_MAJOR_VERSION
const MAX_COMPOSE_LEN int = C.GTK_MAX_COMPOSE_LEN
const MICRO_VERSION int = C.GTK_MICRO_VERSION
const MINOR_VERSION int = C.GTK_MINOR_VERSION
const PAPER_NAME_A3 string = C.GTK_PAPER_NAME_A3
const PAPER_NAME_A4 string = C.GTK_PAPER_NAME_A4
const PAPER_NAME_A5 string = C.GTK_PAPER_NAME_A5
const PAPER_NAME_B5 string = C.GTK_PAPER_NAME_B5
const PAPER_NAME_EXECUTIVE string = C.GTK_PAPER_NAME_EXECUTIVE
const PAPER_NAME_LEGAL string = C.GTK_PAPER_NAME_LEGAL
const PAPER_NAME_LETTER string = C.GTK_PAPER_NAME_LETTER
const PATH_PRIO_MASK int = C.GTK_PATH_PRIO_MASK
const PRINT_SETTINGS_COLLATE string = C.GTK_PRINT_SETTINGS_COLLATE
const PRINT_SETTINGS_DEFAULT_SOURCE string = C.GTK_PRINT_SETTINGS_DEFAULT_SOURCE
const PRINT_SETTINGS_DITHER string = C.GTK_PRINT_SETTINGS_DITHER
const PRINT_SETTINGS_DUPLEX string = C.GTK_PRINT_SETTINGS_DUPLEX
const PRINT_SETTINGS_FINISHINGS string = C.GTK_PRINT_SETTINGS_FINISHINGS
const PRINT_SETTINGS_MEDIA_TYPE string = C.GTK_PRINT_SETTINGS_MEDIA_TYPE
const PRINT_SETTINGS_NUMBER_UP string = C.GTK_PRINT_SETTINGS_NUMBER_UP
const PRINT_SETTINGS_NUMBER_UP_LAYOUT string = C.GTK_PRINT_SETTINGS_NUMBER_UP_LAYOUT
const PRINT_SETTINGS_N_COPIES string = C.GTK_PRINT_SETTINGS_N_COPIES
const PRINT_SETTINGS_ORIENTATION string = C.GTK_PRINT_SETTINGS_ORIENTATION
const PRINT_SETTINGS_OUTPUT_BIN string = C.GTK_PRINT_SETTINGS_OUTPUT_BIN
const PRINT_SETTINGS_OUTPUT_FILE_FORMAT string = C.GTK_PRINT_SETTINGS_OUTPUT_FILE_FORMAT
const PRINT_SETTINGS_OUTPUT_URI string = C.GTK_PRINT_SETTINGS_OUTPUT_URI
const PRINT_SETTINGS_PAGE_RANGES string = C.GTK_PRINT_SETTINGS_PAGE_RANGES
const PRINT_SETTINGS_PAGE_SET string = C.GTK_PRINT_SETTINGS_PAGE_SET
const PRINT_SETTINGS_PAPER_FORMAT string = C.GTK_PRINT_SETTINGS_PAPER_FORMAT
const PRINT_SETTINGS_PAPER_HEIGHT string = C.GTK_PRINT_SETTINGS_PAPER_HEIGHT
const PRINT_SETTINGS_PAPER_WIDTH string = C.GTK_PRINT_SETTINGS_PAPER_WIDTH
const PRINT_SETTINGS_PRINTER string = C.GTK_PRINT_SETTINGS_PRINTER
const PRINT_SETTINGS_PRINTER_LPI string = C.GTK_PRINT_SETTINGS_PRINTER_LPI
const PRINT_SETTINGS_PRINT_PAGES string = C.GTK_PRINT_SETTINGS_PRINT_PAGES
const PRINT_SETTINGS_QUALITY string = C.GTK_PRINT_SETTINGS_QUALITY
const PRINT_SETTINGS_RESOLUTION string = C.GTK_PRINT_SETTINGS_RESOLUTION
const PRINT_SETTINGS_RESOLUTION_X string = C.GTK_PRINT_SETTINGS_RESOLUTION_X
const PRINT_SETTINGS_RESOLUTION_Y string = C.GTK_PRINT_SETTINGS_RESOLUTION_Y
const PRINT_SETTINGS_REVERSE string = C.GTK_PRINT_SETTINGS_REVERSE
const PRINT_SETTINGS_SCALE string = C.GTK_PRINT_SETTINGS_SCALE
const PRINT_SETTINGS_USE_COLOR string = C.GTK_PRINT_SETTINGS_USE_COLOR
const PRINT_SETTINGS_WIN32_DRIVER_EXTRA string = C.GTK_PRINT_SETTINGS_WIN32_DRIVER_EXTRA
const PRINT_SETTINGS_WIN32_DRIVER_VERSION string = C.GTK_PRINT_SETTINGS_WIN32_DRIVER_VERSION
const PRIORITY_RESIZE int = C.GTK_PRIORITY_RESIZE

// Blacklisted : STOCK_ABOUT

// Blacklisted : STOCK_ADD

// Blacklisted : STOCK_APPLY

// Blacklisted : STOCK_BOLD

// Blacklisted : STOCK_CANCEL

// Blacklisted : STOCK_CAPS_LOCK_WARNING

// Blacklisted : STOCK_CDROM

// Blacklisted : STOCK_CLEAR

// Blacklisted : STOCK_CLOSE

// Blacklisted : STOCK_COLOR_PICKER

// Blacklisted : STOCK_CONNECT

// Blacklisted : STOCK_CONVERT

// Blacklisted : STOCK_COPY

// Blacklisted : STOCK_CUT

// Blacklisted : STOCK_DELETE

// Blacklisted : STOCK_DIALOG_AUTHENTICATION

// Blacklisted : STOCK_DIALOG_ERROR

// Blacklisted : STOCK_DIALOG_INFO

// Blacklisted : STOCK_DIALOG_QUESTION

// Blacklisted : STOCK_DIALOG_WARNING

// Blacklisted : STOCK_DIRECTORY

// Blacklisted : STOCK_DISCARD

// Blacklisted : STOCK_DISCONNECT

// Blacklisted : STOCK_DND

// Blacklisted : STOCK_DND_MULTIPLE

// Blacklisted : STOCK_EDIT

// Blacklisted : STOCK_EXECUTE

// Blacklisted : STOCK_FILE

// Blacklisted : STOCK_FIND

// Blacklisted : STOCK_FIND_AND_REPLACE

// Blacklisted : STOCK_FLOPPY

// Blacklisted : STOCK_FULLSCREEN

// Blacklisted : STOCK_GOTO_BOTTOM

// Blacklisted : STOCK_GOTO_FIRST

// Blacklisted : STOCK_GOTO_LAST

// Blacklisted : STOCK_GOTO_TOP

// Blacklisted : STOCK_GO_BACK

// Blacklisted : STOCK_GO_DOWN

// Blacklisted : STOCK_GO_FORWARD

// Blacklisted : STOCK_GO_UP

// Blacklisted : STOCK_HARDDISK

// Blacklisted : STOCK_HELP

// Blacklisted : STOCK_HOME

// Blacklisted : STOCK_INDENT

// Blacklisted : STOCK_INDEX

// Blacklisted : STOCK_INFO

// Blacklisted : STOCK_ITALIC

// Blacklisted : STOCK_JUMP_TO

// Blacklisted : STOCK_JUSTIFY_CENTER

// Blacklisted : STOCK_JUSTIFY_FILL

// Blacklisted : STOCK_JUSTIFY_LEFT

// Blacklisted : STOCK_JUSTIFY_RIGHT

// Blacklisted : STOCK_LEAVE_FULLSCREEN

// Blacklisted : STOCK_MEDIA_FORWARD

// Blacklisted : STOCK_MEDIA_NEXT

// Blacklisted : STOCK_MEDIA_PAUSE

// Blacklisted : STOCK_MEDIA_PLAY

// Blacklisted : STOCK_MEDIA_PREVIOUS

// Blacklisted : STOCK_MEDIA_RECORD

// Blacklisted : STOCK_MEDIA_REWIND

// Blacklisted : STOCK_MEDIA_STOP

// Blacklisted : STOCK_MISSING_IMAGE

// Blacklisted : STOCK_NETWORK

// Blacklisted : STOCK_NEW

// Blacklisted : STOCK_NO

// Blacklisted : STOCK_OK

// Blacklisted : STOCK_OPEN

// Blacklisted : STOCK_ORIENTATION_LANDSCAPE

// Blacklisted : STOCK_ORIENTATION_PORTRAIT

// Blacklisted : STOCK_ORIENTATION_REVERSE_LANDSCAPE

// Blacklisted : STOCK_ORIENTATION_REVERSE_PORTRAIT

// Blacklisted : STOCK_PAGE_SETUP

// Blacklisted : STOCK_PASTE

// Blacklisted : STOCK_PREFERENCES

// Blacklisted : STOCK_PRINT

// Blacklisted : STOCK_PRINT_ERROR

// Blacklisted : STOCK_PRINT_PAUSED

// Blacklisted : STOCK_PRINT_PREVIEW

// Blacklisted : STOCK_PRINT_REPORT

// Blacklisted : STOCK_PRINT_WARNING

// Blacklisted : STOCK_PROPERTIES

// Blacklisted : STOCK_QUIT

// Blacklisted : STOCK_REDO

// Blacklisted : STOCK_REFRESH

// Blacklisted : STOCK_REMOVE

// Blacklisted : STOCK_REVERT_TO_SAVED

// Blacklisted : STOCK_SAVE

// Blacklisted : STOCK_SAVE_AS

// Blacklisted : STOCK_SELECT_ALL

// Blacklisted : STOCK_SELECT_COLOR

// Blacklisted : STOCK_SELECT_FONT

// Blacklisted : STOCK_SORT_ASCENDING

// Blacklisted : STOCK_SORT_DESCENDING

// Blacklisted : STOCK_SPELL_CHECK

// Blacklisted : STOCK_STOP

// Blacklisted : STOCK_STRIKETHROUGH

// Blacklisted : STOCK_UNDELETE

// Blacklisted : STOCK_UNDERLINE

// Blacklisted : STOCK_UNDO

// Blacklisted : STOCK_UNINDENT

// Blacklisted : STOCK_YES

// Blacklisted : STOCK_ZOOM_100

// Blacklisted : STOCK_ZOOM_FIT

// Blacklisted : STOCK_ZOOM_IN

// Blacklisted : STOCK_ZOOM_OUT

const STYLE_CLASS_ACCELERATOR string = C.GTK_STYLE_CLASS_ACCELERATOR
const STYLE_CLASS_ARROW string = C.GTK_STYLE_CLASS_ARROW
const STYLE_CLASS_BACKGROUND string = C.GTK_STYLE_CLASS_BACKGROUND
const STYLE_CLASS_BOTTOM string = C.GTK_STYLE_CLASS_BOTTOM
const STYLE_CLASS_BUTTON string = C.GTK_STYLE_CLASS_BUTTON
const STYLE_CLASS_CALENDAR string = C.GTK_STYLE_CLASS_CALENDAR
const STYLE_CLASS_CELL string = C.GTK_STYLE_CLASS_CELL
const STYLE_CLASS_CHECK string = C.GTK_STYLE_CLASS_CHECK
const STYLE_CLASS_COMBOBOX_ENTRY string = C.GTK_STYLE_CLASS_COMBOBOX_ENTRY
const STYLE_CLASS_CONTEXT_MENU string = C.GTK_STYLE_CLASS_CONTEXT_MENU
const STYLE_CLASS_CURSOR_HANDLE string = C.GTK_STYLE_CLASS_CURSOR_HANDLE
const STYLE_CLASS_DEFAULT string = C.GTK_STYLE_CLASS_DEFAULT
const STYLE_CLASS_DIM_LABEL string = C.GTK_STYLE_CLASS_DIM_LABEL
const STYLE_CLASS_DND string = C.GTK_STYLE_CLASS_DND
const STYLE_CLASS_DOCK string = C.GTK_STYLE_CLASS_DOCK
const STYLE_CLASS_ENTRY string = C.GTK_STYLE_CLASS_ENTRY
const STYLE_CLASS_ERROR string = C.GTK_STYLE_CLASS_ERROR
const STYLE_CLASS_EXPANDER string = C.GTK_STYLE_CLASS_EXPANDER
const STYLE_CLASS_FRAME string = C.GTK_STYLE_CLASS_FRAME
const STYLE_CLASS_GRIP string = C.GTK_STYLE_CLASS_GRIP
const STYLE_CLASS_HEADER string = C.GTK_STYLE_CLASS_HEADER
const STYLE_CLASS_HIGHLIGHT string = C.GTK_STYLE_CLASS_HIGHLIGHT
const STYLE_CLASS_HORIZONTAL string = C.GTK_STYLE_CLASS_HORIZONTAL
const STYLE_CLASS_IMAGE string = C.GTK_STYLE_CLASS_IMAGE
const STYLE_CLASS_INFO string = C.GTK_STYLE_CLASS_INFO
const STYLE_CLASS_INLINE_TOOLBAR string = C.GTK_STYLE_CLASS_INLINE_TOOLBAR
const STYLE_CLASS_INSERTION_CURSOR string = C.GTK_STYLE_CLASS_INSERTION_CURSOR
const STYLE_CLASS_LEFT string = C.GTK_STYLE_CLASS_LEFT
const STYLE_CLASS_LEVEL_BAR string = C.GTK_STYLE_CLASS_LEVEL_BAR
const STYLE_CLASS_LINKED string = C.GTK_STYLE_CLASS_LINKED
const STYLE_CLASS_LIST string = C.GTK_STYLE_CLASS_LIST
const STYLE_CLASS_LIST_ROW string = C.GTK_STYLE_CLASS_LIST_ROW
const STYLE_CLASS_MARK string = C.GTK_STYLE_CLASS_MARK
const STYLE_CLASS_MENU string = C.GTK_STYLE_CLASS_MENU
const STYLE_CLASS_MENUBAR string = C.GTK_STYLE_CLASS_MENUBAR
const STYLE_CLASS_MENUITEM string = C.GTK_STYLE_CLASS_MENUITEM
const STYLE_CLASS_NOTEBOOK string = C.GTK_STYLE_CLASS_NOTEBOOK
const STYLE_CLASS_OSD string = C.GTK_STYLE_CLASS_OSD
const STYLE_CLASS_PANE_SEPARATOR string = C.GTK_STYLE_CLASS_PANE_SEPARATOR
const STYLE_CLASS_PRIMARY_TOOLBAR string = C.GTK_STYLE_CLASS_PRIMARY_TOOLBAR
const STYLE_CLASS_PROGRESSBAR string = C.GTK_STYLE_CLASS_PROGRESSBAR
const STYLE_CLASS_PULSE string = C.GTK_STYLE_CLASS_PULSE
const STYLE_CLASS_QUESTION string = C.GTK_STYLE_CLASS_QUESTION
const STYLE_CLASS_RADIO string = C.GTK_STYLE_CLASS_RADIO
const STYLE_CLASS_RAISED string = C.GTK_STYLE_CLASS_RAISED
const STYLE_CLASS_READ_ONLY string = C.GTK_STYLE_CLASS_READ_ONLY
const STYLE_CLASS_RIGHT string = C.GTK_STYLE_CLASS_RIGHT
const STYLE_CLASS_RUBBERBAND string = C.GTK_STYLE_CLASS_RUBBERBAND
const STYLE_CLASS_SCALE string = C.GTK_STYLE_CLASS_SCALE
const STYLE_CLASS_SCALE_HAS_MARKS_ABOVE string = C.GTK_STYLE_CLASS_SCALE_HAS_MARKS_ABOVE
const STYLE_CLASS_SCALE_HAS_MARKS_BELOW string = C.GTK_STYLE_CLASS_SCALE_HAS_MARKS_BELOW
const STYLE_CLASS_SCROLLBAR string = C.GTK_STYLE_CLASS_SCROLLBAR
const STYLE_CLASS_SCROLLBARS_JUNCTION string = C.GTK_STYLE_CLASS_SCROLLBARS_JUNCTION
const STYLE_CLASS_SEPARATOR string = C.GTK_STYLE_CLASS_SEPARATOR
const STYLE_CLASS_SIDEBAR string = C.GTK_STYLE_CLASS_SIDEBAR
const STYLE_CLASS_SLIDER string = C.GTK_STYLE_CLASS_SLIDER
const STYLE_CLASS_SPINBUTTON string = C.GTK_STYLE_CLASS_SPINBUTTON
const STYLE_CLASS_SPINNER string = C.GTK_STYLE_CLASS_SPINNER
const STYLE_CLASS_TITLEBAR string = C.GTK_STYLE_CLASS_TITLEBAR
const STYLE_CLASS_TOOLBAR string = C.GTK_STYLE_CLASS_TOOLBAR
const STYLE_CLASS_TOOLTIP string = C.GTK_STYLE_CLASS_TOOLTIP
const STYLE_CLASS_TOP string = C.GTK_STYLE_CLASS_TOP
const STYLE_CLASS_TROUGH string = C.GTK_STYLE_CLASS_TROUGH
const STYLE_CLASS_VERTICAL string = C.GTK_STYLE_CLASS_VERTICAL
const STYLE_CLASS_VIEW string = C.GTK_STYLE_CLASS_VIEW
const STYLE_CLASS_WARNING string = C.GTK_STYLE_CLASS_WARNING
const STYLE_PROPERTY_BACKGROUND_COLOR string = C.GTK_STYLE_PROPERTY_BACKGROUND_COLOR
const STYLE_PROPERTY_BACKGROUND_IMAGE string = C.GTK_STYLE_PROPERTY_BACKGROUND_IMAGE
const STYLE_PROPERTY_BORDER_COLOR string = C.GTK_STYLE_PROPERTY_BORDER_COLOR
const STYLE_PROPERTY_BORDER_RADIUS string = C.GTK_STYLE_PROPERTY_BORDER_RADIUS
const STYLE_PROPERTY_BORDER_STYLE string = C.GTK_STYLE_PROPERTY_BORDER_STYLE
const STYLE_PROPERTY_BORDER_WIDTH string = C.GTK_STYLE_PROPERTY_BORDER_WIDTH
const STYLE_PROPERTY_COLOR string = C.GTK_STYLE_PROPERTY_COLOR
const STYLE_PROPERTY_FONT string = C.GTK_STYLE_PROPERTY_FONT
const STYLE_PROPERTY_MARGIN string = C.GTK_STYLE_PROPERTY_MARGIN
const STYLE_PROPERTY_PADDING string = C.GTK_STYLE_PROPERTY_PADDING
const STYLE_PROVIDER_PRIORITY_APPLICATION int = C.GTK_STYLE_PROVIDER_PRIORITY_APPLICATION
const STYLE_PROVIDER_PRIORITY_FALLBACK int = C.GTK_STYLE_PROVIDER_PRIORITY_FALLBACK
const STYLE_PROVIDER_PRIORITY_SETTINGS int = C.GTK_STYLE_PROVIDER_PRIORITY_SETTINGS
const STYLE_PROVIDER_PRIORITY_THEME int = C.GTK_STYLE_PROVIDER_PRIORITY_THEME
const STYLE_PROVIDER_PRIORITY_USER int = C.GTK_STYLE_PROVIDER_PRIORITY_USER
const STYLE_REGION_COLUMN string = C.GTK_STYLE_REGION_COLUMN
const STYLE_REGION_COLUMN_HEADER string = C.GTK_STYLE_REGION_COLUMN_HEADER
const STYLE_REGION_ROW string = C.GTK_STYLE_REGION_ROW
const STYLE_REGION_TAB string = C.GTK_STYLE_REGION_TAB
const TEXT_VIEW_PRIORITY_VALIDATE int = C.GTK_TEXT_VIEW_PRIORITY_VALIDATE
const TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID int = C.GTK_TREE_SORTABLE_DEFAULT_SORT_COLUMN_ID
const TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID int = C.GTK_TREE_SORTABLE_UNSORTED_SORT_COLUMN_ID
