// This is a generated file - DO NOT EDIT
// +build gtk_3.14 gtk_3.16 gtk_3.18 gtk_3.20 gtk_3.22 gtk_3.22.6 gtk_3.22.26 gtk_3.22.29

package gtk

import "C"

const STYLE_CLASS_CSD string = C.GTK_STYLE_CLASS_CSD
const STYLE_CLASS_FLAT string = C.GTK_STYLE_CLASS_FLAT
const STYLE_CLASS_MESSAGE_DIALOG string = C.GTK_STYLE_CLASS_MESSAGE_DIALOG
const STYLE_CLASS_OVERSHOOT string = C.GTK_STYLE_CLASS_OVERSHOOT
const STYLE_CLASS_POPOVER string = C.GTK_STYLE_CLASS_POPOVER
const STYLE_CLASS_POPUP string = C.GTK_STYLE_CLASS_POPUP
const STYLE_CLASS_SUBTITLE string = C.GTK_STYLE_CLASS_SUBTITLE
const STYLE_CLASS_TITLE string = C.GTK_STYLE_CLASS_TITLE
