// Code generated - DO NOT EDIT.

package gtk

// AccelGroupsActivate is a representation of the C type gtk_accel_groups_activate.
// AccelGroupsFromObject is a representation of the C type gtk_accel_groups_from_object.
// AcceleratorGetDefaultModMask is a representation of the C type gtk_accelerator_get_default_mod_mask.
// AcceleratorGetLabel is a representation of the C type gtk_accelerator_get_label.
// AcceleratorGetLabelWithKeycode is a representation of the C type gtk_accelerator_get_label_with_keycode.
// AcceleratorName is a representation of the C type gtk_accelerator_name.
// AcceleratorNameWithKeycode is a representation of the C type gtk_accelerator_name_with_keycode.
// AcceleratorParse is a representation of the C type gtk_accelerator_parse.
// AcceleratorParseWithKeycode is a representation of the C type gtk_accelerator_parse_with_keycode.
// AcceleratorSetDefaultModMask is a representation of the C type gtk_accelerator_set_default_mod_mask.
// AcceleratorValid is a representation of the C type gtk_accelerator_valid.
// AlternativeDialogButtonOrder is a representation of the C type gtk_alternative_dialog_button_order.
// BindingEntryAddSignalFromString is a representation of the C type gtk_binding_entry_add_signal_from_string.
// BindingEntryAddSignall is a representation of the C type gtk_binding_entry_add_signall.
// BindingEntryRemove is a representation of the C type gtk_binding_entry_remove.
// BindingEntrySkip is a representation of the C type gtk_binding_entry_skip.
// BindingSetByClass is a representation of the C type gtk_binding_set_by_class.
// BindingSetFind is a representation of the C type gtk_binding_set_find.
// BindingSetNew is a representation of the C type gtk_binding_set_new.
// BindingsActivate is a representation of the C type gtk_bindings_activate.
// BindingsActivateEvent is a representation of the C type gtk_bindings_activate_event.
// BuilderErrorQuark is a representation of the C type gtk_builder_error_quark.
// CairoShouldDrawWindow is a representation of the C type gtk_cairo_should_draw_window.
// CairoTransformToWindow is a representation of the C type gtk_cairo_transform_to_window.
// CheckVersion is a representation of the C type gtk_check_version.
// CssProviderErrorQuark is a representation of the C type gtk_css_provider_error_quark.
// DeviceGrabAdd is a representation of the C type gtk_device_grab_add.
// DeviceGrabRemove is a representation of the C type gtk_device_grab_remove.
// DisableSetlocale is a representation of the C type gtk_disable_setlocale.
// DistributeNaturalAllocation is a representation of the C type gtk_distribute_natural_allocation.
// DragCancel is a representation of the C type gtk_drag_cancel.
// DragFinish is a representation of the C type gtk_drag_finish.
// DragGetSourceWidget is a representation of the C type gtk_drag_get_source_widget.
// DragSetIconDefault is a representation of the C type gtk_drag_set_icon_default.
// DragSetIconGicon is a representation of the C type gtk_drag_set_icon_gicon.
// DragSetIconName is a representation of the C type gtk_drag_set_icon_name.
// DragSetIconPixbuf is a representation of the C type gtk_drag_set_icon_pixbuf.
// DragSetIconStock is a representation of the C type gtk_drag_set_icon_stock.
// DragSetIconSurface is a representation of the C type gtk_drag_set_icon_surface.
// DragSetIconWidget is a representation of the C type gtk_drag_set_icon_widget.
// DrawInsertionCursor is a representation of the C type gtk_draw_insertion_cursor.
// EventsPending is a representation of the C type gtk_events_pending.
// False is a representation of the C type gtk_false.
// FileChooserErrorQuark is a representation of the C type gtk_file_chooser_error_quark.
// GetBinaryAge is a representation of the C type gtk_get_binary_age.
// GetCurrentEvent is a representation of the C type gtk_get_current_event.
// GetCurrentEventDevice is a representation of the C type gtk_get_current_event_device.
// GetCurrentEventState is a representation of the C type gtk_get_current_event_state.
// GetCurrentEventTime is a representation of the C type gtk_get_current_event_time.
// GetDebugFlags is a representation of the C type gtk_get_debug_flags.
// GetDefaultLanguage is a representation of the C type gtk_get_default_language.
// GetEventWidget is a representation of the C type gtk_get_event_widget.
// GetInterfaceAge is a representation of the C type gtk_get_interface_age.
// GetLocaleDirection is a representation of the C type gtk_get_locale_direction.
// GetMajorVersion is a representation of the C type gtk_get_major_version.
// GetMicroVersion is a representation of the C type gtk_get_micro_version.
// GetMinorVersion is a representation of the C type gtk_get_minor_version.
// GetOptionGroup is a representation of the C type gtk_get_option_group.
// GrabGetCurrent is a representation of the C type gtk_grab_get_current.
// IconSizeFromName is a representation of the C type gtk_icon_size_from_name.
// IconSizeGetName is a representation of the C type gtk_icon_size_get_name.
// IconSizeLookup is a representation of the C type gtk_icon_size_lookup.
// IconSizeLookupForSettings is a representation of the C type gtk_icon_size_lookup_for_settings.
// IconSizeRegister is a representation of the C type gtk_icon_size_register.
// IconSizeRegisterAlias is a representation of the C type gtk_icon_size_register_alias.
// IconThemeErrorQuark is a representation of the C type gtk_icon_theme_error_quark.
// Init is a representation of the C type gtk_init.
// InitCheck is a representation of the C type gtk_init_check.
// InitWithArgs is a representation of the C type gtk_init_with_args.
// KeySnooperInstall is a representation of the C type gtk_key_snooper_install.
// KeySnooperRemove is a representation of the C type gtk_key_snooper_remove.
// Main is a representation of the C type gtk_main.
// MainDoEvent is a representation of the C type gtk_main_do_event.
// MainIteration is a representation of the C type gtk_main_iteration.
// MainIterationDo is a representation of the C type gtk_main_iteration_do.
// MainLevel is a representation of the C type gtk_main_level.
// MainQuit is a representation of the C type gtk_main_quit.
// PaintArrow is a representation of the C type gtk_paint_arrow.
// PaintBox is a representation of the C type gtk_paint_box.
// PaintBoxGap is a representation of the C type gtk_paint_box_gap.
// PaintCheck is a representation of the C type gtk_paint_check.
// PaintDiamond is a representation of the C type gtk_paint_diamond.
// PaintExpander is a representation of the C type gtk_paint_expander.
// PaintExtension is a representation of the C type gtk_paint_extension.
// PaintFlatBox is a representation of the C type gtk_paint_flat_box.
// PaintFocus is a representation of the C type gtk_paint_focus.
// PaintHandle is a representation of the C type gtk_paint_handle.
// PaintHline is a representation of the C type gtk_paint_hline.
// PaintLayout is a representation of the C type gtk_paint_layout.
// PaintOption is a representation of the C type gtk_paint_option.
// PaintResizeGrip is a representation of the C type gtk_paint_resize_grip.
// PaintShadow is a representation of the C type gtk_paint_shadow.
// PaintShadowGap is a representation of the C type gtk_paint_shadow_gap.
// PaintSlider is a representation of the C type gtk_paint_slider.
// PaintSpinner is a representation of the C type gtk_paint_spinner.
// PaintTab is a representation of the C type gtk_paint_tab.
// PaintVline is a representation of the C type gtk_paint_vline.
// PaperSizeGetDefault is a representation of the C type gtk_paper_size_get_default.
// PaperSizeGetPaperSizes is a representation of the C type gtk_paper_size_get_paper_sizes.
// ParseArgs is a representation of the C type gtk_parse_args.
// PrintErrorQuark is a representation of the C type gtk_print_error_quark.
// PrintRunPageSetupDialog is a representation of the C type gtk_print_run_page_setup_dialog.
// PrintRunPageSetupDialogAsync is a representation of the C type gtk_print_run_page_setup_dialog_async.
// PropagateEvent is a representation of the C type gtk_propagate_event.
// RcAddDefaultFile is a representation of the C type gtk_rc_add_default_file.
// RcFindModuleInPath is a representation of the C type gtk_rc_find_module_in_path.
// RcFindPixmapInPath is a representation of the C type gtk_rc_find_pixmap_in_path.
// RcGetDefaultFiles is a representation of the C type gtk_rc_get_default_files.
// RcGetImModuleFile is a representation of the C type gtk_rc_get_im_module_file.
// RcGetImModulePath is a representation of the C type gtk_rc_get_im_module_path.
// RcGetModuleDir is a representation of the C type gtk_rc_get_module_dir.
// RcGetStyle is a representation of the C type gtk_rc_get_style.
// RcGetStyleByPaths is a representation of the C type gtk_rc_get_style_by_paths.
// RcGetThemeDir is a representation of the C type gtk_rc_get_theme_dir.
// RcParse is a representation of the C type gtk_rc_parse.
// RcParseColor is a representation of the C type gtk_rc_parse_color.
// RcParseColorFull is a representation of the C type gtk_rc_parse_color_full.
// RcParsePriority is a representation of the C type gtk_rc_parse_priority.
// RcParseState is a representation of the C type gtk_rc_parse_state.
// RcParseString is a representation of the C type gtk_rc_parse_string.
// RcPropertyParseBorder is a representation of the C type gtk_rc_property_parse_border.
// RcPropertyParseColor is a representation of the C type gtk_rc_property_parse_color.
// RcPropertyParseEnum is a representation of the C type gtk_rc_property_parse_enum.
// RcPropertyParseFlags is a representation of the C type gtk_rc_property_parse_flags.
// RcPropertyParseRequisition is a representation of the C type gtk_rc_property_parse_requisition.
// RcReparseAll is a representation of the C type gtk_rc_reparse_all.
// RcReparseAllForSettings is a representation of the C type gtk_rc_reparse_all_for_settings.
// RcResetStyles is a representation of the C type gtk_rc_reset_styles.
// RcScannerNew is a representation of the C type gtk_rc_scanner_new.
// RcSetDefaultFiles is a representation of the C type gtk_rc_set_default_files.
// RecentChooserErrorQuark is a representation of the C type gtk_recent_chooser_error_quark.
// RecentManagerErrorQuark is a representation of the C type gtk_recent_manager_error_quark.
// RenderActivity is a representation of the C type gtk_render_activity.
// RenderArrow is a representation of the C type gtk_render_arrow.
// RenderBackground is a representation of the C type gtk_render_background.
// RenderBackgroundGetClip is a representation of the C type gtk_render_background_get_clip.
// RenderCheck is a representation of the C type gtk_render_check.
// RenderExpander is a representation of the C type gtk_render_expander.
// RenderExtension is a representation of the C type gtk_render_extension.
// RenderFocus is a representation of the C type gtk_render_focus.
// RenderFrame is a representation of the C type gtk_render_frame.
// RenderFrameGap is a representation of the C type gtk_render_frame_gap.
// RenderHandle is a representation of the C type gtk_render_handle.
// RenderIcon is a representation of the C type gtk_render_icon.
// RenderIconPixbuf is a representation of the C type gtk_render_icon_pixbuf.
// RenderIconSurface is a representation of the C type gtk_render_icon_surface.
// RenderInsertionCursor is a representation of the C type gtk_render_insertion_cursor.
// RenderLayout is a representation of the C type gtk_render_layout.
// RenderLine is a representation of the C type gtk_render_line.
// RenderOption is a representation of the C type gtk_render_option.
// RenderSlider is a representation of the C type gtk_render_slider.
// RgbToHsv is a representation of the C type gtk_rgb_to_hsv.
// SelectionAddTarget is a representation of the C type gtk_selection_add_target.
// SelectionAddTargets is a representation of the C type gtk_selection_add_targets.
// SelectionClearTargets is a representation of the C type gtk_selection_clear_targets.
// SelectionConvert is a representation of the C type gtk_selection_convert.
// SelectionOwnerSet is a representation of the C type gtk_selection_owner_set.
// SelectionOwnerSetForDisplay is a representation of the C type gtk_selection_owner_set_for_display.
// SelectionRemoveAll is a representation of the C type gtk_selection_remove_all.
// SetDebugFlags is a representation of the C type gtk_set_debug_flags.
// ShowAboutDialog is a representation of the C type gtk_show_about_dialog.
// ShowUri is a representation of the C type gtk_show_uri.
// ShowUriOnWindow is a representation of the C type gtk_show_uri_on_window.
// StockAdd is a representation of the C type gtk_stock_add.
// StockAddStatic is a representation of the C type gtk_stock_add_static.
// StockListIds is a representation of the C type gtk_stock_list_ids.
// StockLookup is a representation of the C type gtk_stock_lookup.
// StockSetTranslateFunc is a representation of the C type gtk_stock_set_translate_func.
// TargetTableFree is a representation of the C type gtk_target_table_free.
// TargetTableNewFromList is a representation of the C type gtk_target_table_new_from_list.
// TargetsIncludeImage is a representation of the C type gtk_targets_include_image.
// TargetsIncludeRichText is a representation of the C type gtk_targets_include_rich_text.
// TargetsIncludeText is a representation of the C type gtk_targets_include_text.
// TargetsIncludeUri is a representation of the C type gtk_targets_include_uri.
// TestCreateSimpleWindow is a representation of the C type gtk_test_create_simple_window.
// TestCreateWidget is a representation of the C type gtk_test_create_widget.
// TestDisplayButtonWindow is a representation of the C type gtk_test_display_button_window.
// TestFindLabel is a representation of the C type gtk_test_find_label.
// TestFindSibling is a representation of the C type gtk_test_find_sibling.
// TestFindWidget is a representation of the C type gtk_test_find_widget.
// TestInit is a representation of the C type gtk_test_init.
// TestListAllTypes is a representation of the C type gtk_test_list_all_types.
// TestRegisterAllTypes is a representation of the C type gtk_test_register_all_types.
// TestSliderGetValue is a representation of the C type gtk_test_slider_get_value.
// TestSliderSetPerc is a representation of the C type gtk_test_slider_set_perc.
// TestSpinButtonClick is a representation of the C type gtk_test_spin_button_click.
// TestTextGet is a representation of the C type gtk_test_text_get.
// TestTextSet is a representation of the C type gtk_test_text_set.
// TestWidgetClick is a representation of the C type gtk_test_widget_click.
// TestWidgetSendKey is a representation of the C type gtk_test_widget_send_key.
// TestWidgetWaitForDraw is a representation of the C type gtk_test_widget_wait_for_draw.
// TreeGetRowDragData is a representation of the C type gtk_tree_get_row_drag_data.
// TreeRowReferenceDeleted is a representation of the C type gtk_tree_row_reference_deleted.
// TreeRowReferenceInserted is a representation of the C type gtk_tree_row_reference_inserted.
// TreeRowReferenceReordered is a representation of the C type gtk_tree_row_reference_reordered.
// TreeSetRowDragData is a representation of the C type gtk_tree_set_row_drag_data.
// True is a representation of the C type gtk_true.
