// This is a generated file - DO NOT EDIT
// +build gio_2.22 gio_2.24 gio_2.26 gio_2.28 gio_2.30 gio_2.32 gio_2.34 gio_2.36 gio_2.38 gio_2.40 gio_2.42 gio_2.44 gio_2.46 gio_2.48 gio_2.50 gio_2.52 gio_2.54 gio_2.56

package gio

import "C"

const FILE_ATTRIBUTE_MOUNTABLE_CAN_POLL string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_POLL
const FILE_ATTRIBUTE_MOUNTABLE_CAN_START string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_START
const FILE_ATTRIBUTE_MOUNTABLE_CAN_START_DEGRADED string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_START_DEGRADED
const FILE_ATTRIBUTE_MOUNTABLE_CAN_STOP string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_STOP
const FILE_ATTRIBUTE_MOUNTABLE_IS_MEDIA_CHECK_AUTOMATIC string = C.G_FILE_ATTRIBUTE_MOUNTABLE_IS_MEDIA_CHECK_AUTOMATIC
const FILE_ATTRIBUTE_MOUNTABLE_START_STOP_TYPE string = C.G_FILE_ATTRIBUTE_MOUNTABLE_START_STOP_TYPE
const FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_FILE string = C.G_FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE_FILE
