// This is a generated file - DO NOT EDIT
// +build gio_2.32 gio_2.34 gio_2.36 gio_2.38 gio_2.40 gio_2.42 gio_2.44 gio_2.46 gio_2.48 gio_2.50 gio_2.52 gio_2.54 gio_2.56

package gio

import "C"

const FILE_ATTRIBUTE_FILESYSTEM_USED string = C.G_FILE_ATTRIBUTE_FILESYSTEM_USED
const MENU_ATTRIBUTE_ACTION string = C.G_MENU_ATTRIBUTE_ACTION
const MENU_ATTRIBUTE_LABEL string = C.G_MENU_ATTRIBUTE_LABEL
const MENU_ATTRIBUTE_TARGET string = C.G_MENU_ATTRIBUTE_TARGET
const MENU_LINK_SECTION string = C.G_MENU_LINK_SECTION
const MENU_LINK_SUBMENU string = C.G_MENU_LINK_SUBMENU
