// This is a generated file - DO NOT EDIT

package gio

// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <gio/gdesktopappinfo.h>
// #include <gio/gfiledescriptorbased.h>
// #include <gio/gio.h>
// #include <gio/gunixconnection.h>
// #include <gio/gunixcredentialsmessage.h>
// #include <gio/gunixfdlist.h>
// #include <gio/gunixfdmessage.h>
// #include <gio/gunixinputstream.h>
// #include <gio/gunixmounts.h>
// #include <gio/gunixoutputstream.h>
// #include <gio/gunixsocketaddress.h>
// #include <stdlib.h>
import "C"

const DESKTOP_APP_INFO_LOOKUP_EXTENSION_POINT_NAME string = C.G_DESKTOP_APP_INFO_LOOKUP_EXTENSION_POINT_NAME
const FILE_ATTRIBUTE_ACCESS_CAN_DELETE string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_DELETE
const FILE_ATTRIBUTE_ACCESS_CAN_EXECUTE string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_EXECUTE
const FILE_ATTRIBUTE_ACCESS_CAN_READ string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_READ
const FILE_ATTRIBUTE_ACCESS_CAN_RENAME string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_RENAME
const FILE_ATTRIBUTE_ACCESS_CAN_TRASH string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_TRASH
const FILE_ATTRIBUTE_ACCESS_CAN_WRITE string = C.G_FILE_ATTRIBUTE_ACCESS_CAN_WRITE
const FILE_ATTRIBUTE_DOS_IS_ARCHIVE string = C.G_FILE_ATTRIBUTE_DOS_IS_ARCHIVE
const FILE_ATTRIBUTE_DOS_IS_SYSTEM string = C.G_FILE_ATTRIBUTE_DOS_IS_SYSTEM
const FILE_ATTRIBUTE_ETAG_VALUE string = C.G_FILE_ATTRIBUTE_ETAG_VALUE
const FILE_ATTRIBUTE_FILESYSTEM_FREE string = C.G_FILE_ATTRIBUTE_FILESYSTEM_FREE
const FILE_ATTRIBUTE_FILESYSTEM_READONLY string = C.G_FILE_ATTRIBUTE_FILESYSTEM_READONLY

// Blacklisted : FILE_ATTRIBUTE_FILESYSTEM_REMOTE

const FILE_ATTRIBUTE_FILESYSTEM_SIZE string = C.G_FILE_ATTRIBUTE_FILESYSTEM_SIZE
const FILE_ATTRIBUTE_FILESYSTEM_TYPE string = C.G_FILE_ATTRIBUTE_FILESYSTEM_TYPE
const FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW string = C.G_FILE_ATTRIBUTE_FILESYSTEM_USE_PREVIEW
const FILE_ATTRIBUTE_GVFS_BACKEND string = C.G_FILE_ATTRIBUTE_GVFS_BACKEND
const FILE_ATTRIBUTE_ID_FILE string = C.G_FILE_ATTRIBUTE_ID_FILE
const FILE_ATTRIBUTE_ID_FILESYSTEM string = C.G_FILE_ATTRIBUTE_ID_FILESYSTEM
const FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT
const FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT
const FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT string = C.G_FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT
const FILE_ATTRIBUTE_MOUNTABLE_HAL_UDI string = C.G_FILE_ATTRIBUTE_MOUNTABLE_HAL_UDI
const FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE string = C.G_FILE_ATTRIBUTE_MOUNTABLE_UNIX_DEVICE
const FILE_ATTRIBUTE_OWNER_GROUP string = C.G_FILE_ATTRIBUTE_OWNER_GROUP
const FILE_ATTRIBUTE_OWNER_USER string = C.G_FILE_ATTRIBUTE_OWNER_USER
const FILE_ATTRIBUTE_OWNER_USER_REAL string = C.G_FILE_ATTRIBUTE_OWNER_USER_REAL
const FILE_ATTRIBUTE_SELINUX_CONTEXT string = C.G_FILE_ATTRIBUTE_SELINUX_CONTEXT
const FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE string = C.G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE
const FILE_ATTRIBUTE_STANDARD_COPY_NAME string = C.G_FILE_ATTRIBUTE_STANDARD_COPY_NAME
const FILE_ATTRIBUTE_STANDARD_DESCRIPTION string = C.G_FILE_ATTRIBUTE_STANDARD_DESCRIPTION
const FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME string = C.G_FILE_ATTRIBUTE_STANDARD_DISPLAY_NAME
const FILE_ATTRIBUTE_STANDARD_EDIT_NAME string = C.G_FILE_ATTRIBUTE_STANDARD_EDIT_NAME
const FILE_ATTRIBUTE_STANDARD_FAST_CONTENT_TYPE string = C.G_FILE_ATTRIBUTE_STANDARD_FAST_CONTENT_TYPE
const FILE_ATTRIBUTE_STANDARD_ICON string = C.G_FILE_ATTRIBUTE_STANDARD_ICON
const FILE_ATTRIBUTE_STANDARD_IS_BACKUP string = C.G_FILE_ATTRIBUTE_STANDARD_IS_BACKUP
const FILE_ATTRIBUTE_STANDARD_IS_HIDDEN string = C.G_FILE_ATTRIBUTE_STANDARD_IS_HIDDEN
const FILE_ATTRIBUTE_STANDARD_IS_SYMLINK string = C.G_FILE_ATTRIBUTE_STANDARD_IS_SYMLINK
const FILE_ATTRIBUTE_STANDARD_IS_VIRTUAL string = C.G_FILE_ATTRIBUTE_STANDARD_IS_VIRTUAL
const FILE_ATTRIBUTE_STANDARD_NAME string = C.G_FILE_ATTRIBUTE_STANDARD_NAME
const FILE_ATTRIBUTE_STANDARD_SIZE string = C.G_FILE_ATTRIBUTE_STANDARD_SIZE
const FILE_ATTRIBUTE_STANDARD_SORT_ORDER string = C.G_FILE_ATTRIBUTE_STANDARD_SORT_ORDER
const FILE_ATTRIBUTE_STANDARD_SYMLINK_TARGET string = C.G_FILE_ATTRIBUTE_STANDARD_SYMLINK_TARGET
const FILE_ATTRIBUTE_STANDARD_TARGET_URI string = C.G_FILE_ATTRIBUTE_STANDARD_TARGET_URI
const FILE_ATTRIBUTE_STANDARD_TYPE string = C.G_FILE_ATTRIBUTE_STANDARD_TYPE
const FILE_ATTRIBUTE_THUMBNAILING_FAILED string = C.G_FILE_ATTRIBUTE_THUMBNAILING_FAILED
const FILE_ATTRIBUTE_THUMBNAIL_PATH string = C.G_FILE_ATTRIBUTE_THUMBNAIL_PATH
const FILE_ATTRIBUTE_TIME_ACCESS string = C.G_FILE_ATTRIBUTE_TIME_ACCESS
const FILE_ATTRIBUTE_TIME_ACCESS_USEC string = C.G_FILE_ATTRIBUTE_TIME_ACCESS_USEC
const FILE_ATTRIBUTE_TIME_CHANGED string = C.G_FILE_ATTRIBUTE_TIME_CHANGED
const FILE_ATTRIBUTE_TIME_CHANGED_USEC string = C.G_FILE_ATTRIBUTE_TIME_CHANGED_USEC
const FILE_ATTRIBUTE_TIME_CREATED string = C.G_FILE_ATTRIBUTE_TIME_CREATED
const FILE_ATTRIBUTE_TIME_CREATED_USEC string = C.G_FILE_ATTRIBUTE_TIME_CREATED_USEC
const FILE_ATTRIBUTE_TIME_MODIFIED string = C.G_FILE_ATTRIBUTE_TIME_MODIFIED
const FILE_ATTRIBUTE_TIME_MODIFIED_USEC string = C.G_FILE_ATTRIBUTE_TIME_MODIFIED_USEC
const FILE_ATTRIBUTE_TRASH_ITEM_COUNT string = C.G_FILE_ATTRIBUTE_TRASH_ITEM_COUNT
const FILE_ATTRIBUTE_UNIX_BLOCKS string = C.G_FILE_ATTRIBUTE_UNIX_BLOCKS
const FILE_ATTRIBUTE_UNIX_BLOCK_SIZE string = C.G_FILE_ATTRIBUTE_UNIX_BLOCK_SIZE
const FILE_ATTRIBUTE_UNIX_DEVICE string = C.G_FILE_ATTRIBUTE_UNIX_DEVICE
const FILE_ATTRIBUTE_UNIX_GID string = C.G_FILE_ATTRIBUTE_UNIX_GID
const FILE_ATTRIBUTE_UNIX_INODE string = C.G_FILE_ATTRIBUTE_UNIX_INODE
const FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT string = C.G_FILE_ATTRIBUTE_UNIX_IS_MOUNTPOINT
const FILE_ATTRIBUTE_UNIX_MODE string = C.G_FILE_ATTRIBUTE_UNIX_MODE
const FILE_ATTRIBUTE_UNIX_NLINK string = C.G_FILE_ATTRIBUTE_UNIX_NLINK
const FILE_ATTRIBUTE_UNIX_RDEV string = C.G_FILE_ATTRIBUTE_UNIX_RDEV
const FILE_ATTRIBUTE_UNIX_UID string = C.G_FILE_ATTRIBUTE_UNIX_UID
const NATIVE_VOLUME_MONITOR_EXTENSION_POINT_NAME string = C.G_NATIVE_VOLUME_MONITOR_EXTENSION_POINT_NAME
const PROXY_RESOLVER_EXTENSION_POINT_NAME string = C.G_PROXY_RESOLVER_EXTENSION_POINT_NAME

// Blacklisted : SETTINGS_BACKEND_EXTENSION_POINT_NAME

const TLS_BACKEND_EXTENSION_POINT_NAME string = C.G_TLS_BACKEND_EXTENSION_POINT_NAME
const TLS_DATABASE_PURPOSE_AUTHENTICATE_CLIENT string = C.G_TLS_DATABASE_PURPOSE_AUTHENTICATE_CLIENT
const TLS_DATABASE_PURPOSE_AUTHENTICATE_SERVER string = C.G_TLS_DATABASE_PURPOSE_AUTHENTICATE_SERVER
const VFS_EXTENSION_POINT_NAME string = C.G_VFS_EXTENSION_POINT_NAME
const VOLUME_IDENTIFIER_KIND_CLASS string = C.G_VOLUME_IDENTIFIER_KIND_CLASS
const VOLUME_IDENTIFIER_KIND_HAL_UDI string = C.G_VOLUME_IDENTIFIER_KIND_HAL_UDI
const VOLUME_IDENTIFIER_KIND_LABEL string = C.G_VOLUME_IDENTIFIER_KIND_LABEL
const VOLUME_IDENTIFIER_KIND_NFS_MOUNT string = C.G_VOLUME_IDENTIFIER_KIND_NFS_MOUNT
const VOLUME_IDENTIFIER_KIND_UNIX_DEVICE string = C.G_VOLUME_IDENTIFIER_KIND_UNIX_DEVICE
const VOLUME_IDENTIFIER_KIND_UUID string = C.G_VOLUME_IDENTIFIER_KIND_UUID
const VOLUME_MONITOR_EXTENSION_POINT_NAME string = C.G_VOLUME_MONITOR_EXTENSION_POINT_NAME
