// Code generated - DO NOT EDIT.

package gio

// ActionNameIsValid is a representation of the C type g_action_name_is_valid.
// ActionParseDetailedName is a representation of the C type g_action_parse_detailed_name.
// ActionPrintDetailedName is a representation of the C type g_action_print_detailed_name.
// AppInfoCreateFromCommandline is a representation of the C type g_app_info_create_from_commandline.
// AppInfoGetAll is a representation of the C type g_app_info_get_all.
// AppInfoGetAllForType is a representation of the C type g_app_info_get_all_for_type.
// AppInfoGetDefaultForType is a representation of the C type g_app_info_get_default_for_type.
// AppInfoGetDefaultForUriScheme is a representation of the C type g_app_info_get_default_for_uri_scheme.
// AppInfoGetFallbackForType is a representation of the C type g_app_info_get_fallback_for_type.
// AppInfoGetRecommendedForType is a representation of the C type g_app_info_get_recommended_for_type.
// AppInfoLaunchDefaultForUri is a representation of the C type g_app_info_launch_default_for_uri.
// AppInfoLaunchDefaultForUriAsync is a representation of the C type g_app_info_launch_default_for_uri_async.
// AppInfoLaunchDefaultForUriFinish is a representation of the C type g_app_info_launch_default_for_uri_finish.
// AppInfoResetTypeAssociations is a representation of the C type g_app_info_reset_type_associations.
// AsyncInitableNewvAsync is a representation of the C type g_async_initable_newv_async.
// BusGet is a representation of the C type g_bus_get.
// BusGetFinish is a representation of the C type g_bus_get_finish.
// BusGetSync is a representation of the C type g_bus_get_sync.
// BusOwnName is a representation of the C type g_bus_own_name.
// BusOwnNameOnConnection is a representation of the C type g_bus_own_name_on_connection.
// BusOwnNameOnConnectionWithClosures is a representation of the C type g_bus_own_name_on_connection_with_closures.
// BusOwnNameWithClosures is a representation of the C type g_bus_own_name_with_closures.
// BusUnownName is a representation of the C type g_bus_unown_name.
// BusUnwatchName is a representation of the C type g_bus_unwatch_name.
// BusWatchName is a representation of the C type g_bus_watch_name.
// BusWatchNameOnConnection is a representation of the C type g_bus_watch_name_on_connection.
// BusWatchNameOnConnectionWithClosures is a representation of the C type g_bus_watch_name_on_connection_with_closures.
// BusWatchNameWithClosures is a representation of the C type g_bus_watch_name_with_closures.
// ContentTypeCanBeExecutable is a representation of the C type g_content_type_can_be_executable.
// ContentTypeEquals is a representation of the C type g_content_type_equals.
// ContentTypeFromMimeType is a representation of the C type g_content_type_from_mime_type.
// ContentTypeGetDescription is a representation of the C type g_content_type_get_description.
// ContentTypeGetGenericIconName is a representation of the C type g_content_type_get_generic_icon_name.
// ContentTypeGetIcon is a representation of the C type g_content_type_get_icon.
// ContentTypeGetMimeType is a representation of the C type g_content_type_get_mime_type.
// ContentTypeGetSymbolicIcon is a representation of the C type g_content_type_get_symbolic_icon.
// ContentTypeGuess is a representation of the C type g_content_type_guess.
// ContentTypeGuessForTree is a representation of the C type g_content_type_guess_for_tree.
// ContentTypeIsA is a representation of the C type g_content_type_is_a.
// ContentTypeIsMimeType is a representation of the C type g_content_type_is_mime_type.
// ContentTypeIsUnknown is a representation of the C type g_content_type_is_unknown.
// ContentTypesGetRegistered is a representation of the C type g_content_types_get_registered.
// DbusAddressEscapeValue is a representation of the C type g_dbus_address_escape_value.
// DbusAddressGetForBusSync is a representation of the C type g_dbus_address_get_for_bus_sync.
// DbusAddressGetStream is a representation of the C type g_dbus_address_get_stream.
// DbusAddressGetStreamFinish is a representation of the C type g_dbus_address_get_stream_finish.
// DbusAddressGetStreamSync is a representation of the C type g_dbus_address_get_stream_sync.
// DbusAnnotationInfoLookup is a representation of the C type g_dbus_annotation_info_lookup.
// DbusErrorEncodeGerror is a representation of the C type g_dbus_error_encode_gerror.
// DbusErrorGetRemoteError is a representation of the C type g_dbus_error_get_remote_error.
// DbusErrorIsRemoteError is a representation of the C type g_dbus_error_is_remote_error.
// DbusErrorNewForDbusError is a representation of the C type g_dbus_error_new_for_dbus_error.
// DbusErrorQuark is a representation of the C type g_dbus_error_quark.
// DbusErrorRegisterError is a representation of the C type g_dbus_error_register_error.
// DbusErrorRegisterErrorDomain is a representation of the C type g_dbus_error_register_error_domain.
// DbusErrorStripRemoteError is a representation of the C type g_dbus_error_strip_remote_error.
// DbusErrorUnregisterError is a representation of the C type g_dbus_error_unregister_error.
// DbusGenerateGuid is a representation of the C type g_dbus_generate_guid.
// DbusGvalueToGvariant is a representation of the C type g_dbus_gvalue_to_gvariant.
// DbusGvariantToGvalue is a representation of the C type g_dbus_gvariant_to_gvalue.
// DbusIsAddress is a representation of the C type g_dbus_is_address.
// DbusIsGuid is a representation of the C type g_dbus_is_guid.
// DbusIsInterfaceName is a representation of the C type g_dbus_is_interface_name.
// DbusIsMemberName is a representation of the C type g_dbus_is_member_name.
// DbusIsName is a representation of the C type g_dbus_is_name.
// DbusIsSupportedAddress is a representation of the C type g_dbus_is_supported_address.
// DbusIsUniqueName is a representation of the C type g_dbus_is_unique_name.
// DtlsClientConnectionNew is a representation of the C type g_dtls_client_connection_new.
// DtlsServerConnectionNew is a representation of the C type g_dtls_server_connection_new.
// FileNewForCommandlineArg is a representation of the C type g_file_new_for_commandline_arg.
// FileNewForCommandlineArgAndCwd is a representation of the C type g_file_new_for_commandline_arg_and_cwd.
// FileNewForPath is a representation of the C type g_file_new_for_path.
// FileNewForUri is a representation of the C type g_file_new_for_uri.
// FileNewTmp is a representation of the C type g_file_new_tmp.
// FileParseName is a representation of the C type g_file_parse_name.
// IconDeserialize is a representation of the C type g_icon_deserialize.
// IconHash is a representation of the C type g_icon_hash.
// IconNewForString is a representation of the C type g_icon_new_for_string.
// InitableNewv is a representation of the C type g_initable_newv.
// IoErrorFromErrno is a representation of the C type g_io_error_from_errno.
// IoErrorQuark is a representation of the C type g_io_error_quark.
// IoExtensionPointImplement is a representation of the C type g_io_extension_point_implement.
// IoExtensionPointLookup is a representation of the C type g_io_extension_point_lookup.
// IoExtensionPointRegister is a representation of the C type g_io_extension_point_register.
// IoModulesLoadAllInDirectory is a representation of the C type g_io_modules_load_all_in_directory.
// IoModulesLoadAllInDirectoryWithScope is a representation of the C type g_io_modules_load_all_in_directory_with_scope.
// IoModulesScanAllInDirectory is a representation of the C type g_io_modules_scan_all_in_directory.
// IoModulesScanAllInDirectoryWithScope is a representation of the C type g_io_modules_scan_all_in_directory_with_scope.
// IoSchedulerCancelAllJobs is a representation of the C type g_io_scheduler_cancel_all_jobs.
// IoSchedulerPushJob is a representation of the C type g_io_scheduler_push_job.
// KeyfileSettingsBackendNew is a representation of the C type g_keyfile_settings_backend_new.
// MemorySettingsBackendNew is a representation of the C type g_memory_settings_backend_new.
// NetworkMonitorGetDefault is a representation of the C type g_network_monitor_get_default.
// NetworkingInit is a representation of the C type g_networking_init.
// NullSettingsBackendNew is a representation of the C type g_null_settings_backend_new.
// PollableSourceNew is a representation of the C type g_pollable_source_new.
// PollableSourceNewFull is a representation of the C type g_pollable_source_new_full.
// PollableStreamRead is a representation of the C type g_pollable_stream_read.
// PollableStreamWrite is a representation of the C type g_pollable_stream_write.
// PollableStreamWriteAll is a representation of the C type g_pollable_stream_write_all.
// ProxyGetDefaultForProtocol is a representation of the C type g_proxy_get_default_for_protocol.
// ProxyResolverGetDefault is a representation of the C type g_proxy_resolver_get_default.
// ResolverErrorQuark is a representation of the C type g_resolver_error_quark.
// ResourceErrorQuark is a representation of the C type g_resource_error_quark.
// ResourceLoad is a representation of the C type g_resource_load.
// ResourcesEnumerateChildren is a representation of the C type g_resources_enumerate_children.
// ResourcesGetInfo is a representation of the C type g_resources_get_info.
// ResourcesLookupData is a representation of the C type g_resources_lookup_data.
// ResourcesOpenStream is a representation of the C type g_resources_open_stream.
// ResourcesRegister is a representation of the C type g_resources_register.
// ResourcesUnregister is a representation of the C type g_resources_unregister.
// SettingsSchemaSourceGetDefault is a representation of the C type g_settings_schema_source_get_default.
// SimpleAsyncReportErrorInIdle is a representation of the C type g_simple_async_report_error_in_idle.
// SimpleAsyncReportGerrorInIdle is a representation of the C type g_simple_async_report_gerror_in_idle.
// SimpleAsyncReportTakeGerrorInIdle is a representation of the C type g_simple_async_report_take_gerror_in_idle.
// SrvTargetListSort is a representation of the C type g_srv_target_list_sort.
// TlsBackendGetDefault is a representation of the C type g_tls_backend_get_default.
// TlsClientConnectionNew is a representation of the C type g_tls_client_connection_new.
// TlsErrorQuark is a representation of the C type g_tls_error_quark.
// TlsFileDatabaseNew is a representation of the C type g_tls_file_database_new.
// TlsServerConnectionNew is a representation of the C type g_tls_server_connection_new.
// UnixIsMountPathSystemInternal is a representation of the C type g_unix_is_mount_path_system_internal.
// UnixIsSystemDevicePath is a representation of the C type g_unix_is_system_device_path.
// UnixIsSystemFsType is a representation of the C type g_unix_is_system_fs_type.
// UnixMountAt is a representation of the C type g_unix_mount_at.
// UnixMountCompare is a representation of the C type g_unix_mount_compare.
// UnixMountCopy is a representation of the C type g_unix_mount_copy.
// UnixMountFor is a representation of the C type g_unix_mount_for.
// UnixMountFree is a representation of the C type g_unix_mount_free.
// UnixMountGetDevicePath is a representation of the C type g_unix_mount_get_device_path.
// UnixMountGetFsType is a representation of the C type g_unix_mount_get_fs_type.
// UnixMountGetMountPath is a representation of the C type g_unix_mount_get_mount_path.
// UnixMountGuessCanEject is a representation of the C type g_unix_mount_guess_can_eject.
// UnixMountGuessIcon is a representation of the C type g_unix_mount_guess_icon.
// UnixMountGuessName is a representation of the C type g_unix_mount_guess_name.
// UnixMountGuessShouldDisplay is a representation of the C type g_unix_mount_guess_should_display.
// UnixMountGuessSymbolicIcon is a representation of the C type g_unix_mount_guess_symbolic_icon.
// UnixMountIsReadonly is a representation of the C type g_unix_mount_is_readonly.
// UnixMountIsSystemInternal is a representation of the C type g_unix_mount_is_system_internal.
// UnixMountPointsChangedSince is a representation of the C type g_unix_mount_points_changed_since.
// UnixMountPointsGet is a representation of the C type g_unix_mount_points_get.
// UnixMountsChangedSince is a representation of the C type g_unix_mounts_changed_since.
// UnixMountsGet is a representation of the C type g_unix_mounts_get.
