// Code generated - DO NOT EDIT.
// +build glib_2.14

package glib

// #include <glib.h>
import "C"

// bitfields
type AsciiType C.GAsciiType
type FileTest C.GFileTest
type FormatSizeFlags C.GFormatSizeFlags
type HookFlagMask C.GHookFlagMask
type IOCondition C.GIOCondition
type IOFlags C.GIOFlags
type KeyFileFlags C.GKeyFileFlags
type LogLevelFlags C.GLogLevelFlags
type MarkupCollectType C.GMarkupCollectType
type MarkupParseFlags C.GMarkupParseFlags
type OptionFlags C.GOptionFlags
type RegexCompileFlags C.GRegexCompileFlags
type RegexMatchFlags C.GRegexMatchFlags
type SpawnFlags C.GSpawnFlags
type TestSubprocessFlags C.GTestSubprocessFlags
type TestTrapFlags C.GTestTrapFlags
type TraverseFlags C.GTraverseFlags

// enumerations
type BookmarkFileError C.GBookmarkFileError
type ConvertError C.GConvertError
type DateDMY C.GDateDMY
type DateMonth C.GDateMonth
type DateWeekday C.GDateWeekday
type ErrorType C.GErrorType
type FileError C.GFileError
type IOChannelError C.GIOChannelError
type IOError C.GIOError
type IOStatus C.GIOStatus
type KeyFileError C.GKeyFileError
type MarkupError C.GMarkupError
type NormalizeMode C.GNormalizeMode
type OnceStatus C.GOnceStatus
type OptionArg C.GOptionArg
type OptionError C.GOptionError
type RegexError C.GRegexError
type SeekType C.GSeekType
type ShellError C.GShellError
type SliceConfig C.GSliceConfig
type SpawnError C.GSpawnError
type TestLogType C.GTestLogType
type ThreadError C.GThreadError
type TimeType C.GTimeType
type TokenType C.GTokenType
type TraverseType C.GTraverseType
type UnicodeBreakType C.GUnicodeBreakType
type UnicodeScript C.GUnicodeScript
type UnicodeType C.GUnicodeType
type UserDirectory C.GUserDirectory
type VariantParseError C.GVariantParseError

// records
type Array C.GArray
type AsyncQueue C.GAsyncQueue
type BookmarkFile C.GBookmarkFile
type ByteArray C.GByteArray
type Cond C.GCond
type Data C.GData
type Date C.GDate
type DebugKey C.GDebugKey
type Dir C.GDir
type Error C.GError
type HashTable C.GHashTable
type HashTableIter C.GHashTableIter
type Hook C.GHook
type HookList C.GHookList
type IConv C.GIConv
type IOChannel C.GIOChannel
type IOFuncs C.GIOFuncs
type KeyFile C.GKeyFile
type List C.GList
type MainContext C.GMainContext
type MainLoop C.GMainLoop
type MappedFile C.GMappedFile
type MarkupParseContext C.GMarkupParseContext
type MarkupParser C.GMarkupParser
type MatchInfo C.GMatchInfo
type MemVTable C.GMemVTable
type Node C.GNode
type Once C.GOnce
type OptionContext C.GOptionContext
type OptionEntry C.GOptionEntry
type OptionGroup C.GOptionGroup
type PatternSpec C.GPatternSpec
type PollFD C.GPollFD
type Private C.GPrivate
type PtrArray C.GPtrArray
type Queue C.GQueue
type Rand C.GRand
type Regex C.GRegex
type SList C.GSList
type Scanner C.GScanner
type ScannerConfig C.GScannerConfig
type Sequence C.GSequence
type SequenceIter C.GSequenceIter
type Source C.GSource
type SourceCallbackFuncs C.GSourceCallbackFuncs
type SourceFuncs C.GSourceFuncs
type SourcePrivate C.GSourcePrivate
type StatBuf C.GStatBuf
type String C.GString
type StringChunk C.GStringChunk
type TestCase C.GTestCase
type TestConfig C.GTestConfig
type TestLogBuffer C.GTestLogBuffer
type TestSuite C.GTestSuite
type Thread C.GThread
type ThreadPool C.GThreadPool
type TimeVal C.GTimeVal
type Timer C.GTimer
type TrashStack C.GTrashStack
type Tree C.GTree
type VariantBuilder C.GVariantBuilder
type VariantIter C.GVariantIter
type VariantType C.GVariantType

// classes

// interfaces

// functions
func Fn_access()                                 {}
func Fn_ascii_digit_value()                      {}
func Fn_ascii_dtostr()                           {}
func Fn_ascii_formatd()                          {}
func Fn_ascii_strcasecmp()                       {}
func Fn_ascii_strdown()                          {}
func Fn_ascii_strncasecmp()                      {}
func Fn_ascii_strtod()                           {}
func Fn_ascii_strtoll()                          {}
func Fn_ascii_strtoull()                         {}
func Fn_ascii_strup()                            {}
func Fn_ascii_tolower()                          {}
func Fn_ascii_toupper()                          {}
func Fn_ascii_xdigit_value()                     {}
func Fn_assert_warning()                         {}
func Fn_assertion_message()                      {}
func Fn_assertion_message_cmpnum()               {}
func Fn_assertion_message_cmpstr()               {}
func Fn_assertion_message_error()                {}
func Fn_assertion_message_expr()                 {}
func Fn_atexit()                                 {}
func Fn_atomic_int_add()                         {}
func Fn_atomic_int_compare_and_exchange()        {}
func Fn_atomic_int_dec_and_test()                {}
func Fn_atomic_int_exchange_and_add()            {}
func Fn_atomic_int_get()                         {}
func Fn_atomic_int_inc()                         {}
func Fn_atomic_int_set()                         {}
func Fn_atomic_pointer_compare_and_exchange()    {}
func Fn_atomic_pointer_get()                     {}
func Fn_atomic_pointer_set()                     {}
func Fn_base64_decode()                          {}
func Fn_base64_decode_step()                     {}
func Fn_base64_encode()                          {}
func Fn_base64_encode_close()                    {}
func Fn_base64_encode_step()                     {}
func Fn_basename()                               {}
func Fn_bit_nth_lsf()                            {}
func Fn_bit_nth_msf()                            {}
func Fn_bit_storage()                            {}
func Fn_bookmark_file_error_quark()              {}
func Fn_build_filename()                         {}
func Fn_build_filenamev()                        {}
func Fn_build_path()                             {}
func Fn_build_pathv()                            {}
func Fn_byte_array_free()                        {}
func Fn_byte_array_new()                         {}
func Fn_chdir()                                  {}
func Fn_check_version()                          {}
func Fn_child_watch_add()                        {}
func Fn_child_watch_add_full()                   {}
func Fn_child_watch_source_new()                 {}
func Fn_clear_error()                            {}
func Fn_convert()                                {}
func Fn_convert_error_quark()                    {}
func Fn_convert_with_fallback()                  {}
func Fn_convert_with_iconv()                     {}
func Fn_datalist_clear()                         {}
func Fn_datalist_foreach()                       {}
func Fn_datalist_get_data()                      {}
func Fn_datalist_get_flags()                     {}
func Fn_datalist_id_get_data()                   {}
func Fn_datalist_id_remove_no_notify()           {}
func Fn_datalist_id_set_data_full()              {}
func Fn_datalist_init()                          {}
func Fn_datalist_set_flags()                     {}
func Fn_datalist_unset_flags()                   {}
func Fn_dataset_destroy()                        {}
func Fn_dataset_foreach()                        {}
func Fn_dataset_id_get_data()                    {}
func Fn_dataset_id_remove_no_notify()            {}
func Fn_dataset_id_set_data_full()               {}
func Fn_date_get_days_in_month()                 {}
func Fn_date_get_monday_weeks_in_year()          {}
func Fn_date_get_sunday_weeks_in_year()          {}
func Fn_date_is_leap_year()                      {}
func Fn_date_strftime()                          {}
func Fn_date_valid_day()                         {}
func Fn_date_valid_dmy()                         {}
func Fn_date_valid_julian()                      {}
func Fn_date_valid_month()                       {}
func Fn_date_valid_weekday()                     {}
func Fn_date_valid_year()                        {}
func Fn_direct_equal()                           {}
func Fn_direct_hash()                            {}
func Fn_file_error_from_errno()                  {}
func Fn_file_error_quark()                       {}
func Fn_file_get_contents()                      {}
func Fn_file_open_tmp()                          {}
func Fn_file_read_link()                         {}
func Fn_file_set_contents()                      {}
func Fn_file_test()                              {}
func Fn_filename_display_basename()              {}
func Fn_filename_display_name()                  {}
func Fn_filename_from_uri()                      {}
func Fn_filename_from_utf8()                     {}
func Fn_filename_to_uri()                        {}
func Fn_filename_to_utf8()                       {}
func Fn_find_program_in_path()                   {}
func Fn_fprintf()                                {}
func Fn_free()                                   {}
func Fn_get_application_name()                   {}
func Fn_get_charset()                            {}
func Fn_get_codeset()                            {}
func Fn_get_current_dir()                        {}
func Fn_get_current_time()                       {}
func Fn_get_filename_charsets()                  {}
func Fn_get_home_dir()                           {}
func Fn_get_host_name()                          {}
func Fn_get_language_names()                     {}
func Fn_get_prgname()                            {}
func Fn_get_real_name()                          {}
func Fn_get_system_config_dirs()                 {}
func Fn_get_system_data_dirs()                   {}
func Fn_get_tmp_dir()                            {}
func Fn_get_user_cache_dir()                     {}
func Fn_get_user_config_dir()                    {}
func Fn_get_user_data_dir()                      {}
func Fn_get_user_name()                          {}
func Fn_get_user_special_dir()                   {}
func Fn_getenv()                                 {}
func Fn_hash_table_destroy()                     {}
func Fn_hash_table_insert()                      {}
func Fn_hash_table_lookup()                      {}
func Fn_hash_table_lookup_extended()             {}
func Fn_hash_table_remove()                      {}
func Fn_hash_table_remove_all()                  {}
func Fn_hash_table_replace()                     {}
func Fn_hash_table_size()                        {}
func Fn_hash_table_steal()                       {}
func Fn_hash_table_steal_all()                   {}
func Fn_hash_table_unref()                       {}
func Fn_hook_destroy()                           {}
func Fn_hook_destroy_link()                      {}
func Fn_hook_free()                              {}
func Fn_hook_insert_before()                     {}
func Fn_hook_prepend()                           {}
func Fn_hook_unref()                             {}
func Fn_iconv()                                  {}
func Fn_iconv_open()                             {}
func Fn_idle_add()                               {}
func Fn_idle_add_full()                          {}
func Fn_idle_remove_by_data()                    {}
func Fn_idle_source_new()                        {}
func Fn_int_equal()                              {}
func Fn_int_hash()                               {}
func Fn_intern_static_string()                   {}
func Fn_intern_string()                          {}
func Fn_io_add_watch()                           {}
func Fn_io_add_watch_full()                      {}
func Fn_io_channel_error_from_errno()            {}
func Fn_io_channel_error_quark()                 {}
func Fn_io_create_watch()                        {}
func Fn_key_file_error_quark()                   {}
func Fn_listenv()                                {}
func Fn_locale_from_utf8()                       {}
func Fn_locale_to_utf8()                         {}
func Fn_log()                                    {}
func Fn_log_default_handler()                    {}
func Fn_log_remove_handler()                     {}
func Fn_log_set_always_fatal()                   {}
func Fn_log_set_default_handler()                {}
func Fn_log_set_fatal_mask()                     {}
func Fn_log_set_handler()                        {}
func Fn_log_structured_standard()                {}
func Fn_logv()                                   {}
func Fn_main_context_default()                   {}
func Fn_main_current_source()                    {}
func Fn_main_depth()                             {}
func Fn_malloc()                                 {}
func Fn_malloc0()                                {}
func Fn_markup_error_quark()                     {}
func Fn_markup_escape_text()                     {}
func Fn_markup_printf_escaped()                  {}
func Fn_markup_vprintf_escaped()                 {}
func Fn_mem_is_system_malloc()                   {}
func Fn_mem_profile()                            {}
func Fn_mem_set_vtable()                         {}
func Fn_memdup()                                 {}
func Fn_mkdir_with_parents()                     {}
func Fn_mkstemp()                                {}
func Fn_nullify_pointer()                        {}
func Fn_number_parser_error_quark()              {}
func Fn_on_error_query()                         {}
func Fn_on_error_stack_trace()                   {}
func Fn_once_init_enter()                        {}
func Fn_once_init_leave()                        {}
func Fn_option_error_quark()                     {}
func Fn_parse_debug_string()                     {}
func Fn_path_get_basename()                      {}
func Fn_path_get_dirname()                       {}
func Fn_path_is_absolute()                       {}
func Fn_path_skip_root()                         {}
func Fn_pattern_match()                          {}
func Fn_pattern_match_simple()                   {}
func Fn_pattern_match_string()                   {}
func Fn_print()                                  {}
func Fn_printerr()                               {}
func Fn_printf()                                 {}
func Fn_printf_string_upper_bound()              {}
func Fn_propagate_error()                        {}
func Fn_qsort_with_data()                        {}
func Fn_quark_from_static_string()               {}
func Fn_quark_from_string()                      {}
func Fn_quark_to_string()                        {}
func Fn_quark_try_string()                       {}
func Fn_random_double()                          {}
func Fn_random_double_range()                    {}
func Fn_random_int()                             {}
func Fn_random_int_range()                       {}
func Fn_random_set_seed()                        {}
func Fn_realloc()                                {}
func Fn_regex_check_replacement()                {}
func Fn_regex_error_quark()                      {}
func Fn_regex_escape_string()                    {}
func Fn_regex_match_simple()                     {}
func Fn_regex_split_simple()                     {}
func Fn_return_if_fail_warning()                 {}
func Fn_rmdir()                                  {}
func Fn_sequence_get()                           {}
func Fn_sequence_insert_before()                 {}
func Fn_sequence_move()                          {}
func Fn_sequence_move_range()                    {}
func Fn_sequence_range_get_midpoint()            {}
func Fn_sequence_remove()                        {}
func Fn_sequence_remove_range()                  {}
func Fn_sequence_set()                           {}
func Fn_sequence_swap()                          {}
func Fn_set_application_name()                   {}
func Fn_set_error()                              {}
func Fn_set_prgname()                            {}
func Fn_set_print_handler()                      {}
func Fn_set_printerr_handler()                   {}
func Fn_setenv()                                 {}
func Fn_shell_error_quark()                      {}
func Fn_shell_parse_argv()                       {}
func Fn_shell_quote()                            {}
func Fn_shell_unquote()                          {}
func Fn_slice_alloc()                            {}
func Fn_slice_alloc0()                           {}
func Fn_slice_copy()                             {}
func Fn_slice_free1()                            {}
func Fn_slice_free_chain_with_offset()           {}
func Fn_slice_get_config()                       {}
func Fn_slice_get_config_state()                 {}
func Fn_slice_set_config()                       {}
func Fn_snprintf()                               {}
func Fn_source_remove()                          {}
func Fn_source_remove_by_funcs_user_data()       {}
func Fn_source_remove_by_user_data()             {}
func Fn_spaced_primes_closest()                  {}
func Fn_spawn_async()                            {}
func Fn_spawn_async_with_pipes()                 {}
func Fn_spawn_close_pid()                        {}
func Fn_spawn_command_line_async()               {}
func Fn_spawn_command_line_sync()                {}
func Fn_spawn_error_quark()                      {}
func Fn_spawn_exit_error_quark()                 {}
func Fn_spawn_sync()                             {}
func Fn_sprintf()                                {}
func Fn_stpcpy()                                 {}
func Fn_str_equal()                              {}
func Fn_str_has_prefix()                         {}
func Fn_str_has_suffix()                         {}
func Fn_str_hash()                               {}
func Fn_strcanon()                               {}
func Fn_strcasecmp()                             {}
func Fn_strchomp()                               {}
func Fn_strchug()                                {}
func Fn_strcompress()                            {}
func Fn_strconcat()                              {}
func Fn_strdelimit()                             {}
func Fn_strdown()                                {}
func Fn_strdup()                                 {}
func Fn_strdup_printf()                          {}
func Fn_strdup_vprintf()                         {}
func Fn_strdupv()                                {}
func Fn_strerror()                               {}
func Fn_strescape()                              {}
func Fn_strfreev()                               {}
func Fn_string_new()                             {}
func Fn_string_new_len()                         {}
func Fn_string_sized_new()                       {}
func Fn_strip_context()                          {}
func Fn_strjoin()                                {}
func Fn_strjoinv()                               {}
func Fn_strlcat()                                {}
func Fn_strlcpy()                                {}
func Fn_strncasecmp()                            {}
func Fn_strndup()                                {}
func Fn_strnfill()                               {}
func Fn_strreverse()                             {}
func Fn_strrstr()                                {}
func Fn_strrstr_len()                            {}
func Fn_strsignal()                              {}
func Fn_strsplit()                               {}
func Fn_strsplit_set()                           {}
func Fn_strstr_len()                             {}
func Fn_strtod()                                 {}
func Fn_strup()                                  {}
func Fn_strv_get_type()                          {}
func Fn_strv_length()                            {}
func Fn_test_add_vtable()                        {}
func Fn_test_assert_expected_messages_internal() {}
func Fn_test_log_type_name()                     {}
func Fn_test_trap_assertions()                   {}
func Fn_thread_error_quark()                     {}
func Fn_thread_exit()                            {}
func Fn_thread_pool_get_max_idle_time()          {}
func Fn_thread_pool_get_max_unused_threads()     {}
func Fn_thread_pool_get_num_unused_threads()     {}
func Fn_thread_pool_set_max_idle_time()          {}
func Fn_thread_pool_set_max_unused_threads()     {}
func Fn_thread_pool_stop_unused_threads()        {}
func Fn_thread_self()                            {}
func Fn_thread_yield()                           {}
func Fn_time_val_from_iso8601()                  {}
func Fn_timeout_add()                            {}
func Fn_timeout_add_full()                       {}
func Fn_timeout_add_seconds()                    {}
func Fn_timeout_add_seconds_full()               {}
func Fn_timeout_source_new()                     {}
func Fn_timeout_source_new_seconds()             {}
func Fn_trash_stack_height()                     {}
func Fn_trash_stack_peek()                       {}
func Fn_trash_stack_pop()                        {}
func Fn_trash_stack_push()                       {}
func Fn_try_malloc()                             {}
func Fn_try_malloc0()                            {}
func Fn_try_realloc()                            {}
func Fn_ucs4_to_utf16()                          {}
func Fn_ucs4_to_utf8()                           {}
func Fn_unichar_break_type()                     {}
func Fn_unichar_combining_class()                {}
func Fn_unichar_digit_value()                    {}
func Fn_unichar_get_mirror_char()                {}
func Fn_unichar_get_script()                     {}
func Fn_unichar_isalnum()                        {}
func Fn_unichar_isalpha()                        {}
func Fn_unichar_iscntrl()                        {}
func Fn_unichar_isdefined()                      {}
func Fn_unichar_isdigit()                        {}
func Fn_unichar_isgraph()                        {}
func Fn_unichar_islower()                        {}
func Fn_unichar_ismark()                         {}
func Fn_unichar_isprint()                        {}
func Fn_unichar_ispunct()                        {}
func Fn_unichar_isspace()                        {}
func Fn_unichar_istitle()                        {}
func Fn_unichar_isupper()                        {}
func Fn_unichar_iswide()                         {}
func Fn_unichar_iswide_cjk()                     {}
func Fn_unichar_isxdigit()                       {}
func Fn_unichar_iszerowidth()                    {}
func Fn_unichar_to_utf8()                        {}
func Fn_unichar_tolower()                        {}
func Fn_unichar_totitle()                        {}
func Fn_unichar_toupper()                        {}
func Fn_unichar_type()                           {}
func Fn_unichar_validate()                       {}
func Fn_unichar_xdigit_value()                   {}
func Fn_unicode_canonical_decomposition()        {}
func Fn_unicode_canonical_ordering()             {}
func Fn_unix_error_quark()                       {}
func Fn_unlink()                                 {}
func Fn_unsetenv()                               {}
func Fn_uri_list_extract_uris()                  {}
func Fn_usleep()                                 {}
func Fn_utf16_to_ucs4()                          {}
func Fn_utf16_to_utf8()                          {}
func Fn_utf8_casefold()                          {}
func Fn_utf8_collate()                           {}
func Fn_utf8_collate_key()                       {}
func Fn_utf8_collate_key_for_filename()          {}
func Fn_utf8_find_next_char()                    {}
func Fn_utf8_find_prev_char()                    {}
func Fn_utf8_get_char()                          {}
func Fn_utf8_get_char_validated()                {}
func Fn_utf8_normalize()                         {}
func Fn_utf8_offset_to_pointer()                 {}
func Fn_utf8_pointer_to_offset()                 {}
func Fn_utf8_prev_char()                         {}
func Fn_utf8_strchr()                            {}
func Fn_utf8_strdown()                           {}
func Fn_utf8_strlen()                            {}
func Fn_utf8_strncpy()                           {}
func Fn_utf8_strrchr()                           {}
func Fn_utf8_strreverse()                        {}
func Fn_utf8_strup()                             {}
func Fn_utf8_to_ucs4()                           {}
func Fn_utf8_to_ucs4_fast()                      {}
func Fn_utf8_to_utf16()                          {}
func Fn_utf8_validate()                          {}
func Fn_variant_get_gtype()                      {}
func Fn_variant_parse()                          {}
func Fn_variant_parse_error_quark()              {}
func Fn_variant_parser_get_error_quark()         {}
func Fn_variant_type_checked_()                  {}
func Fn_variant_type_string_get_depth_()         {}
func Fn_variant_type_string_is_valid()           {}
func Fn_vasprintf()                              {}
func Fn_vfprintf()                               {}
func Fn_vprintf()                                {}
func Fn_vsnprintf()                              {}
func Fn_vsprintf()                               {}
func Fn_warn_message()                           {}
