// Code generated - DO NOT EDIT.
// +build !gobject_2.4,!gobject_2.10,!gobject_2.26

package gobject

// #include <glib-object.h>
import "C"

// bitfields
type ConnectFlags C.GConnectFlags
type ParamFlags C.GParamFlags
type SignalFlags C.GSignalFlags
type SignalMatchType C.GSignalMatchType
type TypeDebugFlags C.GTypeDebugFlags
type TypeFlags C.GTypeFlags
type TypeFundamentalFlags C.GTypeFundamentalFlags

// enumerations

// records
type CClosure C.GCClosure
type Closure C.GClosure
type ClosureNotifyData C.GClosureNotifyData
type EnumClass C.GEnumClass
type EnumValue C.GEnumValue
type FlagsClass C.GFlagsClass
type FlagsValue C.GFlagsValue
type InitiallyUnownedClass C.GInitiallyUnownedClass
type InterfaceInfo C.GInterfaceInfo
type ObjectClass C.GObjectClass
type ObjectConstructParam C.GObjectConstructParam
type ParamSpecClass C.GParamSpecClass
type ParamSpecPool C.GParamSpecPool
type ParamSpecTypeInfo C.GParamSpecTypeInfo
type Parameter C.GParameter
type SignalInvocationHint C.GSignalInvocationHint
type SignalQuery C.GSignalQuery
type TypeClass C.GTypeClass
type TypeFundamentalInfo C.GTypeFundamentalInfo
type TypeInfo C.GTypeInfo
type TypeInstance C.GTypeInstance
type TypeInterface C.GTypeInterface
type TypeModuleClass C.GTypeModuleClass
type TypePluginClass C.GTypePluginClass
type TypeQuery C.GTypeQuery
type TypeValueTable C.GTypeValueTable
type Value C.GValue
type ValueArray C.GValueArray
type WeakRef C.GWeakRef

// classes
type InitiallyUnowned C.GInitiallyUnowned
type Object C.GObject
type ParamSpec C.GParamSpec
type ParamSpecBoolean C.GParamSpecBoolean
type ParamSpecBoxed C.GParamSpecBoxed
type ParamSpecChar C.GParamSpecChar
type ParamSpecDouble C.GParamSpecDouble
type ParamSpecEnum C.GParamSpecEnum
type ParamSpecFlags C.GParamSpecFlags
type ParamSpecFloat C.GParamSpecFloat
type ParamSpecInt C.GParamSpecInt
type ParamSpecInt64 C.GParamSpecInt64
type ParamSpecLong C.GParamSpecLong
type ParamSpecObject C.GParamSpecObject
type ParamSpecParam C.GParamSpecParam
type ParamSpecPointer C.GParamSpecPointer
type ParamSpecString C.GParamSpecString
type ParamSpecUChar C.GParamSpecUChar
type ParamSpecUInt C.GParamSpecUInt
type ParamSpecUInt64 C.GParamSpecUInt64
type ParamSpecULong C.GParamSpecULong
type ParamSpecUnichar C.GParamSpecUnichar
type ParamSpecValueArray C.GParamSpecValueArray
type TypeModule C.GTypeModule

// interfaces
type TypePlugin C.GTypePlugin

// functions
func Fn_boxed_copy()                              {}
func Fn_boxed_free()                              {}
func Fn_boxed_type_register_static()              {}
func Fn_cclosure_marshal_BOOLEAN__BOXED_BOXED()   {}
func Fn_cclosure_marshal_BOOLEAN__FLAGS()         {}
func Fn_cclosure_marshal_STRING__OBJECT_POINTER() {}
func Fn_cclosure_marshal_VOID__BOOLEAN()          {}
func Fn_cclosure_marshal_VOID__BOXED()            {}
func Fn_cclosure_marshal_VOID__CHAR()             {}
func Fn_cclosure_marshal_VOID__DOUBLE()           {}
func Fn_cclosure_marshal_VOID__ENUM()             {}
func Fn_cclosure_marshal_VOID__FLAGS()            {}
func Fn_cclosure_marshal_VOID__FLOAT()            {}
func Fn_cclosure_marshal_VOID__INT()              {}
func Fn_cclosure_marshal_VOID__LONG()             {}
func Fn_cclosure_marshal_VOID__OBJECT()           {}
func Fn_cclosure_marshal_VOID__PARAM()            {}
func Fn_cclosure_marshal_VOID__POINTER()          {}
func Fn_cclosure_marshal_VOID__STRING()           {}
func Fn_cclosure_marshal_VOID__UCHAR()            {}
func Fn_cclosure_marshal_VOID__UINT()             {}
func Fn_cclosure_marshal_VOID__UINT_POINTER()     {}
func Fn_cclosure_marshal_VOID__ULONG()            {}
func Fn_cclosure_marshal_VOID__VOID()             {}
func Fn_cclosure_new()                            {}
func Fn_cclosure_new_object()                     {}
func Fn_cclosure_new_object_swap()                {}
func Fn_cclosure_new_swap()                       {}
func Fn_enum_complete_type_info()                 {}
func Fn_enum_get_value()                          {}
func Fn_enum_get_value_by_name()                  {}
func Fn_enum_get_value_by_nick()                  {}
func Fn_enum_register_static()                    {}
func Fn_flags_complete_type_info()                {}
func Fn_flags_get_first_value()                   {}
func Fn_flags_get_value_by_name()                 {}
func Fn_flags_get_value_by_nick()                 {}
func Fn_flags_register_static()                   {}
func Fn_gtype_get_type()                          {}
func Fn_param_spec_boolean()                      {}
func Fn_param_spec_boxed()                        {}
func Fn_param_spec_char()                         {}
func Fn_param_spec_double()                       {}
func Fn_param_spec_enum()                         {}
func Fn_param_spec_flags()                        {}
func Fn_param_spec_float()                        {}
func Fn_param_spec_int()                          {}
func Fn_param_spec_int64()                        {}
func Fn_param_spec_long()                         {}
func Fn_param_spec_object()                       {}
func Fn_param_spec_param()                        {}
func Fn_param_spec_pointer()                      {}
func Fn_param_spec_pool_new()                     {}
func Fn_param_spec_string()                       {}
func Fn_param_spec_uchar()                        {}
func Fn_param_spec_uint()                         {}
func Fn_param_spec_uint64()                       {}
func Fn_param_spec_ulong()                        {}
func Fn_param_spec_unichar()                      {}
func Fn_param_spec_value_array()                  {}
func Fn_param_type_register_static()              {}
func Fn_param_value_convert()                     {}
func Fn_param_value_defaults()                    {}
func Fn_param_value_set_default()                 {}
func Fn_param_value_validate()                    {}
func Fn_param_values_cmp()                        {}
func Fn_pointer_type_register_static()            {}
func Fn_signal_add_emission_hook()                {}
func Fn_signal_chain_from_overridden()            {}
func Fn_signal_connect_closure()                  {}
func Fn_signal_connect_closure_by_id()            {}
func Fn_signal_connect_data()                     {}
func Fn_signal_connect_object()                   {}
func Fn_signal_emit()                             {}
func Fn_signal_emit_by_name()                     {}
func Fn_signal_emit_valist()                      {}
func Fn_signal_emitv()                            {}
func Fn_signal_get_invocation_hint()              {}
func Fn_signal_handler_block()                    {}
func Fn_signal_handler_disconnect()               {}
func Fn_signal_handler_find()                     {}
func Fn_signal_handler_is_connected()             {}
func Fn_signal_handler_unblock()                  {}
func Fn_signal_handlers_block_matched()           {}
func Fn_signal_handlers_destroy()                 {}
func Fn_signal_handlers_disconnect_matched()      {}
func Fn_signal_handlers_unblock_matched()         {}
func Fn_signal_has_handler_pending()              {}
func Fn_signal_list_ids()                         {}
func Fn_signal_lookup()                           {}
func Fn_signal_name()                             {}
func Fn_signal_new()                              {}
func Fn_signal_new_valist()                       {}
func Fn_signal_newv()                             {}
func Fn_signal_override_class_closure()           {}
func Fn_signal_parse_name()                       {}
func Fn_signal_query()                            {}
func Fn_signal_remove_emission_hook()             {}
func Fn_signal_stop_emission()                    {}
func Fn_signal_stop_emission_by_name()            {}
func Fn_signal_type_cclosure_new()                {}
func Fn_source_set_closure()                      {}
func Fn_source_set_dummy_callback()               {}
func Fn_strdup_value_contents()                   {}
func Fn_type_add_class_cache_func()               {}
func Fn_type_add_instance_private()               {}
func Fn_type_add_interface_dynamic()              {}
func Fn_type_add_interface_static()               {}
func Fn_type_check_class_cast()                   {}
func Fn_type_check_class_is_a()                   {}
func Fn_type_check_instance()                     {}
func Fn_type_check_instance_cast()                {}
func Fn_type_check_instance_is_a()                {}
func Fn_type_check_instance_is_fundamentally_a()  {}
func Fn_type_check_is_value_type()                {}
func Fn_type_check_value()                        {}
func Fn_type_check_value_holds()                  {}
func Fn_type_children()                           {}
func Fn_type_class_adjust_private_offset()        {}
func Fn_type_class_peek()                         {}
func Fn_type_class_ref()                          {}
func Fn_type_create_instance()                    {}
func Fn_type_depth()                              {}
func Fn_type_free_instance()                      {}
func Fn_type_from_name()                          {}
func Fn_type_fundamental()                        {}
func Fn_type_fundamental_next()                   {}
func Fn_type_get_plugin()                         {}
func Fn_type_get_qdata()                          {}
func Fn_type_init()                               {}
func Fn_type_init_with_debug_flags()              {}
func Fn_type_interface_add_prerequisite()         {}
func Fn_type_interface_get_plugin()               {}
func Fn_type_interface_peek()                     {}
func Fn_type_interfaces()                         {}
func Fn_type_is_a()                               {}
func Fn_type_name()                               {}
func Fn_type_name_from_class()                    {}
func Fn_type_name_from_instance()                 {}
func Fn_type_next_base()                          {}
func Fn_type_parent()                             {}
func Fn_type_qname()                              {}
func Fn_type_query()                              {}
func Fn_type_register_dynamic()                   {}
func Fn_type_register_fundamental()               {}
func Fn_type_register_static()                    {}
func Fn_type_remove_class_cache_func()            {}
func Fn_type_set_qdata()                          {}
func Fn_type_test_flags()                         {}
func Fn_type_value_table_peek()                   {}
func Fn_value_register_transform_func()           {}
func Fn_value_type_compatible()                   {}
func Fn_value_type_transformable()                {}
func Fn_bad()                                     {}
