// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package cairo

/*
#include "include/cairo.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// HasImageSurface as defined in internal/<predefine>:24
	HasImageSurface = 1
	// HasRecordingSurface as defined in internal/<predefine>:25
	HasRecordingSurface = 1
	// HasUserFont as defined in internal/<predefine>:26
	HasUserFont = 1
	// HasMimeSurface as defined in internal/<predefine>:27
	HasMimeSurface = 1
	// HasObserverSurface as defined in internal/<predefine>:28
	HasObserverSurface = 1
	// HasPngFunctions as defined in internal/<predefine>:29
	HasPngFunctions = 1
	// HasPsSurface as defined in internal/<predefine>:30
	HasPsSurface = 1
	// HasScriptSurface as defined in internal/<predefine>:31
	HasScriptSurface = 1
	// HasSvgSurface as defined in internal/<predefine>:32
	HasSvgSurface = 1
	// HasFcFont as defined in internal/<predefine>:33
	HasFcFont = 1
	// HasGobjectFunctions as defined in internal/<predefine>:34
	HasGobjectFunctions = 1
	// HasTeeSurface as defined in internal/<predefine>:35
	HasTeeSurface = 1
	// HasFtFont as defined in internal/<predefine>:36
	HasFtFont = 1
	// HasPdfSurface as defined in internal/<predefine>:37
	HasPdfSurface = 1
	// Version as defined in include/cairo.h:68
	Version = 11408
	// MimeTypeJpeg as defined in include/cairo.h:2429
	MimeTypeJpeg = "image/jpeg"
	// MimeTypePng as defined in include/cairo.h:2430
	MimeTypePng = "image/png"
	// MimeTypeJp2 as defined in include/cairo.h:2431
	MimeTypeJp2 = "image/jp2"
	// MimeTypeUri as defined in include/cairo.h:2432
	MimeTypeUri = "text/x-uri"
	// MimeTypeUniqueId as defined in include/cairo.h:2433
	MimeTypeUniqueId = "application/x-cairo.uuid"
	// MimeTypeJbig2 as defined in include/cairo.h:2434
	MimeTypeJbig2 = "application/x-cairo.jbig2"
	// MimeTypeJbig2Global as defined in include/cairo.h:2435
	MimeTypeJbig2Global = "application/x-cairo.jbig2-global"
	// MimeTypeJbig2GlobalId as defined in include/cairo.h:2436
	MimeTypeJbig2GlobalId = "application/x-cairo.jbig2-global-id"
	// VersionMajor as defined in include/cairo-version.h:4
	VersionMajor = 1
	// VersionMinor as defined in include/cairo-version.h:5
	VersionMinor = 14
	// VersionMicro as defined in include/cairo-version.h:6
	VersionMicro = 8
	// HasXcbShmFunctions as defined in include/cairo-features.h:19
	HasXcbShmFunctions = 1
	// HasXcbSurface as defined in include/cairo-features.h:20
	HasXcbSurface = 1
	// HasXlibSurface as defined in include/cairo-features.h:21
	HasXlibSurface = 1
	// HasXlibXrenderSurface as defined in include/cairo-features.h:22
	HasXlibXrenderSurface = 1
)

// Status as declared in include/cairo.h:353
type Status int32

// Status enumeration from include/cairo.h:353
const (
	StatusSuccess                 Status = iota
	StatusNoMemory                Status = 1
	StatusInvalidRestore          Status = 2
	StatusInvalidPopGroup         Status = 3
	StatusNoCurrentPoint          Status = 4
	StatusInvalidMatrix           Status = 5
	StatusInvalidStatus           Status = 6
	StatusNullPointer             Status = 7
	StatusInvalidString           Status = 8
	StatusInvalidPathData         Status = 9
	StatusReadError               Status = 10
	StatusWriteError              Status = 11
	StatusSurfaceFinished         Status = 12
	StatusSurfaceTypeMismatch     Status = 13
	StatusPatternTypeMismatch     Status = 14
	StatusInvalidContent          Status = 15
	StatusInvalidFormat           Status = 16
	StatusInvalidVisual           Status = 17
	StatusFileNotFound            Status = 18
	StatusInvalidDash             Status = 19
	StatusInvalidDscComment       Status = 20
	StatusInvalidIndex            Status = 21
	StatusClipNotRepresentable    Status = 22
	StatusTempFileError           Status = 23
	StatusInvalidStride           Status = 24
	StatusFontTypeMismatch        Status = 25
	StatusUserFontImmutable       Status = 26
	StatusUserFontError           Status = 27
	StatusNegativeCount           Status = 28
	StatusInvalidClusters         Status = 29
	StatusInvalidSlant            Status = 30
	StatusInvalidWeight           Status = 31
	StatusInvalidSize             Status = 32
	StatusUserFontNotImplemented  Status = 33
	StatusDeviceTypeMismatch      Status = 34
	StatusDeviceError             Status = 35
	StatusInvalidMeshConstruction Status = 36
	StatusDeviceFinished          Status = 37
	StatusJbig2GlobalMissing      Status = 38
	StatusLastStatus              Status = 39
)

// Content as declared in include/cairo.h:375
type Content int32

// Content enumeration from include/cairo.h:375
const (
	ContentColor      Content = 4096
	ContentAlpha      Content = 8192
	ContentColorAlpha Content = 12288
)

// Format as declared in include/cairo.h:416
type Format int32

// Format enumeration from include/cairo.h:416
const (
	FormatInvalid  Format = -1
	FormatArgb32   Format = 0
	FormatRgb24    Format = 1
	FormatA8       Format = 2
	FormatA1       Format = 3
	FormatRgb16565 Format = 4
	FormatRgb30    Format = 5
)

// Operator as declared in include/cairo.h:639
type Operator int32

// Operator enumeration from include/cairo.h:639
const (
	OperatorClear         Operator = iota
	OperatorSource        Operator = 1
	OperatorOver          Operator = 2
	OperatorIn            Operator = 3
	OperatorOut           Operator = 4
	OperatorAtop          Operator = 5
	OperatorDest          Operator = 6
	OperatorDestOver      Operator = 7
	OperatorDestIn        Operator = 8
	OperatorDestOut       Operator = 9
	OperatorDestAtop      Operator = 10
	OperatorXor           Operator = 11
	OperatorAdd           Operator = 12
	OperatorSaturate      Operator = 13
	OperatorMultiply      Operator = 14
	OperatorScreen        Operator = 15
	OperatorOverlay       Operator = 16
	OperatorDarken        Operator = 17
	OperatorLighten       Operator = 18
	OperatorColorDodge    Operator = 19
	OperatorColorBurn     Operator = 20
	OperatorHardLight     Operator = 21
	OperatorSoftLight     Operator = 22
	OperatorDifference    Operator = 23
	OperatorExclusion     Operator = 24
	OperatorHslHue        Operator = 25
	OperatorHslSaturation Operator = 26
	OperatorHslColor      Operator = 27
	OperatorHslLuminosity Operator = 28
)

// Antialias as declared in include/cairo.h:713
type Antialias int32

// Antialias enumeration from include/cairo.h:713
const (
	AntialiasDefault  Antialias = iota
	AntialiasNone     Antialias = 1
	AntialiasGray     Antialias = 2
	AntialiasSubpixel Antialias = 3
	AntialiasFast     Antialias = 4
	AntialiasGood     Antialias = 5
	AntialiasBest     Antialias = 6
)

// FillRule as declared in include/cairo.h:748
type FillRule int32

// FillRule enumeration from include/cairo.h:748
const (
	FillRuleWinding FillRule = iota
	FillRuleEvenOdd FillRule = 1
)

// LineCap as declared in include/cairo.h:772
type LineCap int32

// LineCap enumeration from include/cairo.h:772
const (
	LineCapButt   LineCap = iota
	LineCapRound  LineCap = 1
	LineCapSquare LineCap = 2
)

// LineJoin as declared in include/cairo.h:796
type LineJoin int32

// LineJoin enumeration from include/cairo.h:796
const (
	LineJoinMiter LineJoin = iota
	LineJoinRound LineJoin = 1
	LineJoinBevel LineJoin = 2
)

// TextClusterFlags as declared in include/cairo.h:1143
type TextClusterFlags int32

// TextClusterFlags enumeration from include/cairo.h:1143
const (
	TextClusterFlagBackward TextClusterFlags = 1
)

// FontSlant as declared in include/cairo.h:1248
type FontSlant int32

// FontSlant enumeration from include/cairo.h:1248
const (
	FontSlantNormal  FontSlant = iota
	FontSlantItalic  FontSlant = 1
	FontSlantOblique FontSlant = 2
)

// FontWeight as declared in include/cairo.h:1262
type FontWeight int32

// FontWeight enumeration from include/cairo.h:1262
const (
	FontWeightNormal FontWeight = iota
	FontWeightBold   FontWeight = 1
)

// SubpixelOrder as declared in include/cairo.h:1289
type SubpixelOrder int32

// SubpixelOrder enumeration from include/cairo.h:1289
const (
	SubpixelOrderDefault SubpixelOrder = iota
	SubpixelOrderRgb     SubpixelOrder = 1
	SubpixelOrderBgr     SubpixelOrder = 2
	SubpixelOrderVrgb    SubpixelOrder = 3
	SubpixelOrderVbgr    SubpixelOrder = 4
)

// HintStyle as declared in include/cairo.h:1321
type HintStyle int32

// HintStyle enumeration from include/cairo.h:1321
const (
	HintStyleDefault HintStyle = iota
	HintStyleNone    HintStyle = 1
	HintStyleSlight  HintStyle = 2
	HintStyleMedium  HintStyle = 3
	HintStyleFull    HintStyle = 4
)

// HintMetrics as declared in include/cairo.h:1342
type HintMetrics int32

// HintMetrics enumeration from include/cairo.h:1342
const (
	HintMetricsDefault HintMetrics = iota
	HintMetricsOff     HintMetrics = 1
	HintMetricsOn      HintMetrics = 2
)

// FontType as declared in include/cairo.h:1552
type FontType int32

// FontType enumeration from include/cairo.h:1552
const (
	FontTypeToy    FontType = iota
	FontTypeFt     FontType = 1
	FontTypeWin32  FontType = 2
	FontTypeQuartz FontType = 3
	FontTypeUser   FontType = 4
)

// PathDataType as declared in include/cairo.h:1972
type PathDataType int32

// PathDataType enumeration from include/cairo.h:1972
const (
	PathMoveTo    PathDataType = iota
	PathLineTo    PathDataType = 1
	PathCurveTo   PathDataType = 2
	PathClosePath PathDataType = 3
)

// DeviceType as declared in include/cairo.h:2148
type DeviceType int32

// DeviceType enumeration from include/cairo.h:2148
const (
	DeviceTypeDrm     DeviceType = iota
	DeviceTypeGl      DeviceType = 1
	DeviceTypeScript  DeviceType = 2
	DeviceTypeXcb     DeviceType = 3
	DeviceTypeXlib    DeviceType = 4
	DeviceTypeXml     DeviceType = 5
	DeviceTypeCogl    DeviceType = 6
	DeviceTypeWin32   DeviceType = 7
	DeviceTypeInvalid DeviceType = -1
)

// SurfaceObserverMode as declared in include/cairo.h:2226
type SurfaceObserverMode int32

// SurfaceObserverMode enumeration from include/cairo.h:2226
const (
	SurfaceObserverNormal           SurfaceObserverMode = iota
	SurfaceObserverRecordOperations SurfaceObserverMode = 1
)

// SurfaceType as declared in include/cairo.h:2398
type SurfaceType int32

// SurfaceType enumeration from include/cairo.h:2398
const (
	SurfaceTypeImage         SurfaceType = iota
	SurfaceTypePdf           SurfaceType = 1
	SurfaceTypePs            SurfaceType = 2
	SurfaceTypeXlib          SurfaceType = 3
	SurfaceTypeXcb           SurfaceType = 4
	SurfaceTypeGlitz         SurfaceType = 5
	SurfaceTypeQuartz        SurfaceType = 6
	SurfaceTypeWin32         SurfaceType = 7
	SurfaceTypeBeos          SurfaceType = 8
	SurfaceTypeDirectfb      SurfaceType = 9
	SurfaceTypeSvg           SurfaceType = 10
	SurfaceTypeOs2           SurfaceType = 11
	SurfaceTypeWin32Printing SurfaceType = 12
	SurfaceTypeQuartzImage   SurfaceType = 13
	SurfaceTypeScript        SurfaceType = 14
	SurfaceTypeQt            SurfaceType = 15
	SurfaceTypeRecording     SurfaceType = 16
	SurfaceTypeVg            SurfaceType = 17
	SurfaceTypeGl            SurfaceType = 18
	SurfaceTypeDrm           SurfaceType = 19
	SurfaceTypeTee           SurfaceType = 20
	SurfaceTypeXml           SurfaceType = 21
	SurfaceTypeSkia          SurfaceType = 22
	SurfaceTypeSubsurface    SurfaceType = 23
	SurfaceTypeCogl          SurfaceType = 24
)

// PatternType as declared in include/cairo.h:2802
type PatternType int32

// PatternType enumeration from include/cairo.h:2802
const (
	PatternTypeSolid        PatternType = iota
	PatternTypeSurface      PatternType = 1
	PatternTypeLinear       PatternType = 2
	PatternTypeRadial       PatternType = 3
	PatternTypeMesh         PatternType = 4
	PatternTypeRasterSource PatternType = 5
)

// Extend as declared in include/cairo.h:2892
type Extend int32

// Extend enumeration from include/cairo.h:2892
const (
	ExtendNone    Extend = iota
	ExtendRepeat  Extend = 1
	ExtendReflect Extend = 2
	ExtendPad     Extend = 3
)

// Filter as declared in include/cairo.h:2927
type Filter int32

// Filter enumeration from include/cairo.h:2927
const (
	FilterFast     Filter = iota
	FilterGood     Filter = 1
	FilterBest     Filter = 2
	FilterNearest  Filter = 3
	FilterBilinear Filter = 4
	FilterGaussian Filter = 5
)

// RegionOverlap as declared in include/cairo.h:3066
type RegionOverlap int32

// RegionOverlap enumeration from include/cairo.h:3066
const (
	RegionOverlapIn   RegionOverlap = iota
	RegionOverlapOut  RegionOverlap = 1
	RegionOverlapPart RegionOverlap = 2
)
