// This is a generated file - DO NOT EDIT

package gobject

// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <glib-object.h>
// #include <stdlib.h>
import "C"

const PARAM_MASK int = C.G_PARAM_MASK
const PARAM_STATIC_STRINGS int = C.G_PARAM_STATIC_STRINGS
const PARAM_USER_SHIFT int = C.G_PARAM_USER_SHIFT
const SIGNAL_FLAGS_MASK int = C.G_SIGNAL_FLAGS_MASK
const SIGNAL_MATCH_MASK int = C.G_SIGNAL_MATCH_MASK

// Unsupported : type GLib.Type for TYPE_FLAG_RESERVED_ID_BIT

const TYPE_FUNDAMENTAL_MAX int = C.G_TYPE_FUNDAMENTAL_MAX
const TYPE_FUNDAMENTAL_SHIFT int = C.G_TYPE_FUNDAMENTAL_SHIFT
const TYPE_RESERVED_BSE_FIRST int = C.G_TYPE_RESERVED_BSE_FIRST
const TYPE_RESERVED_BSE_LAST int = C.G_TYPE_RESERVED_BSE_LAST
const TYPE_RESERVED_GLIB_FIRST int = C.G_TYPE_RESERVED_GLIB_FIRST
const TYPE_RESERVED_GLIB_LAST int = C.G_TYPE_RESERVED_GLIB_LAST
const TYPE_RESERVED_USER_FIRST int = C.G_TYPE_RESERVED_USER_FIRST

// Blacklisted : VALUE_COLLECT_FORMAT_MAX_LENGTH

const VALUE_NOCOPY_CONTENTS int = C.G_VALUE_NOCOPY_CONTENTS
