// Code generated - DO NOT EDIT.

package soup

const ADDRESS_ANY_PORT int32 = "0"

// UNSUPPORTED : ADDRESS_FAMILY
// UNSUPPORTED : ADDRESS_NAME
// UNSUPPORTED : ADDRESS_PHYSICAL
// UNSUPPORTED : ADDRESS_PORT
// UNSUPPORTED : ADDRESS_PROTOCOL
// UNSUPPORTED : ADDRESS_SOCKADDR
// UNSUPPORTED : AUTH_DOMAIN_ADD_PATH
// UNSUPPORTED : AUTH_DOMAIN_BASIC_AUTH_CALLBACK
// UNSUPPORTED : AUTH_DOMAIN_BASIC_AUTH_DATA
const AUTH_DOMAIN_BASIC_H int32 = "1"

// UNSUPPORTED : AUTH_DOMAIN_DIGEST_AUTH_CALLBACK
// UNSUPPORTED : AUTH_DOMAIN_DIGEST_AUTH_DATA
const AUTH_DOMAIN_DIGEST_H int32 = "1"

// UNSUPPORTED : AUTH_DOMAIN_FILTER
// UNSUPPORTED : AUTH_DOMAIN_FILTER_DATA
// UNSUPPORTED : AUTH_DOMAIN_GENERIC_AUTH_CALLBACK
// UNSUPPORTED : AUTH_DOMAIN_GENERIC_AUTH_DATA
const AUTH_DOMAIN_H int32 = "1"

// UNSUPPORTED : AUTH_DOMAIN_PROXY
// UNSUPPORTED : AUTH_DOMAIN_REALM
// UNSUPPORTED : AUTH_DOMAIN_REMOVE_PATH
const AUTH_H int32 = "1"

// UNSUPPORTED : AUTH_HOST
// UNSUPPORTED : AUTH_IS_AUTHENTICATED
// UNSUPPORTED : AUTH_IS_FOR_PROXY
const AUTH_MANAGER_H int32 = "1"

// UNSUPPORTED : AUTH_REALM
// UNSUPPORTED : AUTH_SCHEME_NAME
const CACHE_H int32 = "1"
const CHAR_HTTP_CTL int32 = "16"
const CHAR_HTTP_SEPARATOR int32 = "8"
const CHAR_URI_GEN_DELIMS int32 = "2"
const CHAR_URI_PERCENT_ENCODED int32 = "1"
const CHAR_URI_SUB_DELIMS int32 = "4"
const CONTENT_DECODER_H int32 = "1"
const CONTENT_SNIFFER_H int32 = "1"
const COOKIE_H int32 = "1"

// UNSUPPORTED : COOKIE_JAR_ACCEPT_POLICY
// UNSUPPORTED : COOKIE_JAR_DB_FILENAME
const COOKIE_JAR_DB_H int32 = "1"
const COOKIE_JAR_H int32 = "1"

// UNSUPPORTED : COOKIE_JAR_READ_ONLY
// UNSUPPORTED : COOKIE_JAR_TEXT_FILENAME
const COOKIE_JAR_TEXT_H int32 = "1"
const COOKIE_MAX_AGE_ONE_DAY int32 = "0"
const COOKIE_MAX_AGE_ONE_HOUR int32 = "3600"
const COOKIE_MAX_AGE_ONE_WEEK int32 = "0"
const COOKIE_MAX_AGE_ONE_YEAR int32 = "0"
const DATE_H int32 = "1"
const FORM_H int32 = "1"

// UNSUPPORTED : FORM_MIME_TYPE_MULTIPART
// UNSUPPORTED : FORM_MIME_TYPE_URLENCODED
const HEADERS_H int32 = "1"
const LOGGER_H int32 = "1"

// UNSUPPORTED : LOGGER_LEVEL
// UNSUPPORTED : LOGGER_MAX_BODY_SIZE
const MAJOR_VERSION int32 = "2"
const MESSAGE_BODY_H int32 = "1"

// UNSUPPORTED : MESSAGE_FIRST_PARTY
// UNSUPPORTED : MESSAGE_FLAGS
const MESSAGE_H int32 = "1"
const MESSAGE_HEADERS_H int32 = "1"

// UNSUPPORTED : MESSAGE_HTTP_VERSION
// UNSUPPORTED : MESSAGE_METHOD
// UNSUPPORTED : MESSAGE_PRIORITY
// UNSUPPORTED : MESSAGE_REASON_PHRASE
// UNSUPPORTED : MESSAGE_REQUEST_BODY
// UNSUPPORTED : MESSAGE_REQUEST_BODY_DATA
// UNSUPPORTED : MESSAGE_REQUEST_HEADERS
// UNSUPPORTED : MESSAGE_RESPONSE_BODY
// UNSUPPORTED : MESSAGE_RESPONSE_BODY_DATA
// UNSUPPORTED : MESSAGE_RESPONSE_HEADERS
// UNSUPPORTED : MESSAGE_SERVER_SIDE
// UNSUPPORTED : MESSAGE_STATUS_CODE
// UNSUPPORTED : MESSAGE_TLS_CERTIFICATE
// UNSUPPORTED : MESSAGE_TLS_ERRORS
// UNSUPPORTED : MESSAGE_URI
const METHOD_H int32 = "1"
const MICRO_VERSION int32 = "1"
const MINOR_VERSION int32 = "62"
const MISC_H int32 = "1"
const MULTIPART_H int32 = "1"
const MULTIPART_INPUT_STREAM_H int32 = "1"
const PASSWORD_MANAGER_H int32 = "1"
const PROXY_RESOLVER_DEFAULT_H int32 = "1"
const PROXY_URI_RESOLVER_H int32 = "1"
const REQUESTER_H int32 = "1"
const REQUEST_DATA_H int32 = "1"
const REQUEST_FILE_H int32 = "1"
const REQUEST_H int32 = "1"
const REQUEST_HTTP_H int32 = "1"

// UNSUPPORTED : REQUEST_SESSION
// UNSUPPORTED : REQUEST_URI
// UNSUPPORTED : SERVER_ASYNC_CONTEXT
const SERVER_H int32 = "1"

// UNSUPPORTED : SERVER_HTTPS_ALIASES
// UNSUPPORTED : SERVER_HTTP_ALIASES
// UNSUPPORTED : SERVER_INTERFACE
// UNSUPPORTED : SERVER_PORT
// UNSUPPORTED : SERVER_RAW_PATHS
// UNSUPPORTED : SERVER_SERVER_HEADER
// UNSUPPORTED : SERVER_SSL_CERT_FILE
// UNSUPPORTED : SERVER_SSL_KEY_FILE
// UNSUPPORTED : SERVER_TLS_CERTIFICATE
// UNSUPPORTED : SESSION_ACCEPT_LANGUAGE
// UNSUPPORTED : SESSION_ACCEPT_LANGUAGE_AUTO
// UNSUPPORTED : SESSION_ADD_FEATURE
// UNSUPPORTED : SESSION_ADD_FEATURE_BY_TYPE
// UNSUPPORTED : SESSION_ASYNC_CONTEXT
const SESSION_ASYNC_H int32 = "1"
const SESSION_FEATURE_H int32 = "1"
const SESSION_H int32 = "1"

// UNSUPPORTED : SESSION_HTTPS_ALIASES
// UNSUPPORTED : SESSION_HTTP_ALIASES
// UNSUPPORTED : SESSION_IDLE_TIMEOUT
// UNSUPPORTED : SESSION_LOCAL_ADDRESS
// UNSUPPORTED : SESSION_MAX_CONNS
// UNSUPPORTED : SESSION_MAX_CONNS_PER_HOST
// UNSUPPORTED : SESSION_PROXY_RESOLVER
// UNSUPPORTED : SESSION_PROXY_URI
// UNSUPPORTED : SESSION_REMOVE_FEATURE_BY_TYPE
// UNSUPPORTED : SESSION_SSL_CA_FILE
// UNSUPPORTED : SESSION_SSL_STRICT
// UNSUPPORTED : SESSION_SSL_USE_SYSTEM_CA_FILE
const SESSION_SYNC_H int32 = "1"

// UNSUPPORTED : SESSION_TIMEOUT
// UNSUPPORTED : SESSION_TLS_DATABASE
// UNSUPPORTED : SESSION_TLS_INTERACTION
// UNSUPPORTED : SESSION_USER_AGENT
// UNSUPPORTED : SESSION_USE_NTLM
// UNSUPPORTED : SESSION_USE_THREAD_CONTEXT
// UNSUPPORTED : SOCKET_ASYNC_CONTEXT
// UNSUPPORTED : SOCKET_FLAG_NONBLOCKING
const SOCKET_H int32 = "1"

// UNSUPPORTED : SOCKET_IS_SERVER
// UNSUPPORTED : SOCKET_LOCAL_ADDRESS
// UNSUPPORTED : SOCKET_REMOTE_ADDRESS
// UNSUPPORTED : SOCKET_SSL_CREDENTIALS
// UNSUPPORTED : SOCKET_SSL_FALLBACK
// UNSUPPORTED : SOCKET_SSL_STRICT
// UNSUPPORTED : SOCKET_TIMEOUT
// UNSUPPORTED : SOCKET_TLS_CERTIFICATE
// UNSUPPORTED : SOCKET_TLS_ERRORS
// UNSUPPORTED : SOCKET_TRUSTED_CERTIFICATE
// UNSUPPORTED : SOCKET_USE_THREAD_CONTEXT
const STATUS_H int32 = "1"
const TYPES_H int32 = "1"
const URI_H int32 = "1"
const VALUE_UTILS_H int32 = "1"
const VERSION_MIN_REQUIRED int32 = "2"
const XMLRPC_H int32 = "1"
const XMLRPC_OLD_H int32 = "1"
