// Code generated - DO NOT EDIT.

package soup

// AddCompletion is a representation of the C type soup_add_completion.
// AddIdle is a representation of the C type soup_add_idle.
// AddIoWatch is a representation of the C type soup_add_io_watch.
// AddTimeout is a representation of the C type soup_add_timeout.
// CheckVersion is a representation of the C type soup_check_version.
// CookieParse is a representation of the C type soup_cookie_parse.
// CookiesFree is a representation of the C type soup_cookies_free.
// CookiesFromRequest is a representation of the C type soup_cookies_from_request.
// CookiesFromResponse is a representation of the C type soup_cookies_from_response.
// CookiesToCookieHeader is a representation of the C type soup_cookies_to_cookie_header.
// CookiesToRequest is a representation of the C type soup_cookies_to_request.
// CookiesToResponse is a representation of the C type soup_cookies_to_response.
// FormDecode is a representation of the C type soup_form_decode.
// FormDecodeMultipart is a representation of the C type soup_form_decode_multipart.
// FormEncode is a representation of the C type soup_form_encode.
// FormEncodeDatalist is a representation of the C type soup_form_encode_datalist.
// FormEncodeHash is a representation of the C type soup_form_encode_hash.
// FormEncodeValist is a representation of the C type soup_form_encode_valist.
// FormRequestNew is a representation of the C type soup_form_request_new.
// FormRequestNewFromDatalist is a representation of the C type soup_form_request_new_from_datalist.
// FormRequestNewFromHash is a representation of the C type soup_form_request_new_from_hash.
// FormRequestNewFromMultipart is a representation of the C type soup_form_request_new_from_multipart.
// GetMajorVersion is a representation of the C type soup_get_major_version.
// GetMicroVersion is a representation of the C type soup_get_micro_version.
// GetMinorVersion is a representation of the C type soup_get_minor_version.
// HeaderContains is a representation of the C type soup_header_contains.
// HeaderFreeList is a representation of the C type soup_header_free_list.
// HeaderFreeParamList is a representation of the C type soup_header_free_param_list.
// HeaderGStringAppendParam is a representation of the C type soup_header_g_string_append_param.
// HeaderGStringAppendParamQuoted is a representation of the C type soup_header_g_string_append_param_quoted.
// HeaderParseList is a representation of the C type soup_header_parse_list.
// HeaderParseParamList is a representation of the C type soup_header_parse_param_list.
// HeaderParseQualityList is a representation of the C type soup_header_parse_quality_list.
// HeaderParseSemiParamList is a representation of the C type soup_header_parse_semi_param_list.
// HeadersParse is a representation of the C type soup_headers_parse.
// HeadersParseRequest is a representation of the C type soup_headers_parse_request.
// HeadersParseResponse is a representation of the C type soup_headers_parse_response.
// HeadersParseStatusLine is a representation of the C type soup_headers_parse_status_line.
// HttpErrorQuark is a representation of the C type soup_http_error_quark.
// MessageHeadersIterInit is a representation of the C type soup_message_headers_iter_init.
// RequestErrorQuark is a representation of the C type soup_request_error_quark.
// RequesterErrorQuark is a representation of the C type soup_requester_error_quark.
// StatusGetPhrase is a representation of the C type soup_status_get_phrase.
// StatusProxify is a representation of the C type soup_status_proxify.
// StrCaseEqual is a representation of the C type soup_str_case_equal.
// StrCaseHash is a representation of the C type soup_str_case_hash.
// TldDomainIsPublicSuffix is a representation of the C type soup_tld_domain_is_public_suffix.
// TldErrorQuark is a representation of the C type soup_tld_error_quark.
// TldGetBaseDomain is a representation of the C type soup_tld_get_base_domain.
// UriDecode is a representation of the C type soup_uri_decode.
// UriEncode is a representation of the C type soup_uri_encode.
// UriNormalize is a representation of the C type soup_uri_normalize.
// ValueArrayAppend is a representation of the C type soup_value_array_append.
// ValueArrayAppendVals is a representation of the C type soup_value_array_append_vals.
// ValueArrayFromArgs is a representation of the C type soup_value_array_from_args.
// ValueArrayGetNth is a representation of the C type soup_value_array_get_nth.
// ValueArrayInsert is a representation of the C type soup_value_array_insert.
// ValueArrayNew is a representation of the C type soup_value_array_new.
// ValueArrayNewWithVals is a representation of the C type soup_value_array_new_with_vals.
// ValueArrayToArgs is a representation of the C type soup_value_array_to_args.
// ValueHashInsert is a representation of the C type soup_value_hash_insert.
// ValueHashInsertVals is a representation of the C type soup_value_hash_insert_vals.
// ValueHashInsertValue is a representation of the C type soup_value_hash_insert_value.
// ValueHashLookup is a representation of the C type soup_value_hash_lookup.
// ValueHashLookupVals is a representation of the C type soup_value_hash_lookup_vals.
// ValueHashNew is a representation of the C type soup_value_hash_new.
// ValueHashNewWithVals is a representation of the C type soup_value_hash_new_with_vals.
// WebsocketClientPrepareHandshake is a representation of the C type soup_websocket_client_prepare_handshake.
// WebsocketClientVerifyHandshake is a representation of the C type soup_websocket_client_verify_handshake.
// WebsocketErrorGetQuark is a representation of the C type soup_websocket_error_get_quark.
// WebsocketServerCheckHandshake is a representation of the C type soup_websocket_server_check_handshake.
// WebsocketServerProcessHandshake is a representation of the C type soup_websocket_server_process_handshake.
// XmlrpcBuildFault is a representation of the C type soup_xmlrpc_build_fault.
// XmlrpcBuildMethodCall is a representation of the C type soup_xmlrpc_build_method_call.
// XmlrpcBuildMethodResponse is a representation of the C type soup_xmlrpc_build_method_response.
// XmlrpcBuildRequest is a representation of the C type soup_xmlrpc_build_request.
// XmlrpcBuildResponse is a representation of the C type soup_xmlrpc_build_response.
// XmlrpcErrorQuark is a representation of the C type soup_xmlrpc_error_quark.
// XmlrpcExtractMethodCall is a representation of the C type soup_xmlrpc_extract_method_call.
// XmlrpcExtractMethodResponse is a representation of the C type soup_xmlrpc_extract_method_response.
// XmlrpcFaultQuark is a representation of the C type soup_xmlrpc_fault_quark.
// XmlrpcMessageNew is a representation of the C type soup_xmlrpc_message_new.
// XmlrpcMessageSetFault is a representation of the C type soup_xmlrpc_message_set_fault.
// XmlrpcMessageSetResponse is a representation of the C type soup_xmlrpc_message_set_response.
// XmlrpcParseMethodCall is a representation of the C type soup_xmlrpc_parse_method_call.
// XmlrpcParseMethodResponse is a representation of the C type soup_xmlrpc_parse_method_response.
// XmlrpcParseRequest is a representation of the C type soup_xmlrpc_parse_request.
// XmlrpcParseResponse is a representation of the C type soup_xmlrpc_parse_response.
// XmlrpcRequestNew is a representation of the C type soup_xmlrpc_request_new.
// XmlrpcSetFault is a representation of the C type soup_xmlrpc_set_fault.
// XmlrpcSetResponse is a representation of the C type soup_xmlrpc_set_response.
// XmlrpcVariantGetDatetime is a representation of the C type soup_xmlrpc_variant_get_datetime.
// XmlrpcVariantNewDatetime is a representation of the C type soup_xmlrpc_variant_new_datetime.
